Populate joblist table for gateway jobs
ubccr/xdmod pull request #1411
Opened 2020-08-06 21:55 UTC by jsperhac

## Description
- Break out aggregation by day from that by month, quarter, year
- Populate day aggregation job_id_list, last_modified, and id columns
- Create and populate jobfact_by_day_joblist table for gateways

These schema changes are needed to enable direct access to jobs performance records by drilldown from gateways realm. 

## Motivation and Context

Support drilldown to jobs performance records in gateways realm (where this access is permitted by ACLs)

## Tests performed

Deployed in a Docker; ran all etl v2 governing gateways schema bootstrapping, ingestion, aggregation

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2020-09-17 12:26 UTC, jtpalmer commented on configuration/rawstatistics.d/30_gateways.json
> +                "documentation": "HIERARCHY_BOTTOM_LEVEL_INFO",
Just as an FYI for now, I'm working on changing the `HIERARCHY_` substitutions to match the style used by the ETL configuration files (See #1448).

2020-09-22 17:30 UTC, jtpalmer requested changes
I merged in those variable substitution changes, here's what should change.

2020-09-22 17:30 UTC, jtpalmer commented on configuration/rawstatistics.d/30_gateways.json
> +                "name": "HIERARCHY_TOP_LEVEL_LABEL",
```suggestion
                "name": "${HIERARCHY_TOP_LEVEL_LABEL}",
```

2020-09-22 17:30 UTC, jtpalmer commented on configuration/rawstatistics.d/30_gateways.json
> +                "documentation": "HIERARCHY_TOP_LEVEL_INFO",
```suggestion
                "documentation": "${HIERARCHY_TOP_LEVEL_INFO}",
```

2020-09-22 17:30 UTC, jtpalmer commented on configuration/rawstatistics.d/30_gateways.json
> +                "name": "HIERARCHY_MIDDLE_LEVEL_LABEL",
```suggestion
                "name": "${HIERARCHY_MIDDLE_LEVEL_LABEL}",
```

2020-09-22 17:30 UTC, jtpalmer commented on configuration/rawstatistics.d/30_gateways.json
> +                "documentation": "HIERARCHY_MIDDLE_LEVEL_INFO",
```suggestion
                "documentation": "${HIERARCHY_MIDDLE_LEVEL_INFO}",
```

2020-09-22 17:30 UTC, jtpalmer commented on configuration/rawstatistics.d/30_gateways.json
> +                "name": "HIERARCHY_BOTTOM_LEVEL_LABEL",
```suggestion
                "name": "${HIERARCHY_BOTTOM_LEVEL_LABEL}",
```

2020-09-22 17:30 UTC, jtpalmer commented on configuration/rawstatistics.d/30_gateways.json
> +                "documentation": "HIERARCHY_BOTTOM_LEVEL_INFO",
```suggestion
                "documentation": "${HIERARCHY_BOTTOM_LEVEL_INFO}",
```

2021-01-08 20:23 UTC, jsperhac commented on configuration/rawstatistics.d/30_gateways.json
> +                "documentation": "HIERARCHY_BOTTOM_LEVEL_INFO",
The HIERARCHY_ substitutions for the rawstatistics.d file have been made as suggested.

2021-01-09 16:27 UTC, jsperhac commented
@jtpalmer, I have a question about the component tests for data export. I see test failures that seem to be expecting array elements with [specific numeric keys](https://app.shippable.com/github/ubccr/xdmod/runs/6466/1/console). 

Updates to the component tests for the new realm don't help, since there are gaps in the keys; see my [most recent commit](https://github.com/ubccr/xdmod/pull/1411/commits/beed800cb8abbdceb7ed8413468d35a3c5644e6d). Am I missing something, or do we need an accommodation similar to the RawStatisticsConfiguration getRawDataRealms() method?

2021-01-11 15:57 UTC, jtpalmer commented
I think the test failures are due to more of my `array_filter` bugs.  I created #1481 to fix that.

2021-03-08 15:33 UTC, jsperhac commented
> I merged in those variable substitution changes, here's what should change.

These have been addressed.

2021-03-10 14:49 UTC, jtpalmer approved these changes

2021-03-11 14:40 UTC, jtpalmer approved these changes

2021-03-11 14:43 UTC, merged