Fix institution loading during manual user creation
ubccr/xdmod pull request #1446
Opened 2020-09-11 17:11 UTC by jtpalmer

## Description

Updates the `TGUserDropDown` (used for the "Map To" field when creating users in the internal dashboard) to execute the cascade options after the field is set programmatically. (Previously the cascade options were only executed after the `select` event which is only triggered by a user selecting an item from the drop down.)

## Motivation and Context

Using the "Find" option during user creation wasn't setting the institution which then produces an error message when attempting to create the user.

https://app.asana.com/0/807770147051221/1193376020829900/f

## Tests performed

Tested manually.

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2020-09-11 17:40 UTC, ryanrath approved these changes
Looks good as soon as Shippable finishes passing.

2020-09-15 17:34 UTC, ryanrath requested changes
Looks good minus function argument names.

2020-09-15 17:34 UTC, ryanrath commented on html/gui/js/TGUserDropDown.js
> +    initializeWithValue: function (v, l, c) {
Yay for more docblocks! Personally, I think these one letter variables could use an re-name. Especially since your're adding a new one anyway.

2020-09-15 19:22 UTC, jtpalmer commented on html/gui/js/TGUserDropDown.js
> +    initializeWithValue: function (v, l, c) {
Let me know if you have any suggestions for the variable names.  I'm not really sure what the old ones were intended to mean.

2020-09-15 19:33 UTC, ryanrath commented on html/gui/js/TGUserDropDown.js
> +    initializeWithValue: function (v, l, c) {
sure, I mean you have the descriptions of the variables there so you could base 'um off of that. Maybe something like: 

```
initializeWithValue: function(personId, personDisplay, cascade);
```
or a little more "generic" 

```
initializeWithValue: function(value, displayValue, cascade); 
```

or something else entirely if you have other ideas. These were just off the top of my head.

2020-09-15 19:35 UTC, ryanrath approved these changes

2020-09-16 11:06 UTC, merged