Migrate Logging: Redux
ubccr/xdmod pull request #1461
Opened 2020-10-29 20:25 UTC by ryanrath

## Description
This PR swaps all Pear Log usage w/ Monolog. 
  - Added a new `CCR\Logging` class that takes the place of `CCR\Log` and utilizes Monolog. 
  - Maintained usage of general log settings in portal_settings.ini 
  - Removed usage of the custom `trace` level for now, but this can be re-added if we create a fork of Monolog as we did w/ Log. 
  - Updated / Added doc blocks to reflect using Monolog vs. Pear. 
  - A few minor updates to some of our tests as Monolog uppercases the level name. 
  - The one big difference between Pear / Monolog I found was that Monolog does not support non-string log messages out of the box. To resolve this I created a new class `\CCR\Logger` that is utilized in `CCR\Log::factory` and `\CCR\Log::singleton`. This class provides a shim layer between our code that provides arrays as log messages & Monolog that will json_encode these messages before passing them on to the default Monolog handlers.

## Motivation and Context
This PR came about from looking at what would be required to update XDMoD to support integrating Symfony Flex which requires PHP7. After speaking with Jeff about his students work towards the Centos8 / PHP7 goal he pointed me to https://docs.google.com/document/d/1fIr5ZzTrYdfO3aWP_sNouC-iojNfePqn3axMapJVsu4 which documents some of the currently known blockers for migrating XDMoD to Centos8 / PHP7. I started experimenting w/ a local docker image based on Jeff's students work and noticed that Pear Log required MDB2 which is not compatible w/ PHP7. After a brief conversation he had mentioned that we should probably replace our Logging prior to moving to PHP7, which got me thinking about how hard it would be to actually do. Turns out that it wasn't hard at all, just tedious. After this PR is merged I have a branch ready to go w/ the basics of centos8 support for XDMoD. 

## Tests performed
All automated tests for OpenXDMoD fresh install & upgrade

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2020-10-30 13:49 UTC, jpwhite4 commented on classes/DB/PDODBIngestor.php
> +    public function setLogger(\Psr\Log\LoggerInterface $logger)
I'm very wary of adding TODOs to the code. Please can you explain why this function has been added and what is the impact of having the empty implementation

2020-10-30 14:07 UTC, ryanrath commented on classes/DB/PDODBIngestor.php
> +    public function setLogger(\Psr\Log\LoggerInterface $logger)
Alrighty, so first off I agree about the TODOs, I should have caught that there was one added, sorry 'bout that. Here's the context for this particular class, It didn't actually fully implement the `Ingestor` interface as it did not provide an implementation for `setLogger`. Actually, now that I look at it, it doesn't actually have a `logger` member variable at all and all of it's "logging" is done w/ `print` and `echo` statements. 

So I could fix this up a couple of different ways, which would be your preference? 

- I could just remove the function. 
- I could add actual logging to the class by replacing all the `print` / `echo` w/ calls to the logger. 
- Something else entirely?

2020-10-30 14:14 UTC, jpwhite4 commented on classes/DB/PDODBIngestor.php
> +    public function setLogger(\Psr\Log\LoggerInterface $logger)
I suggest that in a separate pull request we 'git rm' this file since it is not used. Then it will not even be here in this pull request and we need not worry about it.

2020-10-30 14:15 UTC, ryanrath commented on classes/DB/PDODBIngestor.php
> +    public function setLogger(\Psr\Log\LoggerInterface $logger)
I like it! I'll get that PR up post haste.

2020-10-30 14:50 UTC, jpwhite4 commented on composer.json
> +        "ext-pdo": "*",
Remove for this pull request - we can add in later

2020-10-30 14:52 UTC, jpwhite4 commented on tests/component/lib/ETL/IngestorTest.php
> +        if ($result['exit_status'] !== 0) {
Is debug code?

2020-10-30 14:52 UTC, jpwhite4 commented on tests/component/lib/ETL/IngestorTest.php
> +        if ($result['exit_status'] !== 0) {
Debug?

2020-10-30 15:00 UTC, jpwhite4 commented on libraries/security.php
> +    if (session_status() !== PHP_SESSION_ACTIVE) {
double check this change

2020-10-30 15:17 UTC, jpwhite4 commented on classes/CCR/Loggable.php
> +        $logLevel = Log::DEBUG;
The level switched from ERR to DEBUG. Is this correct?

2020-10-30 15:27 UTC, jpwhite4 commented
Issugest that you implement a new MonoLog formatter class that outputs the log records in the identical way that they used to be.

This would include the strtolower(level_name). A cursory glance at the monolog source code suggests that you could also handle the array to string encoding in the formatter class too.

For an example of the strtolower see e.g. https://github.com/Seldaek/monolog/blob/9776fa1d548716490a7d49ffbb608e5c2dda589b/src/Monolog/Formatter/FluentdFormatter.php

2020-10-30 21:58 UTC, jpwhite4 commented
So the database output uses a json encoding: ``` select * from log_table limit 10;
+------+---------------------+------------------+----------+---------------------------------------------------------------------------------+
| id   | logtime             | ident            | priority | message                                                                         |
+------+---------------------+------------------+----------+---------------------------------------------------------------------------------+
|    1 | 2020-08-14 18:49:13 | xdmod-import-csv |        5 | {"message":"xdmod-import-csv start","process_start_time":"2020-08-14 18:49:13"} |
|    2 | 2020-08-14 18:49:13 | xdmod-import-csv |        6 | {"message":"Importing type 'hierarchy'"}                                        |
|    3 | 2020-08-14 18:49:13 | xdmod-import-csv |        6 | {"message":"Starting database transaction"}                                     |
|    4 | 2020-08-14 18:49:13 | xdmod-import-csv |        6 | {"message":"Committing database transaction"}                                   |
|    5 | 2020-08-14 18:49:13 | xdmod-import-csv |        5 | {"message":"xdmod-import-csv end","process_end_time":"2020-08-14 18:49:13"}     |
|    6 | 2020-08-14 18:49:13 | xdmod-import-csv |        5 | {"message":"xdmod-import-csv start","process_start_time":"2020-08-14 18:49:13"} |
|    7 | 2020-08-14 18:49:13 | xdmod-import-csv |        6 | {"message":"Importing type 'group-to-hierarchy'"}                               |
|    8 | 2020-08-14 18:49:13 | xdmod-import-csv |        6 | {"message":"Starting database transaction"}                                     |
|    9 | 2020-08-14 18:49:13 | xdmod-import-csv |        6 | {"message":"Committing database transaction"}                                   |
|   10 | 2020-08-14 18:49:13 | xdmod-import-csv |        5 | {"message":"xdmod-import-csv end","process_end_time":"2020-08-14 18:49:13"}     |
+------+---------------------+------------------+----------+---------------------------------------------------------------------------------+
```

So you are going to have to come up with a way of making it use the json encoding with the DB handler and the CCRLine-style encoding with the Console handler.

One option could be to always serialize to json in the CCR::Logger::extractMessage() function and then have the CCRLineFormatter do a speculative json_decode() and then run the  `$parts[] = '(' . implode(', ', $nonMessageParts) . ')';`.

2020-12-02 16:35 UTC, ryanrath commented on classes/DB/PDODBIngestor.php
> +    public function setLogger(\Psr\Log\LoggerInterface $logger)
This was taken care of in: https://github.com/ubccr/xdmod/pull/1462

2020-12-02 16:37 UTC, ryanrath commented on classes/CCR/Loggable.php
> +        $logLevel = Log::DEBUG;
This is swapped back to `Log::ERR` in the latest version of the code.

2020-12-02 17:04 UTC, jpwhite4 commented on classes/DB/ArrayIngestor.php
> +use CCR\Log;
I don't think you need this use statement since CCR\Log is not present in the file?

2020-12-02 18:20 UTC, ryanrath commented on classes/DB/ArrayIngestor.php
> +use CCR\Log;
I believe this is used on line 40 at the end of the `__construct` function.

2020-12-02 20:36 UTC, ryanrath commented on composer.json
> +        "ext-pdo": "*",
Just confirming that the `ext-*` entries have been removed from composer.json

2020-12-02 20:37 UTC, ryanrath commented on libraries/security.php
> +    if (session_status() !== PHP_SESSION_ACTIVE) {
Yup, this was removed as it was meant to be in the Centos8 branch.

2020-12-03 18:36 UTC, jpwhite4 requested changes
The output format for the database logging is still incorrect:

![image](https://user-images.githubusercontent.com/5342179/101072795-8c35ac80-356c-11eb-9309-e3c404cdb31c.png)

2020-12-03 18:41 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +            ':message' => $record['formatted']
You don't want to output record['formatted'] as the message.

2020-12-03 18:42 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +            ':message' => $record['formatted']
you probably want record['message'] but I have not verified this in the actual code

2020-12-03 19:27 UTC, ryanrath commented on classes/CCR/CCRDBHandler.php
> +            ':message' => $record['formatted']
Great catch, thanks! Yeah, I believe this was left over from moving the formatting around to different places within the code. I tested locally by spinning up a local docker w/ an upgrade. Ran xdmod-ingestor to generate some log messages and confirmed that they were **not** displayed correctly in the interface. Updated the field to `message` and repeated the docker upgrade test and confirmed that the log messages were correctly displayed. 

One thing I did note is that testing the `upgrade` path did not generate any log records, which in turn meant that when I clicked on the `Log Data` tab all that was displayed was a blank Tab Panel, as opposed to displaying the log interface, just without data, or an informational message indicating that things were working, just that there was no data to display.

2020-12-03 19:51 UTC, ryanrath commented on classes/CCR/CCRDBHandler.php
> +            ':message' => $record['formatted']
Also, I've updated `CCRDBHandlerTest` so that it: 
  - Is constructing it's logger the same way that the rest of the code does. 
  - Actually inspects the format of the generated log records to make sure that we don't run into this again.

2020-12-03 20:46 UTC, jpwhite4 commented on classes/CCR/Log.php
> +                    sprintf(
Is this sprintf correct here? Don't you want to send an array in so that it can be json_encoded properly?

2020-12-03 21:16 UTC, jpwhite4 requested changes

2020-12-03 21:16 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
Is this correct? The priority values in the old system were mapped to the numerical values of the PEAR log constants.
Old code ```
MariaDB [(none)]> SELECT DISTINCT priority FROM mod_logger.log_table;
+----------+
| priority |
+----------+
|        2 |
|        3 |
|        4 |
|        5 |
|        6 |
+----------+
```

this stuff:
```
SELECT DISTINCT priority FROM mod_logger.log_table;
+----------+
| priority |
+----------+
|      200 |
|      250 |
+----------+
2 rows in set (0.03 sec)
```

2020-12-03 21:18 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
Needless to say these values can't change because they are all coupled to the stuff in the dashboard.

2020-12-03 21:31 UTC, jpwhite4 commented on html/internal_dashboard/controllers/log/get_levels.php
> +            array('id' => \CCR\Log::EMERG,   'name' => 'Emergency'),
This is no good because it you change the internal constants for the log levels then you will not be able to access the old log data.

2020-12-03 21:59 UTC, ryanrath commented on classes/CCR/Log.php
> +                    sprintf(
I can change it back, this was added pre being able to handle arrays as messages.

2020-12-03 22:03 UTC, ryanrath commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
Agreed, this wouldn't work for an existing installation. I figure we have a couple of options, let me know if you have a preference or a different idea. ( This applies to the comment for `get_levels.php` too ) 
  - I could setup a mapping table so that we can select records for the same level given two different priority values. 
  - Add a migration sql statement that updates the old pear level values to the new PSR\Log values.
    - **I personally like this one as it's less to manage going forward**

2020-12-03 22:03 UTC, ryanrath commented on html/internal_dashboard/controllers/log/get_levels.php
> +            array('id' => \CCR\Log::EMERG,   'name' => 'Emergency'),
Yup, see https://github.com/ubccr/xdmod/pull/1461#discussion_r535629178

2020-12-03 22:05 UTC, plessbd commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
I would think the SQL statement would be better since like you said less to manage

2020-12-03 22:58 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
Or what about option 3)

don't use `$record['level']` when you insert into the database. Instead insert the numerical value that corresponds to the old one. The 'new' priority levels would never hit the database.

2020-12-03 23:00 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
especially since the numerical values you are using here are actually monolog values and not part of the PSR rfc.

2020-12-03 23:04 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
SELECT * FROM mod_logger.log_level;

2020-12-03 23:10 UTC, plessbd commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
You know what they say about assumption, I thought they were part of the PSR rfc.

Option 3 sounds good then.

2020-12-04 02:11 UTC, jpwhite4 commented on configuration/linker.php
> +    $logger = Log::factory('file', $logConf);
I may well be over thinking this. But are you allowed to use PSR loaded classes in the linker? After all, the linker itself it responsible for loading them.

Do you have a test case (whether manual or automated) that gets to this place in the code?

2020-12-04 02:37 UTC, ryanrath commented
@jpwhite4 @plessbd The latest commits implement the code levels from https://tools.ietf.org/html/rfc5424 . I also fixed a problem I had missed earlier that had console logs with duplicated info: 

- 2020-12-04 02:12:47 xdmod-import-csv [notice] 2020-12-04 02:12:47 xdmod-import-csv [notice] xdmod-import-csv start (process_start_time: 2020-12-04 02:30:47)

as oppossed to:
- 2020-12-04 02:12:47 xdmod-import-csv [notice] xdmod-import-csv start (process_start_time: 2020-12-04 02:30:47)

2020-12-04 02:44 UTC, ryanrath commented on configuration/linker.php
> +    $logger = Log::factory('file', $logConf);
Soooo, I wrote a test file located @ `/usr/share/xdmod/test.php` with the contents: 
```<?php

require_once 'configuration/linker.php';

$log = \CCR\Log::factory('testing123', array('db' => false, 'file' => false, 'email' => false));
$log->error('test');

throw new Exception('Testing Exception');
```

And here's what that produced: 

```
[root@baea16a23b9a xdmod]# php test.php
2020-12-04 02:12:03 testing123 [error] test
PHP Fatal error:  Uncaught exception 'Psr\Log\InvalidArgumentException' with message 'Level "3" is not defined, use one of: 100, 200, 250, 300, 400, 500, 550, 600' in /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php:516
Stack trace:
#0 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(298): Monolog\Logger::getLevelName(3)
#1 /usr/share/xdmod/classes/CCR/Logger.php(30): Monolog\Logger->addRecord(3, '{"message":"{\"...', Array)
#2 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(614): CCR\Logger->addRecord(3, '{"message":"Exc...', Array)
#3 /usr/share/xdmod/classes/CCR/Logger.php(22): Monolog\Logger->log(3, '{"message":"Exc...', Array)
#4 /usr/share/xdmod/configuration/linker.php(133): CCR\Logger->log(3, 'Exception Code:...')
#5 /usr/share/xdmod/configuration/linker.php(179): handle_uncaught_exception(Object(Exception))
#6 [internal function]: global_uncaught_exception_handler(Object(Exception))
#7 {main}
  thrown in /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php on line 516
2020-12-04 02:12:03 testing123 [critical] Uncaught exception 'Psr\Log\InvalidArgumentException' with message 'Level "3" is not defined, use one of: 100, 200, 250, 300, 400, 500, 550, 600' in /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php:516 Stack trace: #0 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(298): Monolog\Logger::getLevelName(3) #1 /usr/share/xdmod/classes/CCR/Logger.php(30): Monolog\Logger->addRecord(3, '{"message":"{\"...', Array) #2 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(614): CCR\Logger->addRecord(3, '{"message":"Exc...', Array) #3 /usr/share/xdmod/classes/CCR/Logger.php(22): Monolog\Logger->log(3, '{"message":"Exc...', Array) #4 /usr/share/xdmod/configuration/linker.php(133): CCR\Logger->log(3, 'Exception Code:...') #5 /usr/share/xdmod/configuration/linker.php(179): handle_uncaught_exception(Object(Exception)) #6 [internal function]: global_uncaught_exception_handler(Object(Exception)) #7 {main}   thrown (file: /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php, line: 516, type: 1)
2020-12-04 02:12:03 file [critical] Uncaught exception 'Psr\Log\InvalidArgumentException' with message 'Level "3" is not defined, use one of: 100, 200, 250, 300, 400, 500, 550, 600' in /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php:516 Stack trace: #0 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(298): Monolog\Logger::getLevelName(3) #1 /usr/share/xdmod/classes/CCR/Logger.php(30): Monolog\Logger->addRecord(3, '{"message":"{\"...', Array) #2 /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php(614): CCR\Logger->addRecord(3, '{"message":"Exc...', Array) #3 /usr/share/xdmod/classes/CCR/Logger.php(22): Monolog\Logger->log(3, '{"message":"Exc...', Array) #4 /usr/share/xdmod/configuration/linker.php(133): CCR\Logger->log(3, 'Exception Code:...') #5 /usr/share/xdmod/configuration/linker.php(179): handle_uncaught_exception(Object(Exception)) #6 [internal function]: global_uncaught_exception_handler(Object(Exception)) #7 {main}   thrown (file: /usr/share/xdmod/vendor/monolog/monolog/src/Monolog/Logger.php, line: 516, type: 1)
```

If I'm interpreting that correctly, which it's entirely possible that I'm not ( it is kinda late ), then it looks like it's ok to utilize the PSR loaded class, there's just a problem w/ how I implemented the log levels for RFC5424.

2020-12-04 03:45 UTC, plessbd commented
Ahh utc....

Timezones strike again...

2020-12-04 14:13 UTC, jpwhite4 commented on classes/CCR/Log.php
> +    public static function convertLevel($monologLevel)
Please can you change this function name to better describe what it is doing. Something like monologLevelToCCRLevel() or monoLevelToRfc().....

2020-12-04 14:17 UTC, jpwhite4 commented on classes/CCR/Log.php
> +    public static function convertLevel($monologLevel)
Also it is not clear why this function is in the class. The only place it is used is in the database handler. Wouldn't it make more sense to be a private member of that? Are there other places where we need to do this conversion?

2020-12-04 14:18 UTC, jpwhite4 commented on classes/CCR/Log.php
> +    public static function convertLevel($monologLevel)
Also is is safe to throw and exception here? This code may be called in the top level exception handler.

2020-12-04 17:20 UTC, ryanrath commented on classes/CCR/Log.php
> +    public static function convertLevel($monologLevel)
- re: function name - lol, I guess great minds think a like because I've included this change in the latest commits.
- Good point: I included it in this class as I see `Log` as the central point of control for anything logging in XDMoD. It also seemed a general enough function that it might be needed elsewhere so I lumped it in w/ Log. I've also added a second conversion function `convertToMonologLevel` as I found that if you provide a log level that is less than Monolog's DEBUG, which is the case for all of the PSR log levels, then you'll just always be debugging. Another mark in the "Have these functions together in this class" column, at least in my head. 
- Good question... I'll try and write up a quick test case locally to see what happens / how it's handled.

2020-12-04 18:15 UTC, ryanrath commented on classes/CCR/Log.php
> +    public static function convertLevel($monologLevel)
@jpwhite4 By top level exception handler do you mean like in `linker.php::handle_uncaught_exception` ?

2020-12-04 18:27 UTC, ryanrath commented on classes/CCR/Log.php
> +    public static function convertLevel($monologLevel)
So if you were talking about `handle_uncaught_exception` in `linker.php` then here's the quick test I wrote (`test.php`): 

```php
<?php

require_once 'configuration/linker.php';

$config = array(
    'db' => false,
    'mail' => false,
    'file' => false,
    'consoleLogLevel' => -1
);

$logger = \CCR\Log::factory('testing', $config);

$logger->notice("Notice Me Senpai!");
```

Which generated the following output:
```
[root@40866e5dcf2f xdmod]# php test.php
2020-12-04 06:12:15 file [error] {"message":"Exception Code: 0"}
2020-12-04 06:12:15 file [error] {"message":"Message: Unknown Log Level"}
{"success":false,"count":0,"total":0,"totalCount":0,"results":[],"data":[],"message":"Unknown Log Level","code":0}
```

I also tried updating the logger config in `handle_uncaught_exception` to: 
```php
    $logConf = array(
        'mode' => 0644,
        'file' => $logfile,
        'consoleLogLevel' => -1
    );
```

Which generated the following:
```
[root@40866e5dcf2f xdmod]# php test.php
PHP Fatal error:  Uncaught exception 'Exception' with message 'Unknown Log Level' in /usr/share/xdmod/classes/CCR/Log.php:390
Stack trace:
#0 /usr/share/xdmod/classes/CCR/Log.php(201): CCR\Log::convertToMonologLevel(-1)
#1 [internal function]: CCR\Log::getConsoleHandler('file', Array)
#2 /usr/share/xdmod/classes/CCR/Log.php(170): call_user_func(Array, 'file', Array)
#3 /usr/share/xdmod/classes/CCR/Log.php(91): CCR\Log::getLogger('file', Array)
#4 /usr/share/xdmod/configuration/linker.php(132): CCR\Log::factory('file', Array)
#5 /usr/share/xdmod/configuration/linker.php(180): handle_uncaught_exception(Object(Exception))
#6 [internal function]: global_uncaught_exception_handler(Object(Exception))
#7 {main}
  thrown in /usr/share/xdmod/classes/CCR/Log.php on line 390
[root@40866e5dcf2f xdmod]#
```

So in thinking about it, we could provide a default level instead of throwing an exception. But then it could be possible that this "fails silently" when values we don't expect are provided as opposed to bringing attention to it. 

Thoughts?

2020-12-09 16:11 UTC, ryanrath commented on classes/CCR/CCRDBHandler.php
> +            ':priority' => $record['level'],
@jpwhite4 I've gone with your suggestion of option 3. It's implemented in the latest version of the code.

2020-12-22 18:59 UTC, jpwhite4 requested changes

2020-12-22 18:59 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +        if ($results <= 0) {
The execute function returns true or false according to the php docs.

2020-12-22 18:59 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +        if ($results <= 0) {
https://www.php.net/manual/en/pdostatement.execute.php

2020-12-22 18:59 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +        // We don't check the number of rows deleted as while it most often will be 1, it is also expected to be zero
Surely the reason why you don't check the number of rows deleted is because it doesn't matter. It could be any number.

2020-12-22 18:59 UTC, jpwhite4 commented on classes/CCR/Log.php
> +    public static function convertToCCRLevel($monologLevel)
Given that this function is called many many time.Surely it is much more efficient to not do an array flip on every call. Why not store the flipped array as a variable?

2020-12-22 18:59 UTC, jpwhite4 commented on configuration/linker.php
> +    $logger = Log::factory('file', $logConf);
What were the contents of exception.log?

2020-12-22 18:59 UTC, jpwhite4 commented on tests/component/lib/ETL/BaseEtlTest.php
> +        $action = aAction::factory($etlConfig, $actionName);
Why the change here?

2020-12-22 18:59 UTC, jpwhite4 commented on tests/component/lib/ETL/IngestorTest.php
> +        $this->assertGreaterThanOrEqual(1, $numWarnings, 'Expected number of SQL warnings');
Why did the number of warnings change?

2020-12-22 18:59 UTC, jpwhite4 commented on tests/unit/lib/OpenXdmod/Tests/HostListParserTest.php
> +                    'consoleLogLevel' => \CCR\Log::DEBUG,
Why the API change here?

2020-12-22 19:33 UTC, ryanrath commented on classes/CCR/CCRDBHandler.php
> +        if ($results <= 0) {
True, but `$this-db` is an `iDatabase` /  `PDODB` which returns `$stmt->rowCount()` https://github.com/ubccr/xdmod/blob/4b05b1cddc7912541da65cdb96e25b9883d1554b/classes/CCR/DB/PDODB.php#L190

2020-12-22 19:35 UTC, ryanrath commented on classes/CCR/CCRDBHandler.php
> +        // We don't check the number of rows deleted as while it most often will be 1, it is also expected to be zero
pretty much, I'll update the comment.

2020-12-22 19:38 UTC, ryanrath commented on classes/CCR/Log.php
> +    public static function convertToCCRLevel($monologLevel)
sure, I'll add the variable & update the function.

2020-12-22 20:08 UTC, ryanrath commented on tests/component/lib/ETL/IngestorTest.php
> +        $this->assertGreaterThanOrEqual(1, $numWarnings, 'Expected number of SQL warnings');
That's actually a good question. I believe this changed while I was testing and the test never complained after changing things back because 4 >= 1. I'll make sure this is set back to the original 4.

2020-12-22 20:39 UTC, jpwhite4 commented on classes/CCR/CCRDBHandler.php
> +        if ($results <= 0) {
But that function throws an exception if the pdo::execute fails so there is no way that you can get to line 102 here.

2020-12-22 20:39 UTC, ryanrath commented on tests/unit/lib/OpenXdmod/Tests/HostListParserTest.php
> +                    'consoleLogLevel' => \CCR\Log::DEBUG,
So this is an interesting one, initially this was just another artifact of earlier testing. I had wanted to be explicit that this was to just be a console logger. Changing the log options back to the original ( or equivalent to the original w/ out the db, mail, or file => false ) doesn't cause any problems. Which got me to thinking about whether or not this code was actually ever used. I went about trying to trigger it but ran into problems since there was no `LOG_DEBUG` in `$GLOBALS`. Nor was it immediately apparent how to set a value in GLOBALS. So, do we know why they used GLOBALS here?  I did a git blame but this code has been in place since we initially imported it into git. If we want to use env variables instead of GLOBALS then I tried this: 

```php
        $logDebug = getenv('LOG_DEBUG');
        if ($logDebug) {
            $logger = \CCR\Log::factory(
                'hostlistparser_test',
                array(
                    'consoleLogLevel' => \CCR\Log::DEBUG
                )
            );
            $this->parser->setLogger($logger);
        }
```

which actually worked when I specified `LOG_DEBUG=1`. 

Thoughts?

2020-12-22 20:41 UTC, jpwhite4 commented on classes/CCR/Log.php
> +    public static function convertLevel($monologLevel)
What were the contents of the execption.log file when you did your test?

2020-12-22 20:48 UTC, ryanrath commented on classes/CCR/CCRDBHandler.php
> +        if ($results <= 0) {
True, the insert statement would have to somehow succeed but not affect any rows. Which for a straight `INSERT ... VALUES` statement I don't think is possible. It might be different if it was a `INSERT ... SELECT ` but it's not, so I'll go ahead and remove the `if` statement after this `execute`.

2020-12-22 20:56 UTC, ryanrath commented on classes/CCR/Log.php
> +    public static function convertLevel($monologLevel)
With a valid logger in `linker.php`  it was: 

```
[root@2da6bfc3594c xdmod]# cat /var/log/xdmod/exceptions.log
2020-12-22 08:12:52 file [error] {"message":"Exception Code: 0"}
2020-12-22 08:12:52 file [error] {"message":"Message: Unknown Log Level"}
```

With the logger config updated w/ the invalid log level: 

```php
    $logConf = array(
        'mode' => 0644,
        'file' => $logfile,
        'consoleLogLevel' => -1
    );
```

`exceptions.log` is empty: 
```
[root@2da6bfc3594c xdmod]# php test.php
PHP Fatal error:  Uncaught exception 'Exception' with message 'Unknown Log Level' in /usr/share/xdmod/classes/CCR/Log.php:395
Stack trace:
#0 /usr/share/xdmod/classes/CCR/Log.php(223): CCR\Log::convertToMonologLevel(-1)
#1 [internal function]: CCR\Log::getConsoleHandler('file', Array)
#2 /usr/share/xdmod/classes/CCR/Log.php(192): call_user_func(Array, 'file', Array)
#3 /usr/share/xdmod/classes/CCR/Log.php(113): CCR\Log::getLogger('file', Array)
#4 /usr/share/xdmod/configuration/linker.php(132): CCR\Log::factory('file', Array)
#5 /usr/share/xdmod/configuration/linker.php(180): handle_uncaught_exception(Object(Exception))
#6 [internal function]: global_uncaught_exception_handler(Object(Exception))
#7 {main}
  thrown in /usr/share/xdmod/classes/CCR/Log.php on line 395
[root@2da6bfc3594c xdmod]# ls -alh /var/log/xdmod/
total 20K
drwxrwx--- 1 apache xdmod 4.0K Dec 22 19:48 .
drwxr-xr-x 1 root   root  4.0K Aug 14 18:49 ..
-rw-r--r-- 1 root   root   648 Dec 22 19:50 apache-error.log
-rw-rw---- 1 apache xdmod    0 Dec 22 19:50 exceptions.log
-rw-rw---- 1 apache xdmod    0 Dec 22 19:50 query.log
```

2020-12-22 21:07 UTC, jpwhite4 commented
Test code:```
<?php

require_once '/usr/share/xdmod/configuration/linker.php';

throw new Exception("This message should be written to /var/log/xdmod/exceptions.log");
```

original code output:
```
Dec 22 21:05:36 exception [error] Exception Code: 0
Dec 22 21:05:36 exception [error] Message: This message should be written to /var/log/xdmod/exceptions.log
Dec 22 21:05:36 exception [info] Origin: /tmp/test.php (line 5)
Dec 22 21:05:36 exception [info] Trace:
#0 {main}
-------------------------------------------------------
```

current output:
```
2020-12-22 09:12:23 file [error] {"message":"Exception Code: 0"}
2020-12-22 09:12:23 file [error] {"message":"Message: This message should be written to \/usr\/share\/xdmod\/logs\/exception.log"}
{"success":false,"count":0,"total":0,"totalCount":0,"results":[],"data":[],"message":"This message should be written to \/usr\/share\/xdmod\/logs\/exception.log","code":0}
```

2020-12-23 19:46 UTC, ryanrath commented on tests/unit/lib/OpenXdmod/Tests/HostListParserTest.php
> +                    'consoleLogLevel' => \CCR\Log::DEBUG,
@jpwhite4 So I was playing around with this some more and I got the `GLOBALS` to work with some combination of the following in either `constants.php` or `HostListParserTest`

```php
global $LOG_DEBUG;
$LOG_DEBUG=true;
```

So my question would be do we want to continue using `$GLOBALS` or do we want to use env variables?

2020-12-23 19:53 UTC, ryanrath commented
@jpwhte4 Alrighty, so in regards to: https://github.com/ubccr/xdmod/pull/1461#issuecomment-749776407 

Here are the issues I found: 

  1. Log messages presented in JSON
  2. Missing `INFO` level messages
  3. Additional JSON encoded data is displayed currently where none was previously.

Here's what I've been able to resolve so far: 

  1. Adjusted the way the messages were being provided to the logger by wrapping them in an array `array( 'message' => <original log message> )`. This ensured that the messages were no longer displayed in JSON. 
  2.  Added a `'consoleLogLevel' => \CCR\Log::INFO` property to the log conf. This ensures we see the `INFO` level log messages that were previously absent. 
  3. Modified the `global_uncaught_exception_handler` so that it only `echo $exceptionOutput['content'];` if it's operating within a server context. 
  
**Old**
```php
function global_uncaught_exception_handler($exception)
{
    // Perform logging and output building for the exception.
    $exceptionOutput = handle_uncaught_exception($exception);

    // If running in a server context...
    if ($exceptionOutput['isServerContext'] && !headers_sent()) {
        // Set the exception's headers (if any).
        foreach ($exceptionOutput['headers'] as $headerKey => $headerValue) {
            header("$headerKey: $headerValue");
        }

        // Set the status code header.
        $httpCode = $exceptionOutput['httpCode'];
        header("{$_SERVER['SERVER_PROTOCOL']} $httpCode ".HttpCodeMessages::$messages[$httpCode]);
    }

    // Print the exception's content.
    echo $exceptionOutput['content'];
} // global_uncaught_exception_handler
```

**New**

```php
function global_uncaught_exception_handler($exception)
{
   // Perform logging and output building for the exception.
    $exceptionOutput = handle_uncaught_exception($exception);

   // If running in a server context...
    if ($exceptionOutput['isServerContext']) {
        if (!headers_sent()) {
            // Set the exception's headers (if any).
            foreach ($exceptionOutput['headers'] as $headerKey => $headerValue) {
                header("$headerKey: $headerValue");
            }

            // Set the status code header.
            $httpCode = $exceptionOutput['httpCode'];
            header("{$_SERVER['SERVER_PROTOCOL']} $httpCode ".HttpCodeMessages::$messages[$httpCode]);
        }

        echo $exceptionOutput['content'];
    }
} // global_uncaught_exception_handler
```

Output w/ the changes I made:
```
[root@9aad8718f5bd xdmod]# php /usr/share/xdmod/test.php
2020-12-23 07:12:10 file [error] Exception Code: 0
2020-12-23 07:12:10 file [error] Message: This message should be written to /var/log/xdmod/exceptions.log
2020-12-23 07:12:10 file [info] Origin: /usr/share/xdmod/test.php (line 5)
2020-12-23 07:12:10 file [info] Trace:
#0 {main}
-------------------------------------------------------
[root@9aad8718f5bd xdmod]#
```

2021-01-04 20:38 UTC, jpwhite4 commented
The output is still changed from the old code:
old:
```
2020-12-23 15:05:15 [notice] Start processing section 'xdmod.xdw-aggregate-storage'
```

new:
```
2021-01-04 08:01:34 xdmod-ingestor [notice] Start processing section 'xdmod.xdw-ingest-storage'
```

2021-01-04 21:13 UTC, ryanrath commented
@jpwhite4 re: https://github.com/ubccr/xdmod/pull/1461#issuecomment-754205216 Do we want to exclude the information about what script / logger is generating the log message? It's not a hard change, but it strikes me that this might be useful information to have.

@jpwhite4 Ok, just to double check, did https://github.com/ubccr/xdmod/pull/1461#issuecomment-750449657 address your previous concern about the output from unhandled exceptions?

2021-01-04 22:20 UTC, jpwhite4 commented
The file and console log format output is incorrect. Also the datestamp is also wrong:
old code:
```
2021-01-04 22:06:36 [debug] DataWarehouse\Query\AggregateQuery(Jobs, groupbys=(jobsize), statistics=(total_cpu_hours)) getCountQueryString()
```

new code:
```
2021-01-04 10:01:07 datawarehouse.query [debug] DataWarehouse\Query\AggregateQuery(Jobs, groupbys=(jobsize), statistics=(total_cpu_hours)) getCountQueryString()
```

the two problems are (1) the new code puts the string 'datawarehouse.query' into the output. and (2) the hours, minutss and seconds in the timestamp are wrong.

2021-01-04 22:21 UTC, jpwhite4 commented
> @jpwhite4 re: [#1461 (comment)](https://github.com/ubccr/xdmod/pull/1461#issuecomment-754205216) Do we want to exclude the information about what script / logger is generating the log message? It's not a hard change, but it strikes me that this might be useful information to have.
> 
> @jpwhite4 Ok, just to double check, did [#1461 (comment)](https://github.com/ubccr/xdmod/pull/1461#issuecomment-750449657) address your previous concern about the output from unhandled exceptions?

This pull request should not change the log output.

If you want to change the log output format then do it in a different pull request. If you do want to change the log output format then you will have to do a risk analysis to check whether you will break some other processes / components. One example of breakage is anything that currently parses the log output

2021-01-04 22:25 UTC, jpwhite4 commented
Your problem is in:
```php
const TIME_FORMAT = 'Y-m-d h:m:s';
```
lowercase h is hours in 12 hour format and lower case m is months.

2021-01-05 19:34 UTC, ryanrath commented
@jpwhite4 Thanks for this catch: https://github.com/ubccr/xdmod/pull/1461#issuecomment-754260331 The latest commit: https://github.com/ubccr/xdmod/pull/1461/commits/bceaf7aef0b6e10946ae94d3f7ce7190ae6cef07 contains the changes to resolve those format discrepancies.

2021-01-06 17:12 UTC, jpwhite4 commented
The output from the test.php is still different:
Original code:
```
php test.php
{"success":false,"count":0,"total":0,"totalCount":0,"results":[],"data":[],"message":"This message should be written to \/var\/log\/xdmod\/exceptions.log","code":0}

[root@ea97b64d1520 xdmod]# cat /var/log/xdmod/exceptions.log
Jan 06 17:10:11 exception [error] Exception Code: 0
Jan 06 17:10:11 exception [error] Message: This message should be written to /var/log/xdmod/exceptions.log
Jan 06 17:10:11 exception [info] Origin: /usr/share/xdmod/test.php (line 5)
Jan 06 17:10:11 exception [info] Trace:
#0 {main}
-------------------------------------------------------
```

current build:
```
php test.php
2021-01-06 17:12:11 [error] Exception Code: 0
2021-01-06 17:12:11 [error] Message: This message should be written to /var/log/xdmod/exceptions.log
2021-01-06 17:12:11 [info] Origin: /var/log/xdmod/test.php (line 5)
2021-01-06 17:12:11 [info] Trace:
#0 {main}
-------------------------------------------------------
[root@49402b35fe4a xdmod]# cat /var/log/xdmod/exceptions.log
2021-01-06 17:09:01 [error] Exception Code: 0
2021-01-06 17:09:01 [error] Message: This message should be written to /var/log/xdmod/exceptions.log
```

2021-01-06 18:11 UTC, jpwhite4 commented on configuration/linker.php
> +    if ($exceptionOutput['isServerContext']) {
Please explain why this code changed.

2021-01-06 18:28 UTC, jpwhite4 commented on configuration/linker.php
> +        'consoleLogLevel' => CCR\Log::INFO
The old code created a file logger here. But this change seems to create a file logger and a console logger and set the console logger to log at info. I don't think this is the correct thing to do since it will likely break the frontend.

2021-01-06 18:32 UTC, ryanrath commented on configuration/linker.php
> +    if ($exceptionOutput['isServerContext']) {
I implemented this change to address this comment: https://github.com/ubccr/xdmod/pull/1461#issuecomment-749776407

Specifically it was so that this line was not displayed: 
```
2020-12-22 09:12:23 file [error] {"message":"Message: This message should be written to \/usr\/share\/xdmod\/logs\/exception.log"}
{"success":false,"count":0,"total":0,"totalCount":0,"results":[],"data":[],"message":"This message should be written to \/usr\/share\/xdmod\/logs\/exception.log","code":0}
```

2021-01-06 18:43 UTC, jpwhite4 commented on configuration/linker.php
> +        'consoleLogLevel' => CCR\Log::INFO
Also this code is sending emails too. Which the old code did not.

2021-01-08 15:29 UTC, ryanrath commented on tests/component/lib/ETL/BaseEtlTest.php
> +        $action = aAction::factory($etlConfig, $actionName);
No good reason. I believe my thought process was something along the lines of `self::$logger` is never instantiated ( via `self::createLogger` ) so why provide it? Which should have been to obviously facilitate the debugging of tests. I've re-added it in https://github.com/ubccr/xdmod/pull/1461/commits/f8fe8c39c407cd242b2b6f21d3fc35dd6d20b127

2021-01-08 16:24 UTC, ryanrath commented on configuration/linker.php
> +        'consoleLogLevel' => CCR\Log::INFO
Yup, per our earlier convo I updated the logger config here: https://github.com/ubccr/xdmod/pull/1461/commits/29de561878156e3a2b46bba55f52246fbac0a124

2021-01-14 15:28 UTC, eiffel777 approved these changes

2021-01-19 21:30 UTC, jpwhite4 commented on tests/unit/lib/OpenXdmod/Tests/HostListParserTest.php
> +                    'consoleLogLevel' => \CCR\Log::DEBUG,
The code in question was added in:

commit e970d8f70c60c40dcdcf0388177741ca013fad04
Author: Jeffrey T. Palmer <jtpalmer@buffalo.edu>
Date:   Tue Sep 15 10:03:49 2015 -0400

    Add compressed host list parser

I assume that it was an artifact of development, but its probably worth checking with Jeff just in case.

2021-01-19 22:03 UTC, jpwhite4 approved these changes

2021-01-19 22:03 UTC, jpwhite4 commented
Please can you squash and merge when you merge since there are lots of commits.

2021-01-20 16:28 UTC, ryanrath commented
@jpwhite4 Absolutely, thanks!

2021-01-20 16:29 UTC, merged