Make cloud realm compatible with ONLY_FULL_GROUP_BY
ubccr/xdmod pull request #1480
Opened 2021-01-07 17:42 UTC by eiffel777

This changes makes changes so the cloud realm is compatible with MySQL when ONLY_FULL_GROUP_BY mode is enabled.

For the cloud aggregation the entails adding columns to the group by for the aggregation query. For the cloud resource specifications aggregation it revealed a bug when summing the core time for a time period because of a misplaced parenthesis. Re-aggregation of the cloud resource specifications is necessary because of this.

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2021-01-14 01:44 UTC, jpwhite4 commented on configuration/etl/etl_action_defs.d/cloud_common/cloud_resource_specs_aggregation.json
> +                "core_time_available": "COALESCE(SUM(${wallduration} * crs.vcpus), 0)"
Is this correct? Shouldn't the crs.vpus be in the statistic?

2021-02-22 17:14 UTC, eiffel777 commented
@jpwhite4 @ryanrath This is updated and ready to be reviewed

2021-02-23 21:32 UTC, jpwhite4 requested changes

2021-02-23 21:32 UTC, jpwhite4 commented on classes/OpenXdmod/Migration/Version900To950/DatabaseMigration.php
> +namespace OpenXdmod\Migration\Version851To900;
Wrong namespace - also this change conflicts with the other cloud resources pull request.

2021-02-24 15:26 UTC, ryanrath reviewed
I'll admit this is nit-picky but I'd prefer to have the `use` statements that aren't being used removed. Which I believe would just leave the `CCR\DB` and `ETL\Utilities` statements.

2021-02-24 16:04 UTC, jpwhite4 approved these changes

2021-02-24 16:22 UTC, merged