XDMoD - PHP 7.2, MariaDB 10.3 Update
ubccr/xdmod pull request #1486
Opened 2021-01-22 15:17 UTC by ryanrath

**NOTE: This PR isn't ready for review yet. At the very least I need to push the docker image I'm using before any of the automated tests will pass. I'll detail the current state of tests passing below.**

## Description
This is a first go at updating XDMoD to be able to run on Centos8 w/ PHP 7.2 & MariaDB 10.3.

## Motivation and Context
We have received a number of requests for XDMoD to be run on Centos8 ( prior to Red Hat killing it ). The changes included in this PR are meant to allow us to successfully deploy XDMoD on Centos8. 

## Tests performed
- [X] Unit Tests: Passing
- [X] Component Tests: Passing
- [X] Integration Tests: Passing
- [ ] Regression Tests: The only tests failing are the hashes for `UsageChartsTest::testChartSettings`
- [X] UI Tests: Passing

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2021-01-22 22:44 UTC, jpwhite4 commented on classes/ETL/DbModel/Column.php
> +                 ( "datetime" === $this->type && in_array(strtolower($this->default), $currentTimestampAliases) ) ||
Please can you explain the reason for this change. Did the underlying type names change in the database?

2021-01-23 00:04 UTC, ryanrath commented on classes/ETL/DbModel/Column.php
> +                 ( "datetime" === $this->type && in_array(strtolower($this->default), $currentTimestampAliases) ) ||
@jpwhite4 Sure, It was due to the default values for `datetime` columns being wrapped in single quotes which was causing problems w/ the move to MariaDB 10.3, this new version of MariaDB isn't having any the shenanigans we got away with in earlier versions. Previously when a default value of `'NOW()'` was encountered it would be interpreted as a function call to `NOW`, in MariaDB 10.3 it sees those single quotes and regardless of what's in them treats it as a string literal.

2021-05-06 15:43 UTC, eiffel777 commented on classes/DataWarehouse/Data/TimeseriesDataset.php
> +        $groupInstance = reset($groupBys);
This seems to be just taking one statement and making it into two. Is there a functional reason for this or is it just a style thing? There are a few other spots where this same kind of change happens too. Is it the same reason for all of them?

2021-05-06 17:28 UTC, ryanrath commented on classes/DataWarehouse/Data/TimeseriesDataset.php
> +        $groupInstance = reset($groupBys);
It's just a PHP 7 thing. A lot of the changes in this PR are essentially PHP being a lot more strict about things.

2021-07-27 12:34 UTC, jtpalmer commented on open_xdmod/modules/xdmod/xdmod.spec.in
> +%{?el7:Requires: php-pear-MDB2 php-pear-MDB2-Driver-mysql php-pecl-apcu}
```suggestion
%{?el7:Requires: php-pecl-apcu}
```

2021-07-27 12:38 UTC, jtpalmer commented on open_xdmod/modules/xdmod/xdmod.spec.in
> +%{?el8:Requires: php-pecl-apcu}
I checked and CentOS 8 does have a separate package for the PHP JSON functions.

```suggestion
%{?el8:Requires: php-pecl-apcu php-json}
```

2021-07-27 13:46 UTC, ryanrath commented on open_xdmod/modules/xdmod/xdmod.spec.in
> +%{?el8:Requires: php-pecl-apcu}
lol yup, this was actually the cause of one of the problems the Alpha tester ran into. Do you happen to know if `php-gmp` is still required? That was the other package difference I noticed between a straight Centos8 w/ this RPM installed & the Centos8 image I put together for CircleCI.

2021-08-02 14:32 UTC, ryanrath commented on open_xdmod/modules/xdmod/xdmod.spec.in
> +%{?el7:Requires: php-pear-MDB2 php-pear-MDB2-Driver-mysql php-pecl-apcu}
@jtpalmer This should be all set in the latest commit

2021-08-02 14:32 UTC, ryanrath commented on open_xdmod/modules/xdmod/xdmod.spec.in
> +%{?el8:Requires: php-pecl-apcu}
@jtpalmer This should be all set in the latest commit.

2021-08-03 16:00 UTC, jpwhite4 commented on configuration/etl/etl.d/cloud_ingest_resource_specs.json
> +                          "arguments": "-c '.hypervisors[].date += (.ts | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\")) | .hypervisors'"
Please can you provide a big of info about the reason for this change.

2021-08-03 16:02 UTC, jpwhite4 commented on configuration/etl/etl.d/cloud_ingest_resource_specs.json
> +                          "arguments": "-c '.hypervisors[].date += (.ts | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\")) | .hypervisors'"
Also I think the `%m` in between the hours and seconds should actually be a `%M`

2021-08-03 16:02 UTC, jpwhite4 commented on configuration/etl/etl.d/staging.json
> +                            "arguments": "-c '[ .[] | (.dt = (.dt | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\"))) ]'"
`%m` to `%M` in between hours and seconds.

2021-08-03 16:05 UTC, jpwhite4 commented on configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
> +                "type": "bigint(11)",
Please can you provide info about this change too.

2021-08-03 16:07 UTC, jpwhite4 commented on tests/component/lib/ETL/BaseEtlTest.php
> +        $overseerOptions->setActionNames($actionName);
Please can you provide more info about this change

2021-08-03 16:12 UTC, jpwhite4 commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +                    $expectedJson = json_encode(json_decode($expected), JSON_PRETTY_PRINT);
Please provide more info about this change

2021-08-03 16:14 UTC, jpwhite4 commented on classes/ETL/DbModel/Column.php
> +                 ( "datetime" === $this->type && in_array(strtolower($this->default), $currentTimestampAliases) ) ||
So did they remove the ability to set a default value of NOW() to a column?

2021-08-03 16:16 UTC, jpwhite4 commented on classes/ETL/DbModel/Column.php
> +                 ( "datetime" === $this->type && in_array(strtolower($this->default), $currentTimestampAliases) ) ||
The documentation seems to imply that you can use a function as a default:  https://mariadb.com/kb/en/create-table/#default-column-option

2021-08-03 16:23 UTC, jpwhite4 commented on classes/XDUser.php
> +            $update_data['password_last_updated'] = date('Y-m-d H:i:s');
This changes the time source from the database to the webserver. Is this going to cause any race conditions? Why not continue to use NOW() to se the password last updated value?

2021-08-03 16:24 UTC, jpwhite4 commented on configuration/etl/etl.d/cloud_ingest_resource_specs.json
> +                          "arguments": "-c '.hypervisors[].date += (.ts | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\")) | .hypervisors'"
Also is there a potential timezone problem too?

2021-08-03 18:14 UTC, jtpalmer commented on classes/XDUser.php
> +            $update_data['password_last_updated'] = date('Y-m-d H:i:s');
Is this even necessary with this trigger: https://github.com/ubccr/xdmod/blob/xdmod10.0/configuration/etl/etl_tables.d/xdb/users.json#L148

2021-08-03 19:14 UTC, ryanrath commented on configuration/etl/etl.d/cloud_ingest_resource_specs.json
> +                          "arguments": "-c '.hypervisors[].date += (.ts | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\")) | .hypervisors'"
- For context, here's what I have down as the reason for the change: ` MariaDB datetime columns have a default format that cannot be changed that was preventing this data from being ingested. This change formats the incoming data appropriately.` 

- Re: `%M` vs `%m` I was just going off of https://stedolan.github.io/jq/manual/#Dates which had said that `strftime` used the formats from the "typical C Library Documentation". I honestly probably just looked at the examples in the documentation, but I checked here ( and a couple of other places ) https://www.cplusplus.com/reference/ctime/strftime/ and it seems like `%m` is month and `%M` is minutes. 

- There could very well be a timezone problem here. It does say that `strftime` uses GMT while `strfflocaltime` uses whatever the machine is set to. So that seems like a pretty clear win for `strflocaltime`.

2021-08-03 19:19 UTC, ryanrath commented on configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
> +                "type": "bigint(11)",
Yup yup, here's what I have from the commit: `Not sure why this wasn't caught before but the values being inserted into this column included values that were too large for `int`. After speaking with Greg we decided the easiest fix for now would be to update the column type to `bigint`.`

2021-08-03 20:56 UTC, jpwhite4 commented on configuration/etl/etl.d/cloud_ingest_resource_specs.json
> +                          "arguments": "-c '.hypervisors[].date += (.ts | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\")) | .hypervisors'"
What does the original data look like (before being converted with the 'fromdate' function). How does it work in the Centos 7 builds?

2021-08-03 20:57 UTC, jpwhite4 commented on configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
> +                "type": "bigint(11)",
Is this change a bug that is independent of the Centos 7 -> Centos 8 changes? As in : is this a bug in Centos7 too?
 If so then it will be easier to keep track of this in a separate pull request.

2021-08-03 20:58 UTC, jpwhite4 commented on configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
> +                "type": "bigint(11)",
Also does this impact the 9.5 release?

2021-08-03 21:37 UTC, jpwhite4 commented on configuration/etl/etl.d/cloud_ingest_resource_specs.json
> +                          "arguments": "-c '.hypervisors[].date += (.ts | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\")) | .hypervisors'"
I don't think stflocaltime will help. The data in the json files are in UTC and they need to be stored in the database with the correct offset. I'm pretty sure it could be done with the following: 
```
SELECT CONVERT_TZ(STR_TO_DATE("2018-04-18T22:30:02Z", "%Y-%m-%dT%H:%i:%sZ"), "+00:00", "system");
```

where, obviously, the actual date string would come from the file.

2021-08-03 21:42 UTC, jpwhite4 commented on configuration/etl/etl_schemas.d/storage/usage.schema.json
> +            "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}",
Is it ok to change the schema here? Will this break existing stuff? 

Also timezones.

2021-08-03 21:46 UTC, jpwhite4 commented on configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
> +    IF ( @current_instance_type = instance_type AND @prev_start IS NOT NULL, @prev_start - 1, NULL) AS end_time,
Please explain this change: did they really remove the "INTERVAL X SECOND" ability from mariadb?

2021-08-04 11:27 UTC, jtpalmer commented on configuration/etl/etl_schemas.d/storage/usage.schema.json
> +            "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}",
If this is changing, also please update the documentation (https://github.com/ubccr/xdmod/blame/xdmod10.0/docs/storage.md#L41). Also on line 57.

2021-08-04 13:31 UTC, ryanrath commented on classes/ETL/DbModel/Column.php
> +                 ( "datetime" === $this->type && in_array(strtolower($this->default), $currentTimestampAliases) ) ||
You can still use functions as default values it's just that the SQL for a column w/ a function default value has to be:
```sql
`created` datetime NOT NULL DEFAULT NOW() COMMENT 'The date and time at which a thing is created.'
```
and not 
```sql
`created` datetime NOT NULL DEFAULT 'NOW()' COMMENT 'The date and time at which a thing is created.'
```
This change is just updating the way that ETLv2 generates the column creation sql for `datetime` columns.

2021-08-04 13:32 UTC, ryanrath commented on classes/ETL/DbModel/Column.php
> +                 ( "datetime" === $this->type && in_array(strtolower($this->default), $currentTimestampAliases) ) ||
I'm going to go ahead and add a test case to `DbModelTest.php` to cover this case.

2021-08-04 18:53 UTC, ryanrath commented on configuration/etl/etl.d/staging.json
> +                            "arguments": "-c '[ .[] | (.dt = (.dt | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\"))) ]'"
*facepalm* This is probably what you meant w/ the one above too... I've updated the `%m` to `%M` in both places now.

2021-08-05 14:39 UTC, ryanrath commented on classes/XDUser.php
> +            $update_data['password_last_updated'] = date('Y-m-d H:i:s');
Tested and removed in upcoming commit.

2021-08-05 14:39 UTC, ryanrath commented on classes/ETL/DbModel/Table.php
> +ORDER BY ordinal_position ASC;";
sure, removed in upcoming commit.

2021-08-05 14:42 UTC, ryanrath commented on configuration/etl/etl.d/cloud_ingest_resource_specs.json
> +                          "arguments": "-c '.hypervisors[].date += (.ts | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\")) | .hypervisors'"
Just commenting as I go through each code review section, I completely missed that you were talking about the second `%m`. That's been changed in an upcoming commit. I'll add in / test your proposed fix shortly.

2021-08-05 17:12 UTC, ryanrath commented on configuration/etl/etl_schemas.d/storage/usage.schema.json
> +            "pattern": "^\\d{4}-\\d{2}-\\d{2} \\d{2}:\\d{2}:\\d{2}",
Yeah, I've got nothing here... I know I made the change because I was getting errors similar to `2021-08-04 19:01:16 [warning] Record 6: Does not match the regex pattern date-time`. Hence, jq filter & updating the schema format / pattern to match. But that has, at the very least as @jpwhite4 pointed out, timezone issues. So I removed the `jq` filter and changed it back to `"format": "date-time"` and now it all works *throws hands up*. So yeah, one less line of modifications.

2021-08-05 17:19 UTC, ryanrath commented on configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
> +    IF ( @current_instance_type = instance_type AND @prev_start IS NOT NULL, @prev_start - 1, NULL) AS end_time,
This definitely came up while I was initially testing / developing the changes. But I can't reproduce the errors I was getting now so I've reverted it.

2021-08-05 18:12 UTC, ryanrath commented on configuration/etl/etl_tables.d/cloud_openstack/raw_event.json
> +                "type": "bigint(11)",
This change really only needs to be included when we ( if we? ) decide to turn on MariaDB's strict_mode at some point.

2021-08-05 18:16 UTC, ryanrath commented on tests/component/lib/ETL/BaseEtlTest.php
> +        $overseerOptions->setActionNames($actionName);
This isn't an actual functional change, just a cleanup of code that doesn't make sense. It doesn't make sense due to createLogger not actually return anything. I can remove the change if you'd rather.

2021-08-05 18:26 UTC, ryanrath commented on configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
> +    IF ( @current_instance_type = instance_type AND @prev_start IS NOT NULL, @prev_start - 1, NULL) AS end_time,
Ah hah! I turned on strict mode while testing a different change and I was able to reproduce it.
```
2021-08-05 18:11:25 [notice] Processing SQL file '/etc/xdmod/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql' using delimiter '//' containing 8 statements
2021-08-05 18:11:25 [error] {"sql":"CREATE TEMPORARY TABLE modw_cloud.tmp_end_times
AS
SELECT
    instance_type_id,
    instance_type,
    resource_id,
    IF ( @current_instance_type = instance_type AND @prev_start IS NOT NULL, @prev_start - INTERVAL 1 SECOND, NULL) AS end_time,
    @current_instance_type := instance_type AS junk1,
    @prev_start := start_time AS junk2
FROM modw_cloud.instance_type
ORDER BY instance_type, start_time DESC","stacktrace":"#0 \/usr\/share\/xdmod\/classes\/CCR\/DB\/PDODB.php(185): PDOStatement->execute(Array)
#1 \/usr\/share\/xdmod\/classes\/ETL\/Maintenance\/ExecuteSql.php(245): CCR\\DB\\PDODB->execute('CREATE TEMPORAR...')
#2 \/usr\/share\/xdmod\/classes\/ETL\/EtlOverseer.php(473): ETL\\Maintenance\\ExecuteSql->execute(Object(ETL\\EtlOverseerOptions))
#3 \/usr\/share\/xdmod\/classes\/ETL\/EtlOverseer.php(435): ETL\\EtlOverseer->_execute('xdmod.jobs-clou...', Object(ETL\\Maintenance\\ExecuteSql))
#4 \/usr\/share\/xdmod\/classes\/ETL\/Utilities.php(281): ETL\\EtlOverseer->execute(Object(ETL\\Configuration\\EtlConfiguration))
#5 \/usr\/share\/xdmod\/classes\/OpenXdmod\/DataWarehouseInitializer.php(249): ETL\\Utilities::runEtlPipeline(Array, Object(CCR\\Logger))
#6 \/usr\/share\/xdmod\/classes\/OpenXdmod\/DataWarehouseInitializer.php(143): OpenXdmod\\DataWarehouseInitializer->ingestCloudDataOpenStack()
#7 \/usr\/bin\/xdmod-ingestor(255): OpenXdmod\\DataWarehouseInitializer->ingestAll(NULL, NULL)
#8 \/usr\/bin\/xdmod-ingestor(21): main()
#9 {main}","message":"xdmod.jobs-cloud-extract-openstack.OpenStackCloudPostIngestUpdates (ETL\\Maintenance\\ExecuteSql): Error executing SQL Exception: 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1524063549.466164'' Using DataEndpoint: '('Cloud DB', class=ETL\\DataEndpoint\\Mysql, config=datawarehouse, schema=modw_cloud, host=localhost:3306, user=xdmod)'"}
2021-08-05 18:11:25 [warning] Stopping ETL due to exception in xdmod.jobs-cloud-extract-openstack.OpenStackCloudPostIngestUpdates (ETL\Maintenance\ExecuteSql)
2021-08-05 18:11:25 [critical] Ingestion failed: xdmod.jobs-cloud-extract-openstack.OpenStackCloudPostIngestUpdates (ETL\Maintenance\ExecuteSql): Error executing SQL Exception: 'SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '1524063549.466164'' Using DataEndpoint: '('Cloud DB', class=ETL\DataEndpoint\Mysql, config=datawarehouse, schema=modw_cloud, host=localhost:3306, user=xdmod)' (stacktrace: #0 /usr/share/xdmod/classes/ETL/Maintenance/ExecuteSql.php(250): CCR\Loggable->logAndThrowException('xdmod.jobs-clou...', Array)
#1 /usr/share/xdmod/classes/ETL/EtlOverseer.php(473): ETL\Maintenance\ExecuteSql->execute(Object(ETL\EtlOverseerOptions))
#2 /usr/share/xdmod/classes/ETL/EtlOverseer.php(435): ETL\EtlOverseer->_execute('xdmod.jobs-clou...', Object(ETL\Maintenance\ExecuteSql))
#3 /usr/share/xdmod/classes/ETL/Utilities.php(281): ETL\EtlOverseer->execute(Object(ETL\Configuration\EtlConfiguration))
#4 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(249): ETL\Utilities::runEtlPipeline(Array, Object(CCR\Logger))
#5 /usr/share/xdmod/classes/OpenXdmod/DataWarehouseInitializer.php(143): OpenXdmod\DataWarehouseInitializer->ingestCloudDataOpenStack()
#6 /usr/bin/xdmod-ingestor(255): OpenXdmod\DataWarehouseInitializer->ingestAll(NULL, NULL)
#7 /usr/bin/xdmod-ingestor(21): main()
#8 {main})
[root@e1b5b348bd3e xdmod]#
```

So yeah, we don't have to worry about this one until / if we decide to turn on strict mode.

2021-08-05 18:28 UTC, ryanrath commented on tests/component/lib/ETL/BaseEtlTest.php
> +        $overseerOptions->setActionNames($actionName);
There are tests in `DBModelTest.php` that operate in a `test` db, specifying that it should be created if it doesn't exist. The DB was not being created when the action was directly created / executed. The code path for db creation is only hit when executed via the ETLOverseer.

2021-08-05 18:32 UTC, ryanrath commented on configuration/etl/etl.d/staging.json
> +                            "arguments": "-c '[ .[] | (.dt = (.dt | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\"))) ]'"
This has been removed. It turns out when you specify the correct key in for a json schema property ( format / pattern ) things end up not needing to be pre-processed w/ jq.

2021-08-05 18:37 UTC, ryanrath commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +                    $expectedJson = json_encode(json_decode($expected), JSON_PRETTY_PRINT);
Yup yup: 
RegressionTestHelper.php: w/ PHP 7.2 installed, when dealing with exported CSV data we sometimes encounter and expect JSON data instead. For instance, when a user requests data that they do not have access to a JSON object will be returned. Unfortunately we compare this JSON data as strings and not as objects / arrays. This coupled with JSON Pretty Print not including a new line after the opening square bracket of an empty array (example below ): 
```json 
{ 
    "property1": "", 
    "property2": [ 

 ] 
}
``` 

 Versus 

```json 
{
    "property1": "", 
    "property2": [] 
}
 ```  


This meant that these tests were failing. I've just added a secondary test if the intitial `$expected === $csvdata` condition fails that tests if $expected / $csvdata are actually json data.

2021-08-05 18:57 UTC, ryanrath commented on configuration/etl/etl.d/cloud_ingest_resource_specs.json
> +                          "arguments": "-c '.hypervisors[].date += (.ts | fromdate | strftime(\"%Y-%m-%d %H:%m:%S\")) | .hypervisors'"
Ok, and finally, this is only something we need to look at it / when we enable SQL strict mode.

2021-08-06 13:23 UTC, jpwhite4 commented on configuration/etl/etl_sql.d/cloud_openstack/post_ingest_update.sql
> +    IF ( @current_instance_type = instance_type AND @prev_start IS NOT NULL, @prev_start - 1, NULL) AS end_time,
What is the datatype of `start_time`?

2021-08-06 13:26 UTC, jpwhite4 commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +                    $expectedJson = json_encode(json_decode($expected), JSON_PRETTY_PRINT);
So wehat exactly changed? Does JSON Pretty print in php 7.2 generate different output than 5.4?

2021-08-06 13:27 UTC, jpwhite4 commented on tests/component/lib/ETL/BaseEtlTest.php
> +        $overseerOptions->setActionNames($actionName);
Why does this work in php 5.4 and not in 7?

2021-08-06 13:43 UTC, jpwhite4 commented on tests/integration/lib/Controllers/UsageExplorerTest.php
> +        $ret[] = array($baseSettings, 'image/svg+xml', array('image/svg; charset=utf-8', 'text/plain; charset=utf-8'));
The problem with this change is that it makes it impossible to test whether the mime type is set to what it is supposed to be. The test will still pass if the mime type is different than it should be.

2021-08-16 18:59 UTC, ryanrath commented
Note: This PR won't pass until https://github.com/ubccr/xdmod/pull/1556 has been merged now.

2021-12-16 16:20 UTC, jpwhite4 requested changes

2021-12-16 16:20 UTC, jpwhite4 commented on tests/ui/package.json
> +    "log4js": "^6.3.0",
Is this needed? I can't see any references to log4js elsewhere in the code changes.

2021-12-16 16:20 UTC, jpwhite4 commented on tests/ui/wdio.conf.js
> +    './test/**/*.page.js',
Is this intended? Does this change switch all of the tests off?

2021-12-16 16:24 UTC, jpwhite4 commented on tests/ui/wdio.conf.js
> +    version: '87.0',
Elsewhere you have a sed script that changes the chromedriver version, but only on centos8. What is the impact of changing chorme version here for both centos7 and centos8?

2021-12-16 16:41 UTC, ryanrath commented on tests/ui/wdio.conf.js
> +    './test/**/*.page.js',
*facepalm* yeah... that definitely shouldn't have been left in. I've reverted those changes and pushed it up in the latest commit.

2021-12-16 16:45 UTC, ryanrath commented on tests/ui/package.json
> +    "log4js": "^6.3.0",
I'm not sure ( But I'm guessing not ), I'm testing removing it locally right now.

2021-12-16 16:48 UTC, ryanrath commented on tests/ui/package.json
> +    "log4js": "^6.3.0",
100% not needed ( I just found the commit where I spelled out why it was being added ). I brought this in to do some debugging.

2021-12-17 19:40 UTC, ryanrath commented on tests/ui/wdio.conf.js
> +    version: '87.0',
So this doesn't look like it has an impact at all on actually running the tests. I've tried running the tests w/ 87.0 on centos7 & 8 so far and they've both run successfully. Actually, I just tried running on centos7 after having removed the whole property and it ran just fine. After some looking around ( https://github.com/SeleniumHQ/selenium/wiki/DesiredCapabilities ) it looks like these properties are just our "desired capabilities" that wdio / webdriver will attempt to satisfy, so we've specified that the browserName is 'chrome' which will match what we have installed regardless of whether or not we have 84.0.0 or 87.0.0.

2022-01-07 16:45 UTC, jtpalmer commented on .circleci/config.yml
> -      - image: tools-ext-01.ccr.xdmod.org/xdmod-9.5.0:centos7.9-1.0
How is `tools-ext-01.ccr.xdmod.org/xdmod-9.5.0:centos7.9-0.3` different from `centos7.9-1.0`?  Are there changes to the Dockerfile?

2022-01-07 16:45 UTC, jtpalmer commented on open_xdmod/modules/xdmod/xdmod.spec.in
> +%{?el7:Requires: php-pecl-apcu}
Is there a reason to list `php-pecl-apcu`, `php-cli`, etc. separately for both el7 and el8?  I think it would be easier to see what is different if the common requirements were listed together.  Not really important, but I'm curious if there are benefits to listed them this way.

2022-01-07 16:45 UTC, jtpalmer commented on .circleci/config.yml
> +                name: Update the chromdriver version for Centos8
```suggestion
                name: Update the chromedriver version for Centos8
```

2022-01-07 16:45 UTC, jtpalmer commented on .circleci/config.yml
> +                name: Install new chromdriver
```suggestion
                name: Install new chromedriver
```

2022-01-07 17:00 UTC, ryanrath commented on .circleci/config.yml
> -      - image: tools-ext-01.ccr.xdmod.org/xdmod-9.5.0:centos7.9-1.0
I'm pulling `centos7.9-1.0` now to see what the difference is, if any, but my guess is that 0.3 is what was current when I started work on the PR and I just haven't updated it to 1.0 yet.

2022-01-07 17:09 UTC, ryanrath commented on open_xdmod/modules/xdmod/xdmod.spec.in
> +%{?el7:Requires: php-pecl-apcu}
Honestly this resulted from the way I went about accomplishing "Split the requirements of 7 from 8". I don't think that there's really any benefit to having them completely separated unless / until they actually are completely different and just a quick glance seems to show that there's a fair amount of overlap `php-cli php-pdo php-gd php-xml php-mbstring php-pecl-apcu`. That will also make it clear what's different between the two versions requirements.

2022-01-07 18:36 UTC, jtpalmer commented on open_xdmod/modules/xdmod/xdmod.spec.in
> +%{?el8:Requires: php-pecl-apcu}
Every time I look for a use of `php-gmp` I can't find it.  I'm not sure what it was being used for.

2022-01-07 18:41 UTC, jtpalmer commented on .circleci/config.yml
> +      - image: tools-ext-01.ccr.xdmod.org/centos8-0.3:base
Is there a `Dockerfile` for building this centos8 image?

2022-01-07 19:41 UTC, ryanrath commented on .circleci/config.yml
> +      - image: tools-ext-01.ccr.xdmod.org/centos8-0.3:base
There is, I just need to throw it up into a new branch on ccr-private.

2022-01-07 19:45 UTC, jtpalmer commented on .circleci/config.yml
> +      - image: tools-ext-01.ccr.xdmod.org/centos8-0.3:base
Is there anything in it that needs to be private?  We have the centos7 one in `tests/ci/Docker/`

2022-01-07 20:00 UTC, jpwhite4 approved these changes

2022-01-07 20:00 UTC, ryanrath commented on .circleci/config.yml
> +      - image: tools-ext-01.ccr.xdmod.org/centos8-0.3:base
Nope not really, I had just forgotten that we had moved the Dockerfile into the repo is all.

2022-01-07 20:04 UTC, merged