Create Gateways realm installation instructions
ubccr/xdmod pull request #1509
Opened 2021-03-11 14:28 UTC by jsperhac

## Description

Added markdown describing Gateways realm. This is documentation only and should accompany PR #1411.

## Motivation and Context

Provide brief documentation on, and instructions for installation of, this realm. 

## Tests performed

Markdown viewer. 

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2021-03-12 19:07 UTC, jpwhite4 commented on docs/gateways-realm.md
> +
```suggestion
XDMoD needs a mechanism to identify HPC jobs that were run via a gateway. The default mechanism is to use the last name associated with the user account that ran the jobs. Instructions for configuring the names are in the (User/PI Names guide)[user-names.md]. The steps to use this mechanism are:
1) Choose a suitable identifier to be used for a gateway (such as 'Gateway Proxy User')
1) Update the last name entries in `names.csv` for each gateway proxy user account.
1) Import the updated `names.csv`

2021-03-12 19:08 UTC, jpwhite4 commented
Also please can you update the command listing to match the documentation conventions:

https://open.xdmod.org/9.0/docs-conventions.html

2021-03-12 19:09 UTC, jpwhite4 commented
Also do we want a "Gateways realm (alpha)"  entry in the menu? I think yes.

2021-03-12 19:48 UTC, jsperhac commented on docs/gateways-realm.md
> +`etl_overseer.php --help`
True, and it sounds as though /usr/share/xdmod/tools/etl/ is the RPM install path, so I will indicate that here.

2021-03-12 19:48 UTC, jsperhac commented on docs/gateways-realm.md
> +Open XDMoD 9.5
I will fix that.

2021-03-12 19:57 UTC, jsperhac commented on docs/gateways-realm.md
> +`etl_overseer.php --help`
...and everywhere I refer to the command.

2021-03-12 20:06 UTC, jsperhac commented
> Also do we want a "Gateways realm (alpha)" entry in the menu? I think yes.

Sounds good. I will add this under the "Installing" heading.

2021-03-19 14:55 UTC, jpwhite4 requested changes

2021-03-19 14:55 UTC, jpwhite4 commented on docs/gateways-realm.md
> +The gateways realm displays jobs information due to science gateways. It does this by incorporating jobs data in a new XDMoD database, modw_gateways, created for capturing gateways data. This realm i
```suggestion
The gateways realm displays jobs information due to science gateways. It does this by incorporating jobs data in a new XDMoD database, `modw_gateways`, created for capturing gateways data. This realm is not enabled by default in the current release. These instructions show you how to enable and populate the gateways realm in your Open XDMoD installation.
```

2021-03-19 14:55 UTC, jpwhite4 commented on docs/gateways-realm.md
> +`$ /usr/share/xdmod/tools/etl/etl_overseer.php -p gateways.ingest -d community-user=Bunting`
```suggestion
`$ /usr/share/xdmod/tools/etl/etl_overseer.php -p gateways.ingest -d community-user='Gateway proxy user'`
```

2021-03-19 14:55 UTC, jpwhite4 commented on docs/gateways-realm.md
> +For good measure you may now restart all services (database, webserver, etc.).
I don't think this step is necessary. If it were necessary then you should give instructions on how to do it.

2021-03-26 13:49 UTC, jpwhite4 approved these changes

2021-03-26 14:22 UTC, merged