Update Query Filtering to be based on acls again
ubccr/xdmod pull request #1531
Opened 2021-05-05 17:33 UTC by ryanrath

## Description
This PR's purpose is to replace the hard coded logic of
`Parameters::getParameters`, the function that determines how a query should be
filtered based on what a users most privileged acl is, with a database query
that utilizes the `user_acl_group_by_parameters` table.

To accomplish this we first need to capture for each acl which, if any,
dimension filtering is required. Thankfully our configuration files contain this
information already in the `dimensions` property. A new table was created
`acl_dimensions` that serve as a relation table between `acls` and `group_bys` (
dimension is another name for a group_by, and seeing as we already have an
`acl_group_bys` table, `acl_dimensions` it is. ). To ensure this table is
populated correctly the `acl-config` script was updated to include this as
another managed table. Next, to ensure that when a user is created or modified
the appropriate records are created in the `user_acl_group_by_parameeters` table
the `XDUser::saveUser` function was updated to include the maintenance of these
records.

New component tests ( and artifacts ) have been added to exercise the
`Parameters::getParameters` function.

## Motivation and Context
The old function, while consolidating the logic of which filters should be applied in which cases, did so via hard coded `logic` which is not only not ideal, but we have a table ( `user_acl_group_by_parameters`) that is designed to provide this logic. It is also in keeping with our established design tenant of exclusively using the database at runtime versus configuration files which the old function was also not doing. 

## Tests performed
All automated test suites executed & passed for both the upgrade and install paths. 

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2021-11-10 13:09 UTC, jtpalmer requested changes
Looks fine as far as I can tell.  Not sure why the upgrade is failing.  I just have some requests for doc updates.

2021-11-10 13:09 UTC, jtpalmer commented on classes/Models/Services/Parameters.php
> + * This class is meant to provide the
Provide the?

2021-12-01 18:08 UTC, ryanrath commented on bin/acl-config
> +function processAcl(iDatabase $db, $module, $name, $display, $type = null, $hierarchies = null, $dimensions = null)
Sorry about missing your review on this PR, all of your requested changes should be in the latest commit.

2021-12-01 18:09 UTC, ryanrath commented on bin/acl-config
> + * @param array     $dimensions
Definitely, I've updated the doc blocks in the latest commit.

2021-12-01 18:10 UTC, ryanrath commented on classes/Models/Services/Parameters.php
> + * This class is meant to provide the
Answer to life the Universe and Everything? I wish... I have finished writing the documentation block for this class in the latest commit though.

2021-12-03 13:23 UTC, jtpalmer approved these changes

2021-12-03 16:06 UTC, merged