Convert modw_cloud tables to InnoDB table engine
ubccr/xdmod pull request #1572
Opened 2021-11-15 18:52 UTC by eiffel777

This PR converts tables in the `modw_cloud` database to the InnoDB table engine. For existing XDMoD installations the tables will be converted during the upgrade.

## Tests performed
Tested in Docker

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2021-11-16 14:11 UTC, jtpalmer requested changes

2021-11-16 14:11 UTC, jtpalmer commented on configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
> +	          }
This indentation looks off.

2021-11-18 17:00 UTC, eiffel777 commented on configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/modw_cloud/convert_innodb_aggregate_tables.sql
> +-- The `modw_cloud` aggregate tables cannot be changed to the InnoDB table engine
@jtpalmer It is needed for the `resourcespecsfact_by` tables but those are in `modw_aggregates` not `modw_cloud`. There will be another pull request for tables in the `modw_aggregates` database.

2021-11-18 19:51 UTC, jtpalmer approved these changes

2021-12-01 18:48 UTC, merged