CentOS8 / Rocky Linux XDMoD Docker
ubccr/xdmod pull request #1607
Opened 2022-02-07 21:18 UTC by ryanrath

## Description
- Added CentOS8 / Rocky Linux Docker files. 
- Due to new version of PHP / Composer needed to add an `allow-plugins` section to `composer.json` so that `composer install` would not hang during the CI process. 
- Added the expected test artifacts for regression tests on Rocky Linux. 
- Updated the `copy-caches.sh` script w/ the ability to detect which version of CentOS / Rocky Linux it's running on so that it can copy over a different version of chromedriver.
- Updated `mysql-server.cnf` w/ `sql_mode = ` so that it puts the local MySQL server in permissive sql mode. **note:** this can be removed once we address all the crazy SQL shenanigans that we get up to.
- Added `mysql-prepare-db-dir` script as it was missing. 
- Refactored the `bin/services` script so that it can detect which version of CentOS / Rocky Linux it's running on so that it can spin up / kill `php-fpm` if it's running on CentOS8 / Rocky Linux. 
- Updated UI tests dependencies w/ a newer version of chromedriver & fibers. 

## Motivation and Context
We need to move with times. 

## Tests performed
- These changes / files create working docker containers w/ XDMoD 10.0 installed that passes all automated tests. 
- You can still install / upgrade on CentOS7 w/ these changes. 

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2022-03-08 13:57 UTC, jtpalmer requested changes

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/Docker/bin/mysql-prepare-db-dir
> +#!/bin/sh
This file does exist in Rocky 8/MariaDB 10.3 it just has a different name depending on the MariaDB version.  Does that version not work?

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +FROM centos:8
```suggestion
FROM centos:8.4.2105
```

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +    java-1.8.0-openjdk-devel \
Do we still need Java?

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +    gmp-devel \
I know we've talked about this one before, but I thought we determined that we aren't using anything that needs GMP.

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/bootstrap.sh
> -# image is created without these packages installed.
Why remove this comment?  Are you planning to merge this before or after to 10.0 release?

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/Docker/Dockerfile.centos8
> +ENV BUILD=1.0
These variables aren't used, are they necessary? The CentOS 7 Dockerfile uses them to determine which RPM to install, but that isn't done in this version.

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
This doesn't appear to be necessary since it's already done above.

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/Docker/bin/services
> +  done
There's a lot of indentation changes here making it hard to see what changed.  Please keep the old indentation.

2022-03-08 13:57 UTC, jtpalmer commented on tests/ci/Docker/Dockerfile.centos8
> +RUN npm install
Is this necessary?  `/root/xdmod` is removed below.  Is there a side effect from installing the dependencies?

2022-03-08 16:49 UTC, ryanrath commented on tests/ci/Docker/Dockerfile.centos8
> +RUN npm install
hrmm, probably not. I'll remove it.

2022-03-08 16:50 UTC, ryanrath commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-* && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
Yup, I'll remove this step.

2022-03-08 16:51 UTC, ryanrath commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +    gmp-devel \
Maaaybe? I'll try removing it and see if anything breaks.

2022-03-09 16:51 UTC, ryanrath commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +    gmp-devel \
kk, just tested and yeah, looks like we don't need this or java. I'll go ahead and remove them.

2022-03-09 16:52 UTC, ryanrath commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +    java-1.8.0-openjdk-devel \
nope, just tested along with removing `gmp-devel`, I'll go ahead and remove it.

2022-03-09 16:55 UTC, ryanrath commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +RUN yum -y install \
I split them so that when I added / removed a package I didn't have to wait to for the **entire** thing to run again. i.e. to speed up testing / development. It does also make it clear what packages are non-php pre-reqs vs. php. But I can definitely combine them.

2022-03-09 16:55 UTC, ryanrath commented on tests/ci/Docker/Dockerfile.rocky8.xdmod-base
> +FROM rockylinux:8
sure, this is just what was out when I originally wrote the Dockerfile.

2022-03-09 18:58 UTC, jtpalmer commented on tests/ci/Docker/Dockerfile.centos8.xdmod-base
> +RUN yum -y install \
I'm not sure how much benefit there is from combining various steps.  We've also exported and re-imported images in the past which I think combines everything, but then you lose the benefits of having multiple image layers

2022-04-07 17:31 UTC, jtpalmer requested changes

2022-04-07 17:31 UTC, jtpalmer commented on docs/_data/toc.yml
> +        url: /rest.html
The documentation changes from #1558 and still here.  I created #1619 to merge those separately.  I think it's best to keep them separate so it's clear they are not related.

2022-04-07 17:31 UTC, jtpalmer commented on tests/ci/Docker/Dockerfile.centos8
> +ENV BUILD=1.0
Do you want to switch this to use the RPM.  Probably not a big deal to leave it like this.

2022-04-07 17:31 UTC, jtpalmer commented on tests/ci/Docker/assets/copy-caches.sh
> +          mv $ASSETS/chromedriver_linux64-97.0.zip /root/chromedriver_linux64.zip
Did you rebuild the Docker images with Chromium 99?  I'd like to use the same version in both CentOS 7 and 8, etc. if possible.

2022-04-07 17:31 UTC, jtpalmer commented on tests/ci/Docker/bin/services
> +    esac
```suggestion
esac
```

2022-04-07 17:31 UTC, jtpalmer commented on tests/ci/bootstrap.sh
>  esac
This can be removed now that it's already in the Dockerfile.

2022-04-07 17:31 UTC, jtpalmer commented on tests/ci/bootstrap.sh
> +    # TODO: Replace diff files with hard fixes A
```suggestion
    # TODO: Replace diff files with hard fixes
```

2022-05-02 17:27 UTC, jtpalmer commented on tests/ci/Docker/assets/copy-caches.sh
> +          mv $ASSETS/chromedriver_linux64-97.0.zip /root/chromedriver_linux64.zip
`.circleci/config.yml` is still using tools-ext-01.ccr.xdmod.org/xdmod10.0.0:centos8.4-0.1, etc.

2022-05-02 17:51 UTC, jtpalmer commented on tests/ci/Docker/assets/copy-caches.sh
> +      # Error out ?
Did you decide if this should error or not?

2022-05-02 17:54 UTC, ryanrath commented on tests/ci/Docker/assets/copy-caches.sh
> +      # Error out ?
I'm just going to be removing the os specific section since all of the images use the same version now.

2022-05-05 18:12 UTC, ryanrath commented on tests/ci/Docker/assets/copy-caches.sh
> +          mv $ASSETS/chromedriver_linux64-97.0.zip /root/chromedriver_linux64.zip
@jtpalmer Alrighty, I've finally managed to get the Rocky8 image uploaded and all the tests are now passing.

2022-05-05 18:32 UTC, jtpalmer requested changes

2022-05-05 18:32 UTC, jtpalmer commented on tests/ci/Docker/assets/copy-caches.sh
> +
This variable isn't used anymore.  You can revert this file unless those assets are no longer optionally so that comment is inaccurate.

2022-05-05 18:44 UTC, jtpalmer approved these changes

2022-05-05 18:55 UTC, merged