Fix schema version history
ubccr/xdmod pull request #1608
Opened 2022-02-08 00:03 UTC by ryanrath

## Description
Updated the `action_datetime` column of the various `schema_version_history` tables to have a default value of `CURRENT_TIMESTAMP` and removed the `action_datetime` column & value from the various data files used to populate these tables. 

## Motivation and Context
This is an issue I found when working on CentOS8 changes. 

## Tests performed

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2022-02-08 18:43 UTC, jtpalmer requested changes
Please remove the `getDatabaseVersion` function from `classes/Xdmod/Version.php`.  It isn't used anywhere that I can find.  Also please update the description of the pull request.

2022-02-08 18:43 UTC, jtpalmer commented on db/data/mod_logger.sql
> -
I think this is still needed.

2022-02-08 20:17 UTC, ryanrath commented on db/data/mod_logger.sql
> -
Yup, just replaced it, minus the schema_version_history insert at the end.

2022-02-09 12:42 UTC, jtpalmer commented on configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/drop_schema_version_history.sql
> +-- DROP the schema_version_history table in mod_hpcdb, mod_logger, moddb, modw
```suggestion
-- DROP the schema_version_history table in mod_hpcdb, mod_logger, mod_shredder, moddb, modw
```

I'm against comments like this, but if you're going to include it then might as well include all the schemas.

2022-02-09 12:45 UTC, jtpalmer commented on configuration/etl/etl.d/xdmod-migration-9_5_0-10_0_0.json
> +         },
```suggestion
        },
```

More indentation that shouldn't change.

2022-02-09 12:45 UTC, jtpalmer commented on classes/Xdmod/Version.php
> +      /**
```suggestion
    /**
```
Indentation shouldn't change here.

2022-02-09 14:27 UTC, ryanrath commented on configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/drop_schema_version_history.sql
> +-- DROP the schema_version_history table in mod_hpcdb, mod_logger, moddb, modw
agreed about including all of the tables in the comment. What kind of comment would you prefer to see here?

2022-02-09 14:49 UTC, jtpalmer commented on configuration/etl/etl_sql.d/migrations/9.5.0-10.0.0/drop_schema_version_history.sql
> +-- DROP the schema_version_history table in mod_hpcdb, mod_logger, moddb, modw
I don't think any comment is necessary.  If you really need one you could explain why the tables are being dropped.

2022-02-09 14:50 UTC, jtpalmer approved these changes
Please update the description of the pull request.

2022-02-09 15:16 UTC, merged