Innodb documentation updates
ubccr/xdmod pull request #1611
Opened 2022-02-18 17:24 UTC by eiffel777

Documentation related to InnoDB tables in XDMoD and the conversion of MyISAM tables to InnoDB

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2022-02-24 14:38 UTC, jtpalmer requested changes

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +We recommend setting `innodb_buffer_pool_size` to around 50% of the memory on your server.
We don't do this on either the development or staging server.  Why are we recommending it and not doing this ourselves?

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +We recommend setting `innodb_file_per_table = On` for your XDMoD instance but it
```suggestion
We recommend setting `innodb_file_per_table = On` for your Open XDMoD instance but it
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +on the database server not just XDMoD related databases.
```suggestion
on the database server not just Open XDMoD related databases.
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +we recommend that you export, drop, and re-import all XDMoD InnoDB tables in order
```suggestion
we recommend that you export, drop, and re-import all Open XDMoD InnoDB tables in order
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +This script will only convert XDMoD related databases. For any non-XDMoD databases
```suggestion
This script will only convert Open XDMoD related databases. For any non-Open XDMoD databases
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +1. Export all XDMoD InnoDB tables. This can be done with the following command
```suggestion
1. Export all Open XDMoD InnoDB tables. This can be done with the following command
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +2. Drop all XDMoD InnoDB tables. This can be done using the --drop-tables flag,
```suggestion
2. Drop all Open XDMoD InnoDB tables. This can be done using the `--drop-tables` flag,
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +`xdmod-innodb-convert-fpt --drop-tables`. This command will delete your XDMoD tables!
```suggestion
`xdmod-innodb-convert-fpt --drop-tables`. This command will drop your Open XDMoD InnoDB tables!
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +7. Import XDMoD InnoDB data previously exported. This can be done with the following command:
```suggestion
7. Import Open XDMoD InnoDB data previously exported. This can be done with the following command:
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +5. Delete the ibdata1, ib_logfile0 and ib_logfile1 files from the mysql data directory.
```suggestion
5. Delete the `ibdata1`, `ib_logfile0` and `ib_logfile1` files from the MySQL data directory.
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/upgrade.md
> +upgrade took around 30 hours with most of that time being spent on converting
```suggestion
upgrade took around 40 hours with most of that time being spent on converting
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +While not mandatory, when changing the innodb_file_per_table to `innodb_file_per_table = On`
```suggestion
While not mandatory, when changing the `innodb_file_per_table` to `innodb_file_per_table = On`
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +The steps to enable the innodb_file_per_table MySQL option and making sure
```suggestion
The steps to enable the `innodb_file_per_table` MySQL option and making sure
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +4. Add the following line to /etc/my.cnf file.
```suggestion
4. Add the following line to `/etc/my.cnf` file.
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/configuration.md
> +   innodb_file_per_table = 'On'
```suggestion
   innodb_file_per_table = On
```

2022-02-24 14:38 UTC, jtpalmer commented on docs/upgrade.md
>  ### Database Changes
Please add a note about and a link to the `innodb_file_per_table` instructions here.

2022-02-24 14:59 UTC, eiffel777 commented on docs/configuration.md
> +We recommend setting `innodb_buffer_pool_size` to around 50% of the memory on your server.
@jtpalmer I thought I had this on the staging server but I guess not. It might have got lost in the migration to the new cloud and I forgot to update it. For dev, I probably just forgot to add it to puppet. I can add it to the puppet files.

2022-02-24 15:08 UTC, jtpalmer commented on docs/configuration.md
> +We recommend setting `innodb_buffer_pool_size` to around 50% of the memory on your server.
Ok, sounds good.  There are probably also some MyISAM settings that can be lowered as well.

2022-02-24 17:13 UTC, jtpalmer requested changes

2022-02-24 17:13 UTC, jtpalmer commented on docs/configuration.md
> +A script, `/bin/xdmod-innodb-convert-fpt`, is provided to help with this process.
```suggestion
A script, `/bin/xdmod-convert-innodb-fpt`, is provided to help with this process.
```

2022-02-24 17:13 UTC, jtpalmer commented on docs/configuration.md
> +existing InnoDB data is moved to the appropriate file by using the `xdmod-innodb-convert-fpt`
```suggestion
existing InnoDB data is moved to the appropriate file by using the `xdmod-convert-innodb-fpt`
```

2022-02-24 17:13 UTC, jtpalmer commented on docs/configuration.md
> +`xdmod-innodb-convert-fpt --export-tables --dir=path/to/dir`
```suggestion
`xdmod-convert-innodb-fpt --export-tables --dir=path/to/dir`
```

2022-02-24 17:13 UTC, jtpalmer commented on docs/configuration.md
> +`xdmod-innodb-convert-fpt --drop-tables`. This command will drop your Open XDMoD InnoDB tables!
```suggestion
`xdmod-convert-innodb-fpt --drop-tables`. This command will drop your Open XDMoD InnoDB tables!
```

2022-02-24 17:13 UTC, jtpalmer commented on docs/configuration.md
> +Please make sure you have either run the command `xdmod-innodb-convert-fpt --export-tables --dir=path/to/dir`
```suggestion
Please make sure you have either run the command `xdmod-convert-innodb-fpt --export-tables --dir=path/to/dir`
```

2022-02-24 17:13 UTC, jtpalmer commented on docs/configuration.md
> +`xdmod-innodb-convert-fpt --import-tables --dir=path/to/dir`
```suggestion
`xdmod-convert-innodb-fpt --import-tables --dir=path/to/dir`
```

2022-02-25 19:25 UTC, jtpalmer approved these changes

2022-02-25 19:27 UTC, merged