Update update.sh
ubccr/xdmod pull request #1643
Opened 2022-06-07 20:33 UTC by thanickcruz

Added get_sitemap.py script 

## Description

Runs get_sitemap.py after update. 

## Motivation and Context

This addition automates the sitemap creation process for every update. After update.sh is run, the sitemap in the gh-pages branch will be updated as well. 

## Tests performed

1. Checked that sitemap.xml appears in gh-pages branch after running update.sh
2. Ensured sitemap appears so long as the version exists, the table of contents for that version exists, and _config.yml is up to date.

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2022-06-07 20:34 UTC, jpwhite4 commented
Don't forget to git add the `get_sitemap.py` and also git add the autogenerated site map file too.

2022-06-08 18:42 UTC, jpwhite4 approved these changes

2022-06-08 18:42 UTC, merged

2022-06-08 18:43 UTC, jtpalmer requested changes

2022-06-08 18:43 UTC, jtpalmer commented on update.sh
> +python3 ./get_sitemap.py
Please update the comment at the top of this file to add `python3` and anything else that is required.