Update Contact Us button for ACCESS XDMoD
ubccr/xdmod pull request #1669
Opened 2022-08-24 19:08 UTC by connersaeli

This PR updates the Contact Us button to instead redirect to a configured URL for ACCESS tickets. This only works if the configured URL is present, else it will default to Open XDMoD's functionality.

## Description

1.) Checks if 'tech_support_url' is set in configuration.
2.) If 'tech_support_url' is present, then the Contact Us button redirects to that site instead of the dropdown menu.

Without tech_support_url set:
![image](https://user-images.githubusercontent.com/51850219/186502018-d8120f50-fa3d-49e6-84f5-8426f43d202a.png)

With tech_support_url set:
![image](https://user-images.githubusercontent.com/51850219/186502344-179bf3d3-b75c-4d79-93c2-32853f8c17a8.png)
In the screenshot the Contact Us button will redirect to the configured URL.

## Motivation and Context

ACCESS XDMoD does not need the same dropdown menu for this button as Open XDMoD.

https://app.asana.com/0/1202679277743034/1202840692396198

## Tests performed

Tested on my development port.

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2022-08-24 20:49 UTC, jpwhite4 requested changes

2022-08-24 20:49 UTC, jpwhite4 commented on html/index.php
> +        print "CCR.xdmod.support_url = CCR.xdmod.support_url = '$tech_support_url';\n";
```suggestion
        print 'CCR.xdmod.support_url = ' . json_encode($tech_support_url) . ";\n";
```

You had a typo in the string: "CCR.xdmod.support_url = CCR.xdmod.support_url".

Also you are going to have to encode the $tech_supprt_url variable to make sure it is valid json. I suggest using json_encode. This will ensure that any special characters in the string are escaped and if the variable is set to `false` then it will get output as javascript `false`. The current code will set a javascript string that has the letters  f a l s e in it. This will evaluate to true!

2022-08-24 20:49 UTC, jpwhite4 commented on html/gui/js/CCR.js
> +                window.location.href = CCR.xdmod.support_url;
Does this open in a new window or in the current one?

2022-08-24 20:50 UTC, connersaeli commented on html/gui/js/CCR.js
> +                window.location.href = CCR.xdmod.support_url;
This opens in the same window.

2022-08-24 20:52 UTC, jpwhite4 commented on html/index.php
> +        print "CCR.xdmod.support_url = CCR.xdmod.support_url = '$tech_support_url';\n";
![image](https://user-images.githubusercontent.com/5342179/186521082-79004f27-a72e-4c98-b14a-201a41b12d1a.png)

2022-08-24 20:58 UTC, jpwhite4 commented on html/gui/js/CCR.js
> +                window.location.href = CCR.xdmod.support_url;
Can to change this to open in a new tab (like we do with the user manual). Often you want to add screenshots when submitting a support ticket and you can't easily do that if the portal is gone

2022-08-24 20:59 UTC, connersaeli commented on html/gui/js/CCR.js
> +                window.location.href = CCR.xdmod.support_url;
Ok no problem

2022-08-24 21:00 UTC, jpwhite4 commented on html/gui/js/CCR.js
> +                window.location.href = CCR.xdmod.support_url;
looks like `window.open("user_manual.php");` is used for the user manual code

2022-08-24 21:04 UTC, connersaeli commented on html/index.php
> +        print "CCR.xdmod.support_url = CCR.xdmod.support_url = '$tech_support_url';\n";
Ok I see your point about using json_encode. Just to clarify, this is to also handle the case where tech_support_url is set as 'false' in the configuration file?

2022-08-24 21:14 UTC, connersaeli commented on html/gui/js/CCR.js
> +                window.location.href = CCR.xdmod.support_url;
Just added that change

2022-08-24 21:15 UTC, jpwhite4 commented on html/index.php
> +        print "CCR.xdmod.support_url = CCR.xdmod.support_url = '$tech_support_url';\n";
The scenario I was thinking of was when `tech_support_url` is absent from the file. Having thought about it I realize that php boolean variable false will evaluate to empty string in your code, which is javascript falsy. So this case won't happen. 

But certainly to need to make sure that you encode the `$tech_support_url` variable properly

2022-08-25 02:06 UTC, jpwhite4 approved these changes

2022-08-25 14:59 UTC, merged