Update About -> Links page
ubccr/xdmod pull request #1672
Opened 2022-08-25 18:23 UTC by connersaeli

## Description

Updated this page for ACCESS transition. Images and their corresponding links were changed.

![image](https://user-images.githubusercontent.com/51850219/186739872-9fde3eea-90a8-47ca-88e8-e08483f2452c.png)
![image](https://user-images.githubusercontent.com/51850219/186739795-1e58b17c-1689-4381-a309-947563f84c7c.png)

## Motivation and Context

https://app.asana.com/0/1202679277743034/1202852322868255

## Tests performed

Tested on my development port.

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2022-08-25 20:58 UTC, jpwhite4 commented on html/about/links.html
> +  <td div align=center> <a href="https://www.tacc.utexas.edu/" target="_blank" rel="noopener noreferrer"><img src="/about/images/TACC_logo.png" width="300"></a>
how come this line shows as changed in the diff?

2022-08-25 20:58 UTC, jpwhite4 commented on html/about/links.html
> +  <td div align=center> <a href="https://www.sdsc.edu/" target="_blank" rel="noopener noreferrer"><img src="/about/images/sdsc_logo.png" height="100" width="300"></a>
This changes the aspect ratio of the logo, which is not a good idea since it has text in it.

2022-08-25 20:59 UTC, jpwhite4 requested changes

2022-08-25 20:59 UTC, jpwhite4 commented on html/about/links.html
> +  <td div align=center> <a href="https://www.sdsc.edu/" target="_blank" rel="noopener noreferrer"><img src="/about/images/sdsc_logo.png" height="100" width="300"></a>
Why not use a logo that has the same shape as the others?

https://www.sdsc.edu/assets/images/logos/SDSClogo-plusname-red.jpg

2022-08-25 22:11 UTC, connersaeli commented on html/about/links.html
> +  <td div align=center> <a href="https://www.tacc.utexas.edu/" target="_blank" rel="noopener noreferrer"><img src="/about/images/TACC_logo.png" width="300"></a>
There was a floating double quote after 'width' for the TACC line that I closed and I just changed the following line to match that formatting.

2022-08-25 22:24 UTC, connersaeli commented on html/about/links.html
> +  <td div align=center> <a href="https://www.sdsc.edu/" target="_blank" rel="noopener noreferrer"><img src="/about/images/sdsc_logo.png" height="100" width="300"></a>
Updated with suggested logo:
![image](https://user-images.githubusercontent.com/51850219/186779252-51f936bd-2713-46ab-ba1c-afcb7790943b.png)

2022-08-25 22:27 UTC, connersaeli commented on html/about/links.html
> +  <td div align=center> <a href="https://www.sdsc.edu/" target="_blank" rel="noopener noreferrer"><img src="/about/images/sdsc_logo.png" height="100" width="300"></a>
There is no longer height/width modifier for this update --> original aspect ratio is preserved

2022-08-25 23:47 UTC, jpwhite4 commented on html/about/links.html
> +  <td div align=center> <a href="https://www.tacc.utexas.edu/" target="_blank" rel="noopener noreferrer"><img src="/about/images/TACC_logo.png" width="300"></a>
ah well spotted - I was staring at that line for ages trying to work out what was different

2022-08-26 18:50 UTC, connersaeli commented
Resize Tufts logo to match others:
![image](https://user-images.githubusercontent.com/51850219/186972175-df8b0c8d-4453-466d-b9a2-bc7595868701.png)

2022-10-07 15:47 UTC, jpwhite4 submitted a review, later dismissed

2022-10-07 18:03 UTC, closed without merging