API Token Framework
ubccr/xdmod pull request #1695
Opened 2023-02-28 14:57 UTC by ryanrath

## Description

## Motivation and Context
To support the new Data Analytics Framework authentication / authorization needs this PR adds API Tokens to XDMoD, these tokens are meant to allow programmatic access to very specific endpoints which have also been added. An API Token can only be generated by a traditionally authenticated user and a user may only have one active at any one time. Users will be able to interact with the new API Token framework via the `My Profile` portion of the UI being implemented in https://github.com/ubccr/xdmod/pull/1694 . 

## Tests performed
Integration tests have been added for all new endpoints. This includes the API Token management endpoints as well as the endpoints that can only be accessed w/ a valid API Token. 

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2023-03-01 21:17 UTC, jpwhite4 commented on classes/Models/Services/Tokens.php
> +    const TOKEN_FORMAT = '|^([\w=]+)\.([a-zA-Z0-9/.$]+)$|';
Is this set of characters guaranteed to be appropriate for the hash algorithm? I can't see any documentation that lists the set of characters that are allowed to be in the hash (and hence I'd assume that any characters are valid).

2023-03-01 21:19 UTC, jpwhite4 commented on classes/Models/Services/Tokens.php
> +                    var_export($expectedUserId, true),
Since the 'expected*' variables are our private data I don't think we should be outputting them in error execpetions. This seems like it could be used by a malicious actor to guess valid usernames.

2023-03-01 21:24 UTC, jpwhite4 commented on classes/Models/Services/Tokens.php
> +        $userId = html_entity_decode(base64_decode($matches[1]));
I'm not sure that html_entity_decode() belongs here. Please explain why its needed and where the corresponding html_entity_encode() is done?

2023-03-01 21:26 UTC, jpwhite4 commented on classes/Rest/Controllers/BaseControllerProvider.php
> +use Exception;
How come this has been added? I can't see any new code that throws it (in any case we should prefer not to throw Exception and instead use one of the specfic ones.

2023-03-01 21:27 UTC, jpwhite4 commented on classes/Rest/Controllers/BaseControllerProvider.php
> +     * @throws Exception if not all of the $requiredParams were found.
Don't think this change should be made.

2023-03-01 21:27 UTC, jpwhite4 commented on classes/Rest/Controllers/BaseControllerProvider.php
> +use XDUser;
How come we need to use XDUser here? I don't see any changes that use it

2023-03-01 21:29 UTC, jpwhite4 commented on classes/Rest/Controllers/UserControllerProvider.php
> +        } catch (\Exception $e) {
You don't need to do this - the rest stack already has code that traps unhandled exceptions and returns the message as json

2023-03-01 21:30 UTC, jpwhite4 commented on classes/Rest/Controllers/UserControllerProvider.php
> +        $expirationInterval = \xd_utilities\getConfiguration('api_token', 'expiration_interval');
Lots of extra spaces?

2023-03-01 21:34 UTC, jpwhite4 commented on classes/Models/Services/Tokens.php
> +        $match = preg_match(self::TOKEN_FORMAT, $expectedToken, $matches);
Seems like it would be more computationally efficient to do this check before adding data to the database - not every time we read from the database.

Under what circumstances would we have corrupted token format in the database?

2023-03-01 21:36 UTC, jpwhite4 commented on classes/Models/Services/Tokens.php
> +        $match = preg_match(self::TOKEN_FORMAT, $expectedToken, $matches);
Also why do a regular expression at all at this point? We know the username since it is a dedicated column in the database. Why not have one column for the username and one for the hash?

2023-03-01 21:39 UTC, jpwhite4 commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    'Basic realm="Access to Data Analytics endpoints", charset="UTF-8"',
Is this a cut-and-paste error?
```
Basic realm="Access to Data Analytics endpoints", charset="UTF-8"
```

2023-03-01 21:43 UTC, jpwhite4 requested changes
comments added inline

2023-03-01 22:02 UTC, jpwhite4 commented
Also the lookup for the token should check that moddb.Users.account_is_active is 1

2023-03-02 16:05 UTC, ryanrath commented on classes/Models/Services/Tokens.php
> +    const TOKEN_FORMAT = '|^([\w=]+)\.([a-zA-Z0-9/.$]+)$|';
This has been removed per our convo this morning.

2023-03-02 18:46 UTC, ryanrath commented on classes/Models/Services/Tokens.php
> +                    var_export($expectedUserId, true),
Oh definitely, this was part of debugging that should have been removed.

2023-03-02 18:48 UTC, ryanrath commented on classes/Rest/Controllers/BaseControllerProvider.php
> +use Exception;
It was added by IDE for the `@throws Exception` for the `authenticateToken` function.

2023-03-02 18:49 UTC, ryanrath commented on classes/Rest/Controllers/BaseControllerProvider.php
> +     * @throws Exception if not all of the $requiredParams were found.
Sure, this is just related to the addition of `use Exception;`. Since it's now been `use`'d the `\` can be removed.

2023-03-02 19:12 UTC, ryanrath commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    'Basic realm="Access to Data Analytics endpoints", charset="UTF-8"',
Yeah basically. I've just replaced with with a `BadRequestHttpException`

2023-03-02 19:50 UTC, ryanrath commented on classes/Rest/Controllers/UserControllerProvider.php
> +        } catch (\Exception $e) {
Yeah, I got into the habit when working on the the new rest stuff as I was holding off on a general catch all until I had worked out all the kinks. Obviously no reason to do it here.

2023-03-02 19:59 UTC, ryanrath commented on classes/Rest/Controllers/BaseControllerProvider.php
> +use XDUser;
This is the same as https://github.com/ubccr/xdmod/pull/1695#discussion_r1122315350

2023-03-02 20:00 UTC, ryanrath commented on classes/Models/Services/Tokens.php
> +        $match = preg_match(self::TOKEN_FORMAT, $expectedToken, $matches);
I've re-worked this per our convo this morning.

2023-03-02 20:00 UTC, ryanrath commented on classes/Rest/Controllers/UserControllerProvider.php
> +        $storedToken = sprintf('%s.%s', $encodedUserId, $hash);
This has been re-worked per our convo this morning.

2023-03-02 20:01 UTC, ryanrath commented on classes/Models/Services/Tokens.php
> +        $userId = html_entity_decode(base64_decode($matches[1]));
Updated per our convo this morning.

2023-03-02 21:15 UTC, ryanrath commented on classes/Rest/Controllers/BaseControllerProvider.php
> +     * @throws Exception if not all of the $requiredParams were found.
So this function isn't actually being used anymore, I'm just going to remove it.

2023-03-02 21:21 UTC, jpwhite4 commented on classes/Models/Services/Tokens.php
> +        return XDUser::getUserByID($userId);
best to select the userId from the database and use that value in getUserByID call. The `$userId` variable contains untrused user supplied content.

2023-03-07 16:33 UTC, ryanrath commented on classes/Models/Services/Tokens.php
> +        return XDUser::getUserByID($userId);
Agreed, implemented in latest commits.

2023-03-08 02:12 UTC, jpwhite4 commented on classes/Models/Services/Tokens.php
> +                // post parameter. Here the value will be in the form: `Bearer: <token>`
```suggestion
                // post parameter. Here the value will be in the form: `Bearer <token>`
```
I thought that there isn't a colon between the Bearer and the value - please confirm

2023-03-08 18:46 UTC, jpwhite4 approved these changes

2023-03-08 18:59 UTC, merged