WIP: Refactor integration tests.
ubccr/xdmod pull request #1706
Opened 2023-03-23 21:16 UTC by aaronweeden

## Description

This is a work in progress not yet ready for review.

## Motivation and Context

## Tests performed

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2023-04-27 14:00 UTC, jpwhite4 submitted a review, later dismissed
I'm ok with these changes. Please ask Ryan to also weigh in since he is working on some test updates too.

2023-04-27 14:16 UTC, ryanrath requested changes
Hi Aaron, so a few comments, questions about the changes here. Let's go ahead and schedule a time where we can get together and chat about things.

2023-04-27 14:16 UTC, ryanrath commented on tests/integration/lib/BaseTest.php
> +    private function loadRawJsonFile($file, $validationType) {
Would using the `Configuration\Configuration` class work here? It does support json w/ $ref & $extends ( and also comment lines which is kind of nice ).

2023-04-27 14:16 UTC, ryanrath commented on tests/integration/lib/BaseTest.php
> +    private static function resolveRemoteSchemaRefs($obj, $schemaDir)
Same as above re: using `Configuraiton\Configuration`

2023-04-27 14:16 UTC, ryanrath commented on tests/integration/lib/BaseTest.php
> +    private static function resolveExternalFilePath($parentPath, $path)
and again re: `Configuration\Configuration`

2023-04-27 14:16 UTC, ryanrath commented on tests/integration/lib/Controllers/UserControllerProviderTest.php
> +    public function testAPITokensCRD($role)
Let's talk about this & BaseTest.php

2023-05-02 21:41 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +        } else {
Good idea, done!

2023-05-02 21:42 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +     * Perform an HTTP request and possibly make assertions about the
Good idea, done!

2023-05-02 21:42 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +    public function validateJson(
Done

2023-05-02 21:42 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +        if ('exact' === $validationType) {
Good idea, done!

2023-05-02 21:43 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +                $a = json_encode($actualObject);
From my reading and testing of their code, it seems we can't get much better than `$e->getMessage()`.

2023-05-02 21:46 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +            if (isset($object['$extends'])) {
There isn't a good reason; I've replaced this code with using the `Configuration` class.

2023-05-02 21:46 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +    private function loadRawJsonFile($file, $validationType) {
Good idea, done!

2023-05-02 21:46 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +    private static function resolveRemoteSchemaRefs($obj, $schemaDir)
Good idea, done!

2023-05-02 21:47 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +    private static function resolveExternalFilePath($parentPath, $path)
Good idea, done!

2023-05-02 21:47 UTC, aaronweeden commented on tests/integration/lib/Controllers/UserControllerProviderTest.php
> +    public function testAPITokensCRD($role)
Thanks for the review; I've committed some refactorings based on your suggestions here and during our in-person meeting.

2023-05-12 17:48 UTC, ryanrath reviewed
Just a few quick questions.

2023-05-12 17:48 UTC, ryanrath commented on tests/integration/lib/TestHarness/TokenAuthTest.php
> +abstract class TokenAuthTest extends BaseTest
I would recommend moving this class to `integration/lib` so that it can be found along side`BaseTest.php`. Other than that 👍

2023-05-12 17:48 UTC, ryanrath commented on tests/integration/lib/Rest/WarehouseExportControllerProviderTest.php
> +    private static $TEST_GROUP = 'integration/rest/warehouse/export';
What necessitated the change from `const` to `private static`?

2023-05-12 17:55 UTC, ryanrath approved these changes

2023-05-12 20:07 UTC, aaronweeden commented on tests/integration/lib/TestHarness/TokenAuthTest.php
> +abstract class TokenAuthTest extends BaseTest
Good idea, done!

2023-05-12 20:07 UTC, aaronweeden commented on tests/integration/lib/Rest/WarehouseExportControllerProviderTest.php
> +    private static $TEST_GROUP = 'integration/rest/warehouse/export';
Change was unnecessary, reverting.

2023-05-12 21:33 UTC, ryanrath approved these changes

2023-05-12 21:33 UTC, ryanrath approved these changes

2023-05-15 14:45 UTC, merged