Create REST endpoints for getting raw data.
ubccr/xdmod pull request #1721
Opened 2023-04-20 17:25 UTC by aaronweeden

## Description

This introduces two new REST endpoints, both of which require a valid [API token](https://github.com/ubccr/xdmod/pull/1695) to access:
- `/rest/warehouse/raw-data` — this endpoint responds to `GET` requests, accepts the following query parameters, and responds with a JSON object containing the relevant rows of raw data from the data warehouse and the list of corresponding field labels. Parameters:
    - `start_date` — start date of requested data.
    - `end_date` — end date of requested data.
    - `realm` — data realm to query.
    - `fields` — list of identifiers of fields to get.
    - `filters` — mapping of dimension identifiers to their possible values. Results will only be included whose values for each of the given dimensions match one of the corresponding given values.
    - `offset` — starting row index.
- `/rest/warehouse/raw-data/limit` — this endpoint responds to `GET` requests and responds with a JSON object containing the maximum number of rows that can be returned in a single response from the `raw-data` endpoint. This value is specified in `portal_settings.ini` under the `datawarehouse` section as `rest_raw_row_limit` (default 10000).

In the process, this changes `BatchDataset` to be able to be constructed with specified fields, a limit, and an offset.

This also deletes some unused variables.

This includes a merge of the [PR that updates the HTTP responses for API token requests](https://github.com/ubccr/xdmod/pull/1720).

## Motivation and Context

These endpoints are used by the [Python data analytics framework](https://github.com/ubccr/xdmod-python).

## Tests performed

This includes a merge of the [refactored integration tests](https://github.com/ubccr/xdmod/pull/1706) and adds integration tests for the new endpoints.

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2023-05-15 15:38 UTC, jpwhite4 requested changes

2023-05-15 15:38 UTC, jpwhite4 commented on classes/Rest/Controllers/WarehouseControllerProvider.php
> +        if ('SUPREMM' === $params['realm']) {
Ideally we shouldn't hardcode optional module information into the core XDMoD. The rawstatistics file can be used if we need a realm-specficit configuation.

2023-05-18 14:39 UTC, jpwhite4 requested changes

2023-05-18 14:39 UTC, jpwhite4 commented on classes/Rest/Controllers/WarehouseControllerProvider.php
> +        $this->getStringParam($request, 'querygroup', false, self::_DEFAULT_QUERY_GROUP);
This seems odd to me. Please can you check this change is what you intended to do.

2023-05-18 14:58 UTC, aaronweeden commented on classes/Rest/Controllers/WarehouseControllerProvider.php
> +        $this->getStringParam($request, 'querygroup', false, self::_DEFAULT_QUERY_GROUP);
phpcs caught that `$queryGroup` was an unused variable; it appears it became unused in the commit https://github.com/ubccr/xdmod/commit/b72a5875f6218fd229303145c7e60919b5a73a80 and was never removed. Since there seem to be no useful side effects to this call to `getStringParam()`, I am going to remove the line all together.

2023-05-18 15:53 UTC, jpwhite4 approved these changes

2023-05-19 16:00 UTC, merged