Integrate Plotly JavaScript for Job Viewer Tab
ubccr/xdmod pull request #1729
Opened 2023-05-19 19:36 UTC by aestoltm

## Description

**Timeseries Charts:**
- Timeseries charts are now rendered Plotly js charts instead of HighCharts

**Analytic Charts:**
- Analytic charts are now rendered with Plotly js instead of Highcharts
- Color brightness is slightly different than Highcharts. 

**Peer Charts (Gantt Charts):**

- No official support for gantt charts in Plotly js therefore rendered charts with Plotly shapes and added an underlying scatter plot due to shapes not supporting Plotly events and tooltips. Two other implementations I explored where using horizontal bar charts and box plot charts however the current implementation matches the highcharts version the best.

**Timeseries Drilldown:**
- Adjusted `plotly_click` in `ChartPanel.js` to grab the nodeid of the trace's data point selected for drilldown redirect.
- Adjusted how drilldown works in `GanttChart.js` to include the click event information in each data point and then when `plotly_click` fires `action: 'show'` is added to the click event info and is encoded for the drilldown redirect.

**Export:**
- Updated selector in `chrome-helper.js` to the div in `plotly_template.html`
- Updated layout for export chart to Plotly equivalent in `chartImageResponse()` in `classes/Rest/Controller/WarehouseControllerProvider.php` 
- Updated `charting.php` to grab file content from `plotly_template.html`
- Updated `highcharts_template.html` to `plotly_template.html`. Uses layout and data given from `charting.php` to draw chart a div. 
 
**Known Issues/TODO**
- Puppeteer evaluate call to the div's innerHTML in `plotly_template.html` throws a `Xml Parsing Error: No Root Element Found`. Have doubled checked all files related to exporting and have not yet found the culprit for why the JavaScript in `plotly_template.html`  seems to not be executing. 
- Fix chart responsiveness. Originally charts would not resize on window resize. Tested adding the config `responsive: true` to all chart types but this caused the chart to not appear until resize. Currently charts are responsive to window resize, however, timeseries chart responsiveness will intermittently break when zooming in on a plot.  
- Fix text cutoff on error text for when there are more than four analytic charts. Plotly does not support any word wrapping, therefore, we can add a [wordwrap](https://github.com/75lb/wordwrapjs) library as this most likely will be needed for when updating other modules with Plotly js.
- Optimize `plotly_hover` and `plotly_unhover` that mimics highcharts point hover events. Currently, not included with the PR but during testing the events crashed the webpage if hovering over charts with many overlapping traces. **Note:** this issue may be included in a future PR as it does not impact functionality

## Motivation and Context

Currently, Highcharts requires a license to be purchased which is solved by using Plotly js an open-source library.

## Tests performed

- Added test cases in `xdmod-supremm` for changes made to Job Viewer
- Performed GUI testing by visually comparing production and dev environment charts.

**TODO**
- Add test cases for exporting Plotly charts
- Add a button on Job Viewer Tab to redirect the reviewer to a random job with timeseries data. 

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2023-05-19 20:26 UTC, jpwhite4 commented on background_scripts/chrome-helper/chrome-helper.js
> +    const innerHtml = await page.evaluate(() => document.querySelector('.plotly').innerHTML);
You can't change this - it will break image export for the rest of XDMoD.

2023-05-19 20:27 UTC, jpwhite4 commented on classes/Rest/Controllers/WarehouseControllerProvider.php
> +        /*if (strpos($data['schema']['units'], '%') !== false) {
Please don't add commented code - I'm sure the linter has already complained about this!

2023-05-19 20:28 UTC, jpwhite4 commented on html/gui/js/modules/job_viewer/AnalyticChartPanel.js
> +	    console.log("new annontation");
Please don't add console.log() statements (by all means use them when debugging - but not in the final code that gets reviewed).

2023-05-19 22:11 UTC, jpwhite4 commented on html/gui/js/modules/job_viewer/ChartPanel.js
> +/*
What is the new object lifecycle? Before we explicitly called destroy on highcharts charts to free up memory when the tab was closed. How does it work now in your code?

2023-05-19 22:15 UTC, jpwhite4 commented on html/gui/js/modules/job_viewer/ChartTab.js
> +            Plotly.newPlot(this.id, [], {});
How come you create an empty Plotly plot here?

2023-05-19 22:15 UTC, aestoltm commented on html/gui/js/modules/job_viewer/ChartPanel.js
> +/*
`Plotly.purge(graphDiv)` is supposed to be called here. I will add that to destroy.

2023-05-19 22:20 UTC, aestoltm commented on html/gui/js/modules/job_viewer/ChartTab.js
> +            Plotly.newPlot(this.id, [], {});
This is not needed here and will be removed. This was added when I was trying to understand ChartTab.js and GanttChart.js

2023-05-22 14:25 UTC, eiffel777 requested changes

2023-05-22 14:25 UTC, eiffel777 commented on html/gui/js/modules/job_viewer/JobViewer.js
> +                console.log(test[test.length-1]);
Is this section just some debugging code that wasn't removed before committing? It looks like the only changes to this file are basically console.log statements.

2023-05-22 14:25 UTC, eiffel777 commented on classes/Rest/Controllers/WarehouseControllerProvider.php
> +		'showarrow' => false
This is very nitpicky but it looks like there is differing indentation in a couple of spots in this file. It would be better if there was uniform indentation. The linter might be picking this up but I'm not sure.

2023-05-22 14:25 UTC, eiffel777 commented on html/gui/js/modules/job_viewer/GanttChart.js
> +  	    console.log(record);
More console.log statements that should be removed.

2023-06-05 18:21 UTC, jpwhite4 commented on background_scripts/chrome-helper/chrome-helper.js
> +    const highchartInnerHtml = await page.evaluate(() => document.querySelector('.highcharts-container').innerHTML);
Suggest that you make the selector string a command line parameter. Something like '--selector' then the helper will not have to hardcode the container string name,

2023-06-23 18:24 UTC, ryanrath reviewed
Just a couple of questions

2023-06-23 18:24 UTC, ryanrath commented on html/gui/js/modules/job_viewer/AnalyticChartPanel.js
> +            this._DEFAULT_CONFIG.layout.images = errorImage;
I'm still making my way though the rest of the PR, but does the altering of `this._DEFAULT_CONFIG` have an effect on other instantiations of AnalyticChartPanel? Was that intended? I was just checking out what we did before which kind of looks like: 
- `Ext.apply(this.chartOptions, this._DEFAULT_CONFIG.chartOptions);` 
- `this.colorSteps = Ext.apply(this.colorSteps || [], this._DEFAULT_CONFIG.colorSteps );`

So we were essentially using it to provide the defaults and then further updating `this.chartOptions` or `this.colorSteps` if needed before using. 

Instead of marking each of the lines for this one I'll just list them here: 
- 252 -> 257
- 272
- 289

2023-06-23 19:18 UTC, aestoltm commented on html/gui/js/libraries/PlotlyUtilities.js
> +            + color + ';>●</span> ' + record.data.series[sid].name + ': <b>%{y:}</b> <extra></extra>',
I will fix that. I have not been able to find anything yet that states Plotly JS html encodes the hovertemplate beforehand.

2023-06-23 19:27 UTC, aestoltm commented on html/gui/js/modules/job_viewer/AnalyticChartPanel.js
> +            this._DEFAULT_CONFIG.layout.images = errorImage;
This was not intended and should be changed to how it worked before. Fixing this should also clean up the resize handler for Analytic charts because the plot will have independent layouts.

2023-06-30 14:29 UTC, jpwhite4 commented on classes/Rest/Controllers/WarehouseControllerProvider.php
>          $axisTitleFontSize = ($settings['font_size'] + 12) . 'px';
How come this code was left in but the rest of the setting transformation code was moved? Is there something different about the axis font sizes?

2023-06-30 14:33 UTC, jpwhite4 commented on html/gui/js/modules/job_viewer/AnalyticChartPanel.js
> +            this.chart = Plotly.newPlot(this.id, [], this._DEFAULT_CONFIG.layout, this._DEFAULT_CONFIG.config);
Does it cause problems passing the same configuration objects to multiple plotly instances? I naively would have done a deep copy on the DEFAULT_CONFIG objects and then passed the copy into the plotly instance.

2023-06-30 14:37 UTC, jpwhite4 commented on html/gui/js/modules/job_viewer/AnalyticChartPanel.js
> +            this._DEFAULT_CONFIG.layout.annotations = errorText;
I don't think it is a good idea to be editing the DEFAULT_CONFIG object. it can hardly be a portal-wide default if it changes accordiong to the state of an individual chart

2023-06-30 14:37 UTC, jpwhite4 commented on html/gui/js/modules/job_viewer/AnalyticChartPanel.js
> +            this._DEFAULT_CONFIG.layout.plot_bgcolor = chartColor.bg_color;
Same comment as above - not a good idea to edit the default that is shared among all charts.

2023-07-05 20:28 UTC, ryanrath reviewed
LGTM. I"m good to merge once Joe has a look.

2023-07-05 21:33 UTC, jpwhite4 commented on libraries/charting.php
> +    if ($isPlotly){
Very minor point: if the chart is plotly then the code will open the file called highchart_template.html then allocate memory, then copy the contents of the file into memory, then delete the memory. Needless to say there is no point using cpu cycles to read the highchart_template file when in plotly mode.

Don't need to change this for this pull request. But should address this in the next set of code changes.

2023-07-05 21:35 UTC, jpwhite4 approved these changes

2023-07-05 22:33 UTC, merged