Migrated User Manual from Docs to Sphinx
ubccr/xdmod pull request #1744
Opened 2023-07-19 19:23 UTC by rorymcclenahan

## Description
- Migrate the user manual to the version control and is now built using Sphinx instead of Docs. The manual is now built using Sphinx to automatically generate static web pages from restructured text (rst).
- Created a Sphinx role extension, called only, to help differentiate between the different versions of XDMoD.
- Remove existing portal_settings.ini reference to user manual and replaced with relative link in CCR.js
<img width="1102" alt="User Manual Home Page" src="https://github.com/ubccr/xdmod/assets/98715020/1298ae4f-2896-413e-9957-354d09a76f7a">

## Motivation and Context
Migrating the user manual will allow us to include the user manual under the version control and simplify the build process to generate the user manual. It can now be edited directly on GitHub, and it reduces maintainability of the user manual.

## Tests performed
All the automated tests for a fresh install of rocky Linux 8

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2023-08-11 18:49 UTC, jpwhite4 commented on user_manual_builder/conf.py
> +release = '11.0'
Don't hard code this version number - instead it should be obtained from the contents of the build.json file (which is the autoritative source.

2023-08-11 18:54 UTC, jpwhite4 requested changes
You changed the portal_settings.ini configuration options. You also need to update the documentation about the portal_settings configuration options in the docs/configuration.md file.

2023-08-11 18:54 UTC, jpwhite4 commented on user_manual_builder/conf.py
> +release = '11.0'
Don't hard code this version number - instead it should be obtained from the contents of the build.json file (which is the autoritative source).

2023-08-11 18:54 UTC, jpwhite4 commented on user_manual_builder/conf.py
> +html_logo = 'media/image43.png'
Please can you change this image name to something that describes the image content. For example, if this is the XDMoD logo then change the name to `xdmod_logo.png`

2023-08-11 18:56 UTC, jpwhite4 commented on user_manual_builder/conf.py
> +release = '11.0'
Similarly, I suggest dynamically generating the year in the copyright rather than hardcoding

2023-08-11 18:57 UTC, jpwhite4 commented
Please remove the "edit in github" link.

2023-08-11 19:05 UTC, jpwhite4 commented
Please can you also add a test in the validate script (https://github.com/ubccr/xdmod/blob/xdmod10.5/tests/ci/validate.sh) that confirms that the manual was installed correctly.

2024-02-08 18:29 UTC, jpwhite4 requested changes

2024-02-08 18:29 UTC, jpwhite4 commented on tests/ci/bootstrap.sh
> +python3 -m pip install imagehash==4.2.1
```suggestion
pip3 install imagehash==4.2.1
```

2024-02-08 18:29 UTC, jpwhite4 commented on tests/regression/lib/Controllers/UsageChartsTest.php
> +                throw new \Exception("imagehash returned $retval stderr='$err'");
Prefer this to be in a different pull request.

2024-02-08 18:41 UTC, jpwhite4 requested changes

2024-02-08 18:41 UTC, jpwhite4 commented on html/gui/js/CCR.js
> +                const userManualSectionName = tabPanel.getActiveTab().userManualSectionName;
Need to check if tabPanel is defined before dereferencing it.

2024-02-09 13:59 UTC, connersaeli commented on html/gui/js/CCR.js
> +                const userManualSectionName = tabPanel.getActiveTab().userManualSectionName;
See `html/gui/js/CCR.js` for resolution

2024-02-09 15:08 UTC, connersaeli commented on tests/ci/bootstrap.sh
> +python3 -m pip install imagehash==4.2.1
https://github.com/ubccr/xdmod/pull/1744/commits/cac9280eb42f5095fef229ad788f1c8df55b1dd3

2024-02-09 15:21 UTC, connersaeli commented on tests/regression/lib/Controllers/UsageChartsTest.php
> +                throw new \Exception("imagehash returned $retval stderr='$err'");
Reverted: https://github.com/ubccr/xdmod/pull/1744/commits/cac9280eb42f5095fef229ad788f1c8df55b1dd3
Separate PR: https://github.com/ubccr/xdmod/pull/1819

2024-05-08 19:55 UTC, merged