Remove jQuery dependency
ubccr/xdmod pull request #1756
Opened 2023-08-09 22:58 UTC by aestoltm

## Description

Removing jQuery dependency by replacing `jQuery.extend()` with solutions provided with modern browsers. This PR is a continuation of PR #1542.

## Motivation and Context

jQuery is a large dependency that we use very sparingly. 

## Tests performed

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2023-09-08 14:43 UTC, jpwhite4 commented on html/gui/js/HighChartWrapper.js
> +// Taken from: https://github.com/HubSpot/YouMightNotNeedjQuery
Please can you add the license info about this function into the comments too - I think you said it was MIT license?

2023-10-16 20:11 UTC, aestoltm commented on html/gui/js/HighChartWrapper.js
> +// Taken from: https://github.com/HubSpot/YouMightNotNeedjQuery
Updated license information in NOTICE, notices.md, and the comment mentioned here.

2023-10-16 20:49 UTC, jpwhite4 commented on html/gui/js/HighChartWrapper.js
> +// Taken from: https://github.com/HubSpot/YouMightNotNeedjQuery, which
I think this function belongs with the other utility functions in CCR.js. Seems to me a file called 'HighChartWrapper' should just contain functions related to wrapping highcharts.

2023-10-16 20:54 UTC, jpwhite4 requested changes

2023-10-16 20:54 UTC, jpwhite4 commented on html/gui/js/AddDataPanel.js
> +            var currentFilters = { ...{}, ...this.record.data.filters }; // eslint-disable-line
Please don't disable eslint for one line - either the line is good and the rule can be added to eslint or the line is bad in which case don't do it!

2023-10-18 17:59 UTC, aestoltm commented on html/gui/js/HighChartWrapper.js
> +// Taken from: https://github.com/HubSpot/YouMightNotNeedjQuery, which
Moved to CCR.js with the other utils functions

2023-10-18 18:00 UTC, aestoltm commented on html/gui/js/AddDataPanel.js
> +            var currentFilters = { ...{}, ...this.record.data.filters }; // eslint-disable-line
With updates to xdmod-qa these lines should now be parsed correctly without needing to disable them.

2024-05-10 17:54 UTC, jpwhite4 requested changes

2024-05-10 17:54 UTC, jpwhite4 commented on html/gui/js/modules/Summary.js
> -                    data: []
This looks like a mistake or a code change for a different purpose. Please can you double check.

2024-05-10 17:54 UTC, jpwhite4 commented on html/gui/js/modules/Usage.js
> +                            var chartDiv = document.getElementById(chartOptions.renderTo);
Please can you double check that this should be changed here.

2024-05-10 17:54 UTC, jpwhite4 commented on html/gui/js/modules/Usage.js
> +                                chartOptions = XDMoD.utils.deepExtend({}, baseChartOptions, chartOptions);
The function arguments are in a different order here. Please can you check this is intended (elsewhere you have kept the same order).

2024-05-10 17:54 UTC, jpwhite4 commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                                    var found = false;
```suggestion
                                    let found = false;
```

2024-05-10 18:32 UTC, aestoltm commented on html/gui/js/modules/Summary.js
> -                    data: []
This was leftover from the initial implementation of the Plotly conversion when I was trying to figure out a timing issue with the relayout events. jQuery the empty data array would not overwrite the data field in the target object. However, the native JS approach will overwrite the data loaded in from `chartOptions = chartRecords[0].get('hc_jsonstore'); ` when called with the original ordering  `chartOptions = XDMoD.utils.deepExtend({}, chartOptions, baseChartOptions);`. We want to keep the original ordering but remove the unnecessary empty data array here and in `Usage.js.`

2024-05-14 19:50 UTC, jpwhite4 approved these changes

2024-05-14 23:03 UTC, merged