Add pearc23 access paper
ubccr/xdmod pull request #1775
Opened 2023-09-13 13:31 UTC by eiffel777

Adding the PEARC23 ACCESS Paper to the publications list.

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2023-09-13 14:00 UTC, connersaeli submitted a review, later dismissed

2023-09-13 17:31 UTC, jpwhite4 commented on html/about/publications.html
> +        ser PEARC ’23 July 23–27, 2023, Portland, OR, USA. Association for Computing Machiinery, New York, NY, USA, 4 pages.
```suggestion
        ser PEARC ’23 July 23–27, 2023, Portland, OR, USA. Association for Computing Machinery, New York, NY, USA, 4 pages.
```

2023-09-13 17:32 UTC, jpwhite4 requested changes
See inline suggestions

2023-09-14 20:20 UTC, jpwhite4 approved these changes

2023-10-12 14:36 UTC, merged