Add Resource Specifications realm statistics and groupby's
ubccr/xdmod pull request #1799
Opened 2023-12-14 16:42 UTC by eiffel777

This PR adds the Resource Specifications realm. There are 16 statistics and 4 group by's

### Statistics
- CPU Hours: Total
- CPU Hours: Allocated
- GPU Hours: Total
- GPU Hours: Allocated
- CPU Node Hours: Total
- CPU Node Hours: Allocated
- GPU Node Hours: Total
- GPU Node Hours: Allocated
- Average Number of CPU Nodes: Total
- Average Number of CPU Nodes: Allocated
- Average Number of GPU Nodes: Total
- Average Number of GPU Nodes: Allocated
- Average Number of CPU Cores: Total
- Average Number of CPU Cores: Allocated
- Average Number of GPU Cores: Total
- Average Number of GPU Cores: Allocated

### Group By's
- Resource
- Resource Type
- Service Provider
- Resource Allocation Type

### Changes to resource specifications aggregation:
The aggregation was changed for CPU/GPU cores available and CPU/GPU nodes available to calculate the number of nodes/cores available for a time period times the number of days for that time period. A wallduration column was added that holds how long a resource specification existed for a time period, in seconds. This helps with calculating the average statistics.

### Other Changes:
- configuration/etl/etl_tables.d/common/staging/resource-type-realms.json 
       Changed realm column to varchar(255) to allow for longer realm name.
- configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_.json
- configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
        Changed column resource_id to record_resource_id. This matches the resource column name used in `./datawarehouse.d/ref/group-by-common.json` and allows us to use those group by definitions for the Resource and Resource Type group bys.
- configuration/etl/etl_tables.d/resource_specifications/resourcespecs_fact_by_day_resourcespecslist.json
         Renamed to `resourcespecsfact_by_day_resourcespecslist.json` to match name convention of other similar files.
 `configuration/datawarehouse.d/ref/Cloud-statistics.json`
          changed record_id reference to new record_resource_id column and changed resource specs table alias to be consistent with the alias in other places.

## Tests performed
Tested in docker

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2023-12-18 21:03 UTC, aaronweeden requested changes
To increase test coverage, I would suggest making one or more of the test resources in `tests/ci/scripts/xdmod-setup-jobs.tcl` have values for `percent_allocated` and one or more have multiple resource specifications.

I would also suggest updating `tests/regression/lib/Rest/WarehouseRawDataTest.php` to add a `resourcespecifications` section to `getRawDataProvider`.

It looks like `xdmod-supremm` and `xdmod-appkernels` will need `resourcespecifications` added to the `XDMOD_REALMS` in `.circleci/config.yml`.

2024-01-09 14:33 UTC, eiffel777 commented on configuration/datawarehouse.d/ref/Resourcespecs-statistics.json
> +        "unit": "Hours"
These statistics have been updated to a unit that matches other statistics in other realms so they show on the same axis on the plots. For example, the unit for this statistic is now CPU Hour since that is the same unit used for the CPU Hours: Total statistic in the Jobs realm. If you have both of these statistics on the same plot there will only be one axis instead of two.

2024-01-09 14:44 UTC, eiffel777 commented on configuration/datawarehouse.d/ref/Resourcespecs-statistics.json
> +        "formula": "COALESCE(SUM(agg.cpu_nodes_available) / (SUM(agg.wallduration) / 86400), 0)",
I believe I have the right formula for these average statistics now. The formula I have now is the sum of whatever is being counted(cpu core, gpu core, etc) divided by the number of days in the aggregation unit being looked at.

2024-01-12 16:03 UTC, eiffel777 commented on configuration/datawarehouse.d/ref/Resourcespecs-statistics.json
> +        "formula": "COALESCE(SUM(agg.cpu_nodes_available), 0) * 24",
I added a new field in the aggregation that takes into account the percent allocated. This field is used for the node hour statistics now.

2024-02-01 22:39 UTC, aaronweeden requested changes

2024-02-09 16:14 UTC, eiffel777 commented on configuration/etl/etl_action_defs.d/resource_specifications/resource_specs_aggregation.json
> +            "gpu_node_time_available": "COALESCE(SUM((${resource_specs_duration}) * r.gpu_node_count * ra.percent / 100.0), 0)",
`cpu_cores_available` is the sum of cores per day over the time period being aggregated. For example, a resource with 10 cores the `resourcespecsfact_by_day` table would have 10 for each day and `resourcespecsfact_by_month` would have 300 for a month with 30 days. This column and the others you mentioned are used for the average statistics in the resource specs realm. 

I would also note that these have been renamed now with the addition of statistics for the total number of cpus, gpus, etc and allocated number of cpus, gpus, etc.

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of CPU cores available to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of CPU cores available during a time period, including those not allocated through ${ORGANIZATION_NAME}"
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of GPU cores aavailable to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of GPU cores available during a time period, including those not allocated through ${ORGANIZATION_NAME} "
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of GPU cores aavailable to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of GPU cores available to be allocated through ${ORGANIZATION_NAME} during a time period"
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of CPU nodes available to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of CPU nodes available during a time period, including those not allocated through ${ORGANIZATION_NAME}"
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of GPU nodes available to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of GPU nodes available during a time period, including those not allocated through ${ORGANIZATION_NAME}"
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of GPU nodes available to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of GPU nodes available during a time period, including those not allocated through ${ORGANIZATION_NAME} "
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of CPU core seconds available to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of CPU core seconds available during a time period, including those not allocated through ${ORGANIZATION_NAME}"
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of GPU core seconds available to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of GPU core seconds available during a time period, including those not allocated through ${ORGANIZATION_NAME}"
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of CPU node seconds available to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of CPU node seconds available during a time period, including those not allocated through ${ORGANIZATION_NAME} "
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "name": "total_core_time",
```suggestion
                "name": "total_cpu_core_time",
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "name": "allocated_core_time",
```suggestion
                "name": "allocated_cpu_core_time",
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "name": "total_gpu_time",
```suggestion
                "name": "total_gpu_core_time",
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "name": "allocated_gpu_time",
```suggestion
                "name": "allocated_gpu_core_time",
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day.json
> +                "comment": "FACT: Number of GPU node seconds available to be allocated through ${ORGANIZATION_NAME} during a time period"
```suggestion
                "comment": "FACT: Number of GPU node seconds available during a time period, including those not allocated through ${ORGANIZATION_NAME} "
```

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_.json
See comments in `resourcespecsfact_by_day.json`.

2024-02-09 17:46 UTC, aaronweeden commented on configuration/etl/etl_action_defs.d/resource_specifications/resource_specs_aggregation.json
> +            "gpu_node_time_available": "COALESCE(SUM((${resource_specs_duration}) * r.gpu_node_count * ra.percent / 100.0), 0)",
Currently, the formula for `total_core_time` is:
```
COALESCE(SUM((${resource_specs_duration}) * r.cpu_processor_count), 0)
```
which would be in core seconds, and the formula for `total_cpu_cores` is:
```
COALESCE(SUM((${resource_specs_duration}) * r.cpu_processor_count) / 86400, 0)
```
which is the same as `total_core_time / 86400` and would be in core days. They are both measures of core time. This is why in the statistic for `total_avg_number_of_cpu_cores` you have to divide by the time (i.e., number of days, i.e., `seconds / 86400`):
```
COALESCE(SUM(agg.total_cpu_cores) / ((SELECT SUM(seconds) FROM modw.${AGGREGATION_UNIT}s WHERE FIND_IN_SET(id, GROUP_CONCAT(DISTINCT ${DATE_TABLE_ID_FIELD})) <> 0) / 86400), 0)
```

In that statistic, if you change `total_cpu_cores` to `total_core_time`, then you don't have to divide by `86400` at the end, and the `total_cpu_cores` column isn't needed.

2024-03-04 17:42 UTC, aaronweeden requested changes

2024-03-06 20:07 UTC, eiffel777 commented on tests/ci/bootstrap.sh
> +    sudo -u xdmod xdmod-build-filter-lists -r ResourceSpecifications
@aaronweeden Turns out xdmod-build-filter-lists isn't needed here. It's run in DataWarehouseInitializer.php when the resource specs aggregation is run. I have removed it.

2024-03-07 21:03 UTC, aaronweeden requested changes

2024-03-07 21:03 UTC, aaronweeden commented on configuration/datawarehouse.d/ref/Resourcespecs-statistics.json
> +        "formula": "COALESCE(SUM(agg.total_cpu_node_time) / (SELECT SUM(seconds) FROM modw.${AGGREGATION_UNIT}s WHERE FIND_IN_SET(id, GROUP_CONCAT(DISTINCT ${DATE_TABLE_ID_FIELD})) <> 0), 0)",
I'm not sure this is working for aggregate datasets; it seems to be averaging over the period the resources are available instead of the entire aggregation period. For example, in the Docker container, for an aggregate dataset from `2016-12-01` to `2016-12-31`, I would expect the average for all of Screwdriver to be `6709.68 = (9*4000 + 1*8000 + 4*12000 + 1*16000 + 5*20000) / 31`, but instead it is `10400 = (9*4000 + 1*8000 + 4*12000 + 1*16000 + 5*20000) / 20` (i.e., it is averaging over 20 days instead of 31 days).

2024-03-13 21:10 UTC, aaronweeden approved these changes
These and my previous comments can be addressed in separate PR(s) later.

2024-03-13 21:12 UTC, aaronweeden commented on configuration/datawarehouse.d/ref/Resourcespecs-statistics.json
> +        "formula": "COALESCE(SUM(agg.total_cpu_node_time) / (SELECT SUM(seconds) FROM modw.${AGGREGATION_UNIT}s WHERE FIND_IN_SET(id, GROUP_CONCAT(DISTINCT ${DATE_TABLE_ID_FIELD})) <> 0), 0)",
Greg and I spoke about how, in other places in XDMoD, it averages over the subset of the time range for which data is available, so we are going with the same thing here.

2024-03-13 21:13 UTC, aaronweeden commented on configuration/datawarehouse.d/ref/Resourcespecs-statistics.json
> +        "precision": 0,
So that it doesn't round up to the nearest integer which could be taken to mean there are more cores/nodes than there were.

2024-03-13 21:13 UTC, aaronweeden commented on configuration/etl/etl_tables.d/resource_specifications/resourcespecsfact_by_day_resourcespecslist.json
Greg and I talked about this being used for consistency with other realms.

2024-03-14 13:26 UTC, aaronweeden approved these changes

2024-03-14 13:27 UTC, merged

2024-03-14 13:27 UTC, aaronweeden commented on configuration/datawarehouse.d/ref/Resourcespecs-statistics.json
> +        "formula": "COALESCE(SUM(agg.total_cpu_node_time) / (LEAST((SELECT MAX(end_date_ts) FROM modw.resourcespecs WHERE FIND_IN_SET(resource_id, GROUP_CONCAT(DISTINCT agg.record_resource_id)) <> 0)
Greg let me know statistics don't support macros.