XDMoD 11.0 PHP8 Changes
ubccr/xdmod pull request #1806
Opened 2024-01-08 18:43 UTC by ryanrath

## Description

## Motivation and Context

## Tests performed

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2024-05-10 20:04 UTC, jpwhite4 requested changes

2024-05-10 20:04 UTC, jpwhite4 commented on .circleci/config.yml
> +      - image: tools-ext-01.ccr.xdmod.org/xdmod-10.5.0-x86_64:rockylinux8.5-0.3-php8
We need to test using the existing docker - the migration from php7 to php8 will need to be in a script that runs in circleci.

2024-05-10 20:04 UTC, jpwhite4 commented on tests/ci/samlSetup.sh
> +# Temporarily need to remove this line due to Assertions being removed in PHP8.
Is this really being Temporarily removed? The code looks like it is permanently removing it.

2024-05-16 14:43 UTC, ryanrath commented on .circleci/config.yml
> +          command: >
They're all in Silex / Symfony basically, some examples:
- `[15-May-2024 15:49:49 UTC] PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /usr/share/xdmod/vendor/silex/silex/src/Silex/ControllerResolver.php on line 43` 
- `[15-May-2024 15:49:49 UTC] PHP Deprecated:  Method ReflectionParameter::getClass() is deprecated in /usr/share/xdmod/vendor/symfony/http-kernel/Controller/ControllerResolver.php on line 113`
- `[15-May-2024 15:56:42 UTC] PHP Deprecated:  Function libxml_disable_entity_loader() is deprecated in /usr/share/xdmod/vendor/simplesamlphp/saml2/src/SAML2/DOMDocumentFactory.php on line 26`

2024-05-16 14:43 UTC, ryanrath commented on .circleci/config.yml
> +      - image: tools-ext-01.ccr.xdmod.org/xdmod-10.5.0-x86_64:rockylinux8.5-0.3-php8
This is addressed in the latest commits.

2024-05-16 14:45 UTC, ryanrath commented on tests/ci/samlSetup.sh
> +# Temporarily need to remove this line due to Assertions being removed in PHP8.
I intended `Temporarily` in this case to mean "until the the new REST stack goes in w/ an updated version of SimpleSAMLPHP that does not contain the Assertions code.`.

2024-05-16 15:26 UTC, ryanrath commented on classes/DB/PDODBMultiIngestor.php
> -        $pre_ingest_update_statements = array(),
I've updated the function signature per your recommendation, i.e. moved `$pre_ingest_update_statements` back to it's original location and removed the default value. I updated the child class constructor & they're usage in `Shredder.php` to take this into account.

2024-05-17 19:34 UTC, ryanrath commented on tests/ci/samlSetup.sh
> +# Temporarily need to remove this line due to Assertions being removed in PHP8.
I've updated the comment in the latest commit to clarify.

2024-05-20 15:25 UTC, jpwhite4 commented on .circleci/config.yml
> +          command: >
could we just filter out any deprecated warnings from the files in the xdmod/vendor directory instead? I don't want us to miss code changes that we need to do in our code.

2024-05-20 15:29 UTC, jpwhite4 commented on classes/ETL/Aggregator/pdoAggregator.php
> +        $periodSize = 1;
Is `1` the appropriate default value for periodSize? If aggregationPeriodList is empty then why is periodSize not 0. Similarly if aggregationPeriodList is at the end then the periodSize would be 0 too?

2024-05-20 15:31 UTC, jpwhite4 commented on docs/upgrade.md
> +### Server: EL7, XDMoD: 10.5, PHP: 7.2
EL7 is not php 7.2

2024-05-20 15:35 UTC, jpwhite4 commented on docs/upgrade.md
> +*NOTE: There may be some PHP Warning messages generated during this process, they can be safely ignored. Once the
You need to say what PHP warning are generated.

2024-05-20 15:35 UTC, jpwhite4 commented on docs/upgrade.md
> +The steps to accommodate this scenario are fairly straightforward:
```suggestion
The following steps should be used to update an XDMoD 10.5.0 instance running on Rocky Linux 8.
```

2024-05-20 15:37 UTC, jpwhite4 commented on docs/upgrade.md
> +*NOTE: There may be some PHP Warning messages generated during this process, they can be safely ignored. Once the
and when to expect to see such warning. - saying that all the warnings can be deregarded is likely to cause us problems when someone has a fatal error that they ignore

2024-05-20 15:42 UTC, jpwhite4 commented on docs/upgrade.md
> +Open XDMoD is now no longer bundled with any non-commercial licenses. The charting library used in Open XDMoD has changed from [Highcharts](https://www.highcharts.com/) to [Plotly JS](https://plotly.
```
Open XDMoD is now no longer bundled with any non-commercial licenses.
```
To be fair Open XDMoD has never been bundled with any licenses ever. It has, however, been bundled with software libraries that have licenses that have additional restrictions for commercial and governmental use.

2024-05-20 15:44 UTC, jpwhite4 commented on tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs.json
Please can you confirm this is correct? Seems odd to be adding an empty file here

2024-05-20 15:46 UTC, jpwhite4 commented on tests/ci/bootstrap.sh
> +        mv /etc/my.cnf.d/mariadb-server.cnf.rpmsave /etc/my.cnf.d/mariadb-server.cnf
This line seems unnecessary since the file is going to be overwritten 3 lines down on line 70.

2024-05-20 15:50 UTC, jpwhite4 commented on tests/ci/bootstrap.sh
> +        >/etc/my.cnf.d/mariadb-server.cnf
Why test for the file to exist before overwriting it? Under what conditions will the file not exist?

2024-05-20 16:01 UTC, jpwhite4 requested changes
see inline comments...

2024-05-20 19:01 UTC, ryanrath commented on .circleci/config.yml
> +          command: >
Yup, we now only filter out deprecated warnings for code in the vendor directory.

2024-05-20 19:16 UTC, ryanrath commented on tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs.json
I would agree, I think this must have been generated while I was testing early on in development. I'll go ahead and remove this file.

2024-05-20 19:57 UTC, ryanrath commented on docs/upgrade.md
> +### Server: EL7, XDMoD: 10.5, PHP: 7.2
It is if you have 10.5 installed. But if not, then yeah it's 5.4 by default.

2024-05-20 20:01 UTC, ryanrath commented on docs/upgrade.md
> +1. Install a fresh copy of XDMoD 10.5 on a new Rocky 8 server.
Most definitely. Yeah, I should have updated the `10.0.x installation` to be `10.5.0` and had another full entry for `10.0.x`

2024-05-20 20:25 UTC, ryanrath commented on docs/upgrade.md
> +*NOTE: There may be some PHP Warning messages generated during this process, they can be safely ignored. Once the
I've updated this w/ the specific warnings to look out for in the latest commit

2024-05-20 20:25 UTC, ryanrath commented on tests/ci/bootstrap.sh
> +        mv /etc/my.cnf.d/mariadb-server.cnf.rpmsave /etc/my.cnf.d/mariadb-server.cnf
Yup, it's removed in the latest

2024-05-20 20:26 UTC, ryanrath commented on tests/ci/bootstrap.sh
> +        >/etc/my.cnf.d/mariadb-server.cnf
no idea, testing has been removed in the lates

2024-05-20 20:26 UTC, ryanrath commented on tests/ci/bootstrap.sh
> +              pid-file=/run/mariadb/mariadb.pid" > /etc/my.cnf.d/mariadb-server.cnf
Yup, it's been updated in the latest.

2024-05-21 13:39 UTC, ryanrath commented on docs/upgrade.md
> +1. Install a fresh copy of XDMoD 10.5 on a new Rocky 8 server.
I've updated this in the latest commits, let me know if what I've done works.

2024-05-21 13:40 UTC, ryanrath commented on tests/artifacts/xdmod/regression/current/expected/reference/raw-data/jobs.json
This has been removed.

2024-05-22 17:42 UTC, jpwhite4 commented on tests/ci/samlSetup.sh
> +# Temporarily ( until the REST update goes in ) need to remove this line due to Assertions being removed in PHP8.
As per our conversation - confirm whether this step would always be needed and, if so, then do this in build.json so that the packaged files are correct.

2024-05-22 17:43 UTC, jpwhite4 commented on .circleci/config.yml
> +            sed -i 's/SimpleSAML_Error_Assertion::installHandler();//g' vendor/simplesamlphp/simplesamlphp/www/_include.php
As per our conversation - confirm whether this step is specfic to our ci build (if so then it is ok to leave here). If it is not circle-ci specific and is actually needed for the production software then do this in build.json so that the packaged files are correct.

2024-05-28 21:13 UTC, aaronweeden requested changes

2024-05-28 21:13 UTC, aaronweeden commented on tests/integration/lib/Rest/WarehouseExportControllerProviderTest.php
> +        $this->assertTrue(count($content['data']) === count($beforeContent['data']), 'Deleted IDs are in response');
Maybe this should use `array_diff` instead of just `count`?

2024-05-28 21:13 UTC, aaronweeden commented on tests/component/phpunit.xml.dist
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="true" bootstrap="bootstrap.php" colors="true" t
Having one attribute per line is a bit more readable.

2024-05-28 21:13 UTC, aaronweeden commented on tests/integration/phpunit.xml.dist
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="true" bootstrap="bootstrap.php" colors="true" t
Having one attribute per line is a bit more readable.

2024-05-28 21:13 UTC, aaronweeden commented on tests/regression/phpunit.xml.dist
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="true" bootstrap="bootstrap.php" colors="true" t
Having one attribute per line is a bit more readable.

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/phpunit.xml.dist
> +         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="true"
Having one attribute per line is a bit more readable.

2024-05-28 21:13 UTC, aaronweeden commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +     * @throws \PHPUnit\Framework\ExpectationFailedException If the test failed.
```suggestion
     * @throws SkippedTestError If the test is skipped.
     * @throws IncompleteTestError If the test is incomplete.
     * @throws ExpectationFailedException If the test failed.
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +            throw new \PHPUnit\Framework\SkippedTestError($fullTestName . ' intentionally skipped');
```suggestion
            throw new SkippedTestError($fullTestName . ' intentionally skipped');
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +        throw new \PHPUnit\Framework\SkippedTestError(
```suggestion
        throw new SkippedTestError(
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +            throw new \PHPUnit\Framework\SkippedTestError(
```suggestion
            throw new SkippedTestError(
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/DataWarehouse/Export/CsvFileWriterTest.php
> +use \PHPUnit\Framework\TestCase;
```suggestion
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/DataWarehouse/Export/FileWriterFactoryTest.php
> +use \PHPUnit\Framework\TestCase;
```suggestion
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/DataWarehouse/Export/JsonFileWriterTest.php
> +use \PHPUnit\Framework\TestCase;
```suggestion
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/DataWarehouse/Export/NullFileWriterTest.php
> +use \PHPUnit\Framework\TestCase;
```suggestion
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
> +use \PHPUnit\Framework\TestCase;
```suggestion
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
> +                    fn($obj) => json_decode(json_encodE($obj)),
```suggestion
                    fn($obj) => json_decode(json_encode($obj)),
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
> -                return array_map(array($this, 'arrayToStdClass'), $inputData);
Looks like `arraytoStdClass` no longer needs to be defined.

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/ETL/DbModel/TableTest.php
> +use \PHPUnit\Framework\TestCase;
```suggestion
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/OpenXdmod/Tests/Shredder/JobShredderBaseTestCase.php
> +use \PHPUnit\Framework\TestCase;
```suggestion
```

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/OpenXdmod/Tests/Shredder/LsfShredderTest.php
> -            ->with(new \PHPUnit_Framework_Constraint_ArraySubset($job));
Should this be reimplemented?

2024-05-28 21:13 UTC, aaronweeden commented on tests/unit/lib/OpenXdmod/Tests/Shredder/SlurmShredderTest.php
> -            ->with(new \PHPUnit_Framework_Constraint_ArraySubset(['job_name' => $jobName]));
Should this be reimplemented?

2024-05-29 18:23 UTC, ryanrath commented on tests/integration/lib/Rest/WarehouseExportControllerProviderTest.php
> +                $counts = [28, 16, 16 ];
no idea, but i'll remove it.

2024-05-29 19:17 UTC, ryanrath commented on tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
> +                    fn($obj) => json_decode(json_encodE($obj)),
lol, gotta love PHP not caring about case. This has been updated.

2024-05-29 19:18 UTC, ryanrath commented on tests/unit/lib/ETL/DbModel/ForeignKeyConstraintTest.php
> -                return array_map(array($this, 'arrayToStdClass'), $inputData);
*nod* It is being removed from the code, to be replaced with `fn($obj) => json_decode(json_encode($obj)),`

2024-05-30 13:26 UTC, ryanrath commented on tests/ci/samlSetup.sh
> +# Temporarily ( until the REST update goes in ) need to remove this line due to Assertions being removed in PHP8.
This has been added to `build.json` and I'm just removing it from `samlSetup.sh` now.

2024-05-30 13:30 UTC, ryanrath commented on tests/component/lib/Export/FileManagerTest.php
> -        $dataSet->method('rewind')->willReturn(null);
Honestly I don't remember. They've been re-added in the latest commits.

2024-05-30 13:30 UTC, ryanrath commented on tests/integration/lib/Controllers/ControllerTest.php
>          // and if that fails then just fallback to the full response body as is.
This has been updated in the latest commits.

2024-05-30 13:31 UTC, ryanrath commented on tests/integration/lib/Rest/WarehouseExportControllerProviderTest.php
> +            $this->assertTrue(count($requests) === count($content['data']), 'Data contains requests');
I've added a new composer dependency that re-adds the `assertArraySubset` functionality back into PHPUnit, and reverted these changes.

2024-05-30 13:31 UTC, ryanrath commented on tests/integration/lib/Rest/WarehouseExportControllerProviderTest.php
> +        $this->assertTrue(count($content['data']) === count($beforeContent['data']), 'Deleted IDs are in response');
I've added a new composer dependency that re-adds the `assertArraySubset` functionality back into PHPUnit, and reverted these changes.

2024-05-30 13:31 UTC, ryanrath commented on tests/component/phpunit.xml.dist
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="true" bootstrap="bootstrap.php" colors="true" t
I've reformatted to be more readable.

2024-05-30 13:31 UTC, ryanrath commented on tests/integration/phpunit.xml.dist
> +<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="true" bootstrap="bootstrap.php" colors="true" t
I've reformatted to be more readable.

2024-05-30 13:31 UTC, ryanrath commented on tests/unit/phpunit.xml.dist
> +         xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="true"
I've reformatted to be more readable.

2024-05-30 13:34 UTC, ryanrath commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +     * @throws \PHPUnit\Framework\ExpectationFailedException If the test failed.
I've standardized all of the instances of these `throws` clauses to `use Fully\Qualified\ExceptionClassName;` w/  and `@throws ExceptionClassName ....` for the areas you've identified.

2024-05-30 13:34 UTC, ryanrath commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +            throw new \PHPUnit\Framework\SkippedTestError($fullTestName . ' intentionally skipped');
I've standardized all of the instances of these `throws` clauses to `use Fully\Qualified\ExceptionClassName;` w/  and `@throws ExceptionClassName ....` for the areas you've identified.

2024-05-30 13:34 UTC, ryanrath commented on tests/regression/lib/TestHarness/RegressionTestHelper.php
> +            throw new \PHPUnit\Framework\SkippedTestError(
I've standardized all of the instances of these `throws` clauses to `use Fully\Qualified\ExceptionClassName;` w/  and `@throws ExceptionClassName ....` for the areas you've identified.

2024-05-30 13:35 UTC, ryanrath commented on tests/unit/lib/DataWarehouse/Export/CsvFileWriterTest.php
> +use \PHPUnit\Framework\TestCase;
I'm going to go ahead and leave this as `CsvFileWriterTest` extends from `TestCase`.

2024-05-30 13:35 UTC, ryanrath commented on tests/unit/lib/DataWarehouse/Export/FileWriterFactoryTest.php
> +use \PHPUnit\Framework\TestCase;
I'm going to go ahead and leave this as `FileWriterFactoryTest` extends from `TestCase`.

2024-05-30 13:36 UTC, ryanrath commented on tests/unit/lib/DataWarehouse/Export/JsonFileWriterTest.php
> +use \PHPUnit\Framework\TestCase;
I'm going to go ahead and leave this as `JsonFileWriterTest` extends from `TestCase`

2024-05-30 13:36 UTC, ryanrath commented on tests/unit/lib/DataWarehouse/Export/NullFileWriterTest.php
> +use \PHPUnit\Framework\TestCase;
I'm going to go ahead and leave this as `NullFileWriterTest` extends from `TestCase`

2024-05-30 13:37 UTC, ryanrath commented on docs/upgrade.md
> +*NOTE: You may be some PHP Warning messages generated during this process:*
This has been updated in the latest commits

2024-05-30 14:06 UTC, ryanrath commented on .circleci/config.yml
> +          command: yes '' | pecl install mongodb || true
So at one point during development `yes '' | pecl install mongodb` was returning a non-zero exit code due to not being able to add information php.ini. that doesn't seem to be the case anymore. I'll remove the extraneous `|| true`

2024-05-30 14:06 UTC, ryanrath commented on docs/upgrade.md
> +
Yup, this section has been updated to reference the steps below.

2024-05-30 14:07 UTC, ryanrath commented on .circleci/config.yml
> +              test `egrep -v "PHP Deprecated.*vendor\/.*" /var/log/php-fpm/www-error.log | wc -l` = 0;
Same as  my `xdmod-supremm` comment, just interested to see what the thought was in adding `\/` here.

2024-05-30 14:07 UTC, ryanrath commented on .circleci/config.yml
> +                  test `egrep -v "PHP Deprecated.*vendor\/.*|PHP Notice:  fread()" /var/log/php_errors.log | wc -l` = 0;
Same as  my `xdmod-supremm` comment, just interested to see what the thought was in adding `\/` here.

2024-05-30 14:07 UTC, ryanrath commented on tests/regression/lib/Controllers/MetricExplorerChartsTest.php
Yup, this has been updated.

2024-05-30 14:08 UTC, ryanrath commented on tests/component/lib/ETL/EtlOverseerTest.php
> +            $this->assertTrue(true);
Sure, it's been added / updated.

2024-05-30 14:22 UTC, ryanrath commented on .circleci/config.yml
> +          command: yes '' | pecl install mongodb || true
Or judging by the latest build failure it looks like we do need this. Specifically it returns 
```configuration option "php_ini" is not set to php.ini location
You should add "extension=mongodb.so" to php.ini
```
and exit code=141

2024-05-30 18:20 UTC, jpwhite4 commented on composer.json
> +        "phpoffice/phpword": "*",
Should this be a wildcard?  We had it pinned at a version that we knew worked.

2024-05-30 18:42 UTC, jpwhite4 requested changes
Looks like php 8.0 is not supported, so we can't switch to this.

2024-06-07 16:09 UTC, jpwhite4 commented on .circleci/config.yml
> +          name: Install PHP 8.0 and PHP module pre-reqs & an updated version of PHP Pear
```suggestion
          name: Install PHP 7.4 and PHP module pre-reqs & an updated version of PHP Pear
```

2024-06-10 15:24 UTC, jpwhite4 requested changes

2024-06-10 15:24 UTC, jpwhite4 commented on classes/ETL/DbModel/Entity.php
> +        if (!is_string($identifier)) {
Is this the safest way to handle this case? What scenarios exist where the quote function was called with a non string object? What was the object and what happened next?

2024-06-10 18:50 UTC, ryanrath commented on classes/ETL/DbModel/Entity.php
> +        if (!is_string($identifier)) {
It's probably not, I've updated this in the latest commit to throw an Exception.

2024-06-10 18:51 UTC, ryanrath commented on classes/ETL/DbModel/Entity.php
> +        if (!is_string($identifier)) {
So just some background, this code works fine in 7.2|7.4, but it was failing in 8.0 due to 8.X being more stringent about types.

2024-06-10 22:33 UTC, jpwhite4 approved these changes

2024-06-11 13:33 UTC, merged