Updated summary charts howto, added color palette howto.
ubccr/xdmod pull request #1818
Opened 2024-02-08 20:15 UTC by Macman1234

## Description
This PR changes the summary charts howto to use the Metrics Explorer json export function, and added more details about where summary charts are set from. The article is reorganized slightly to better flow sequentially through steps.
It also adds a new howto for how to set up `colors1.json` for custom colors. It adds both of these to the Howto root article and changes the styling of that article slightly.

## Motivation and Context
The [existing summary chart howto](https://open.xdmod.org/10.5/howto-summary-charts.html) explains the method for pulling chart JSON data out of the user database, which is cumbersome and not possible to do without administrator access.
The [user dashboard guide](https://open.xdmod.org/10.5/dashboard.html) has instructions on how to get the chart from Metric Dashboard directly, which works great for this use case with some modifications.
The existing howto also didn't include info about the roles.d/jobs.json field adding charts for logged-in users, which threw me off when trying this on my instance of Open XDMoD.

Currently there's no documentation on how to edit `colors1.json` - though it's mostly self-explanatory, it took me a bit to figure out how to get gradients working for different elements of a dataset. I figured some documentation might save people time if they're trying to do the same.

## Tests performed
I wasn't able to replicate the Jekyll/gh-pages setup that https://open.xdmod.org/10.5/ seems to run on, but I looked through these in a standard Markdown viewer and they look good. They match the formatting of other articles, and follow the [documentation conventions](https://open.xdmod.org/10.5/docs-conventions.html)

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2024-06-11 18:38 UTC, aestoltm requested changes

2024-06-11 18:38 UTC, aestoltm commented on docs/howto-summary-charts.md
> +`PREFIX/etc/roles.d/jobs.json` if you did a manual install) - to remove these default charts from
Just wanted to note that charts can be explicitly defined in multiple files in `roles.d/`. It might be more clear to hint that these other files can be customized (such as `roles.d/cloud.json`) not just `roles.d/jobs.json`.

2024-06-11 18:38 UTC, aestoltm commented on docs/howto-summary-charts.md
> +The export functionality from Metric Explorer does not, by default,
We are aware of the issues surrounding `global_filters` within the Summary tab. I have a minor suggestion that it may be more concise to mention that an empty `global_filters` field is required in the chart JSON due to a known issue

2024-06-19 19:28 UTC, Macman1234 commented on docs/howto-summary-charts.md
> +`PREFIX/etc/roles.d/jobs.json` if you did a manual install) - to remove these default charts from
After looking through the configuration files more, I've significantly rewrote this section of the article. I originally wrote it through the lens of "dang, just let me set my defaults!" rather than actually looking at where anything should/could go.

2024-06-19 19:29 UTC, Macman1234 commented on docs/howto-summary-charts.md
> +The export functionality from Metric Explorer does not, by default,
got it - changed the wording and I think it's clearer now, though I'm unsure if it's more concise.

2024-06-20 19:30 UTC, aestoltm requested changes
The changes you made look great. I just had a few minor suggestions about some wording for some parts related to `roles.d`.

I think you also have some linter errors for extra whitespace characters at the end of some lines.

2024-06-20 19:30 UTC, aestoltm commented on docs/howto-summary-charts.md
> +and in any `.json` file located in `roles.d` (`/etc/xdmod/roles.d/*.json` or `PREFIX/xdmod/roles.d/*.json` respectively).
```suggestion
and in some `.json` files located in `roles.d` (`/etc/xdmod/roles.d/` or `PREFIX/xdmod/roles.d/` respectively). The files that contain `+summary_charts` are typically organized into different realm configuration files such as `roles.d/jobs.json` and `roles.d/cloud.json`.
```
I just wanted to specify this because of `dashboard.json` and `statistics_format.json` in `roles.d/`.

2024-06-20 19:31 UTC, aestoltm commented on docs/howto-summary-charts.md
> +any files in `roles.d`. If `summary_charts` contains any charts, those override displaying any of the summary charts.
```suggestion
in `roles.d`. If `summary_charts` contains any charts, those override displaying any of the summary charts.
```

2024-06-21 02:12 UTC, Macman1234 commented
> The changes you made look great. I just had a few minor suggestions about some wording for some parts related to `roles.d`.

Applied! I was unaware XDMoD is looking for the specific realm `.json` files.

> I think you also have some linter errors for extra whitespace characters at the end of some lines.

Thanks for the catch! My linter was turned off - fixed now.

2024-06-24 19:08 UTC, aestoltm requested changes
After talking with some folks on the team, the 'best practice' for customizing the summary charts would be to create a new file within `roles.d/`. I apologize for any confusion from my previous suggestions. I added some new suggestions with this 'best practice' in mind.

Otherwise, there are a few linter errors on `howto-colors.md`. Once that is cleared up along with the suggestions everything should be good for merging!

2024-06-24 19:08 UTC, aestoltm commented on docs/howto-summary-charts.md
> +  has explicitly defined summary charts appended in `roles.d/jobs.json` equivalent to the base summary charts.
```suggestion
  has explicitly defined summary charts appended in `roles.d/jobs.json` or your custom summary chart `.json` file that are equivalent to the base summary charts.
```

2024-06-25 18:32 UTC, aestoltm requested changes
A few minor suggestions for `howto-colors.md`

2024-06-25 18:32 UTC, aestoltm commented on docs/howto-colors.md
> +]
Missing a ``` at the end of the last json block.

2024-07-01 19:55 UTC, Macman1234 commented on docs/howto-colors.md
> +]
done!

2024-07-01 19:59 UTC, Macman1234 commented on docs/howto-summary-charts.md
> +and in some `.json` files located in `roles.d` (`/etc/xdmod/roles.d/` or `PREFIX/xdmod/roles.d/` respectively). The files that contain `+summary_charts` are typically organized into different realm c
Should I switch it back to the language describing _any_ `.json` file in that folder being parsed for roles?

2024-07-03 19:12 UTC, Macman1234 commented
I ended up making some changes to what you had suggested. It should still all be in line with the recommended method of creating a new JSON file to store any new summary charts. Let me know how it's looking.

I also fixed some more linter issues in the color article.

2024-07-13 00:06 UTC, aestoltm requested changes
The `howto-summary-charts.md` changes look good! I had two minor suggestions for the `howto-colors.md` and I made a note about extra whitespace in that file.

2024-07-13 00:06 UTC, aestoltm commented on docs/howto-colors.md
> +If I selected the second `123456`, though, the next two groups, would *still* be colored `AABBCC` and `CCBBAA`.
```suggestion
Selecting the second `123456` in the palette would result in the next two groups *still* being colored `AABBCC` and `CCBBAA`.
```

2024-07-13 00:06 UTC, aestoltm commented on docs/howto-colors.md
There is a bit of whitespace on the ends of the palettes and I believe on the end of some sentences. It looks like the linter output from the CI build was cut off.

2024-07-19 18:57 UTC, Macman1234 commented on docs/howto-colors.md
Ugh, linter misconfig (on a different editor than the one I got working for the last linting problems) strikes again. Fixed, though I didn't notice any at the end of sentences, just in the palettes.

2024-07-19 18:58 UTC, Macman1234 commented on docs/howto-colors.md
> +The second palette below shows a workaround for this to add both an 8-element and 10-element Viridis gradient, by
Great idea, will make that change.

2024-07-25 19:19 UTC, aestoltm approved these changes
Everything looks good to me. Thank you for the contribution!

2024-07-25 20:54 UTC, Macman1234 commented
> Everything looks good to me. Thank you for the contribution!

Thanks for the help on this, Andrew!

FYI, I don't have write access and so can't merge this myself. I assume there are other things that happen before this gets merged, but wanted to make sure you knew I couldn't do that.

2024-07-26 15:51 UTC, aestoltm commented
> > Everything looks good to me. Thank you for the contribution!
> 
> Thanks for the help on this, Andrew!
> 
> FYI, I don't have write access and so can't merge this myself. I assume there are other things that happen before this gets merged, but wanted to make sure you knew I couldn't do that.

Thanks for the heads up. Merging this now.

2024-07-26 15:53 UTC, merged