Highcharts conversion to Plotly JS
ubccr/xdmod pull request #1822
Opened 2024-02-13 23:33 UTC by aestoltm

## Description

These changes are for the Summary, Usage and Metric Explorer Tabs.

 **When finding a bug please compare with an instance running Highcharts** so we know if this is an existing bug or not.

**Features not in Plotly JS yet**
- Hover events styling marker and line sizes
- Shadow
## Motivation and Context

Plotly JS has no license requirement which is desirable for Open XDMoD.

## Tests performed

Tested on docker and dev-port. Will be converting the Playwright tests to work with Plotly JS.

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2024-03-13 14:19 UTC, aaronweeden commented
Some files still reference HighCharts; this will list them (run in your cloned copy of this branch):
```
grep -ir --exclude-dir .git HighChart .
```

2024-04-09 13:10 UTC, eiffel777 commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                menu.add({
What is the purpose of the two menu elements below? I'm not sure I see what an end user would use them for. Are they leftovers from helping debug?

2024-04-09 18:50 UTC, ryanrath commented on NOTICE
> -Name:    Highcharts
I think Plotly should probably be added to this file.

2024-04-09 18:50 UTC, ryanrath commented on html/gui/js/modules/Usage.js
> +                                    if (dtick === 86400000 && evt.data[evt.curveNumber].x.length > 7) {
Not a huge fan of magic numbers, would it be possible to pull this into a variable w/ a descriptive name?

2024-04-09 18:50 UTC, ryanrath commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                if (visible !== true) {
Is `visibility[originalTitle]` sometimes not a boolean value? Just seems like an odd little bit of logic.

2024-04-09 18:50 UTC, ryanrath commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                            pointSelected = seriesObj.x;
Does there need to be a break here? Or is it that `seriesObj.y === point.y` is guaranteed to only occur once?

2024-04-09 19:04 UTC, aestoltm commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                if (visible !== true) {
Yeah it can be `legendonly` or `true`. It actually should never be 'false' because that means it would be removed from the plot also. I had it checking `legendonly` before but it threw a linter error.

2024-04-09 19:07 UTC, aestoltm commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                menu.add({
I had it in for debugging before but left it because I didn't know if it would be useful to keep it or not. I can remove it if it doesn't seem necessary

2024-04-09 19:08 UTC, aestoltm commented on html/gui/js/modules/Usage.js
> +                                    if (dtick === 86400000 && evt.data[evt.curveNumber].x.length > 7) {
Should be able to. The 86400000 is equivalent to a dtick of '1 day'

2024-04-09 19:20 UTC, ryanrath commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                menu.add({
It might be a good candidate for people with the `developer` ACL.

2024-04-09 19:21 UTC, ryanrath commented on html/gui/js/modules/Usage.js
> +                                    if (dtick === 86400000 && evt.data[evt.curveNumber].x.length > 7) {
sweet.

2024-04-15 18:03 UTC, aaronweeden requested changes
I have not reviewed everything in this PR yet, but here are some initial suggestions.

104 is a lot of commits; I would recommend squashing ones that don't make it easier to review.

2024-04-15 18:54 UTC, aestoltm commented on background_scripts/chrome-helper/chrome-helper.js
> +#!/usr/bin/node
That shouldn't be changed. I think it snuck in when I initially worked on getting the export working.

2024-04-26 13:16 UTC, aaronweeden commented on NOTICE
> +Author:  Plotly and contributors
Where does this string come from? The `LICENSE` file in the GitHub repo says `Plotly, Inc`

2024-04-26 13:18 UTC, aaronweeden commented
`docs/xdmod-rest-schema.json` still references `highcharts`.

2024-04-30 19:08 UTC, aaronweeden commented on NOTICE
> +Name:    Plotly, Inc.
```suggestion
Name:    Plotly.js
```

2024-04-30 19:08 UTC, aaronweeden commented on NOTICE
> +Author:  Plotly, Inc. and contributors
Where does the `and contributors` come from?

2024-05-01 14:44 UTC, aestoltm commented on NOTICE
> +Author:  Plotly, Inc. and contributors
I had that because of the open source contributions to Plotly JS

2024-05-01 16:00 UTC, aaronweeden requested changes

2024-05-01 16:00 UTC, aaronweeden commented on background_scripts/chrome-helper/chrome-helper.js
> +    // HTML tags in titles thorw xml not well-formed error
```suggestion
    // HTML tags in titles throw xml not well-formed error
```

2024-05-01 16:00 UTC, aaronweeden commented on background_scripts/chrome-helper/chrome-helper.js
> +    const svgInnerHtml = svg.replace(/<br>|<br\/>|<br \/>|<\/span>|<span|<sub>|<\/sub>|<sup>|<\/sup>|<b>|<\/b>/gm, (str) => {
These aren't the only title tags that can cause an error. Looks like anything between `<` and `>`.

2024-05-01 17:05 UTC, aaronweeden requested changes

2024-05-01 17:05 UTC, aaronweeden commented on docs/new-charting-library.md
> +- Chart axes are draggable to adjust chart range.
```suggestion
- Chart axes are draggable to adjust the chart range. For charts in the Metric Explorer, the axis range can be reset to the default through the axis context menu. For other charts, the chart can be reset to the default by double-clicking.
```

2024-05-01 17:05 UTC, aaronweeden commented on docs/new-charting-library.md
> +- Change layering for multiple axis charts.
```suggestion
- The ability to change the layering order for charts with multiple axes.
```

2024-05-01 17:05 UTC, aaronweeden commented on docs/new-charting-library.md
> +- Shadow
```suggestion
- Shadow.
```

2024-05-01 17:05 UTC, aaronweeden commented on docs/new-charting-library.md
> +- Change layering for multiple axis charts.
It looks like the `Layer` option is still available in the context menu.

2024-05-01 17:05 UTC, aaronweeden commented on docs/new-charting-library.md
> +The following are known issues in Open XDMoD 11.0.
```suggestion
```
The title of this section is self-explanatory.

2024-05-01 17:17 UTC, aaronweeden commented on docs/new-charting-library.md
> +
```suggestion

- For line charts, the context menu for a data series is brought up by clicking on its points, not its lines. As before, the context menu can also be brought up by clicking on it in the legend.
```

2024-05-01 17:37 UTC, aaronweeden commented on classes/DataWarehouse/Access/Usage.php
> -                            $meDataSeries['name'] = "${primaryDataSeriesRank}. " . $meDataSeries['name'];
It appears this now makes `$primaryDataSeriesRank` an unused variable.

2024-05-01 17:38 UTC, aaronweeden commented on classes/DataWarehouse/Access/Usage.php
>                      // the data labels.
This comment should be removed if it no longer applies.

2024-05-01 17:39 UTC, aaronweeden commented on classes/DataWarehouse/Access/Usage.php
>                      // in the Usage chart only.
This comment should be removed if it no longer applies.

2024-05-01 17:42 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +    protected $_prevCategory = null;
Does this need to be `null` or can it just be undefined?

2024-05-01 17:45 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +                $pointInterval = (365.25);
```suggestion
                $pointInterval = 365.25 / 12;
                break;
            case 'Quarter':
            case 'quarter':
                $pointInterval = 365.25 / 4;
                break;
            case 'Year':
            case 'year':
                $pointInterval = 365.25;
```

2024-05-01 17:51 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +        // otherwise, just call it (see above)
This comment appears to be outdated.

2024-05-01 17:55 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +                        continue 2; // bug? comment above mentions break but uses continue
Yep, looks like it should be `break 2`.

2024-05-01 17:57 UTC, aaronweeden commented on classes/DataWarehouse/Access/Usage.php
> +                } elseif ($usageChartSettings['display_type'] != 'h_bar'){
```suggestion
                } elseif ($usageChartSettings['display_type'] != 'h_bar') {
```

2024-05-01 17:57 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +            if ($yAxisIndex > 0){
```suggestion
            if ($yAxisIndex > 0) {
```

2024-05-01 18:04 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +            }
```suggestion
            if ($yAxisIndex > 0) {
                $side = 'left';
                $anchor = 'free';
                if ($yAxisIndex % 2 == 1) {
                    $side = 'right';
                }
                if ($yAxisIndex == 1) {
                    $anchor = 'x';
                }
                $yAxis = array_merge($yAxis, array(
                    'side' => $side,
                    'anchor' => $anchor,
                    'autoshift' => true,
                ));
            }
```

2024-05-01 18:04 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +                $legendRank+=2;
```suggestion
                $legendRank += 2;
```

2024-05-01 18:06 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +                $isThumbnail = !($this->_width > \DataWarehouse\Visualization::$thumbnail_width);
```suggestion
                $isThumbnail = $this->_width <= \DataWarehouse\Visualization::$thumbnail_width;
```

2024-05-01 18:12 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +    // TODO: Two main implementations, need to choose which one would be better.
Better to have `TODO`s documented elsewhere rather than in the code.

2024-05-01 18:14 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +    // Export chart object aoverlayings JSON, indicate count.
```suggestion
    // Export chart object as JSON, indicate count.
```
Looks like a paste typo (paste-o?)

2024-05-01 18:17 UTC, aaronweeden commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +    // ---------------------------------------------------------
```suggestion
    /**
     * Set annotations within the layout array based on the
     * requested type of labels and other configuration settings.
     */
```

2024-05-01 18:30 UTC, aaronweeden commented on html/gui/js/PlotlyPanel.js
> +                this.store.on('load', function (t, records, opitons) {
```suggestion
                this.store.on('load', function (t, records, options) {
```

2024-05-01 20:24 UTC, aaronweeden commented on html/gui/js/PlotlyPanel.js
> +     * TODO:error display for plotly charts
Better to have `TODO`s documented elsewhere instead of in the code.

2024-05-01 20:34 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +        }
```suggestion
            {
                source: 'gui/images/report_thumbnail_no_data.png',
                align: 'center',
                xref: 'paper',
                xanchor: 'center',
                yanchor: 'center',
                yref: 'paper',
                sizex: 1.0,
                sizey: 1.0,
                x: 0.5,
                y: 1.0
            }
```

2024-05-01 20:37 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +            if (points.length !== 0 && points[0].children) {
```suggestion
            if (points.length > 0 && points[0].children) {
```

2024-05-01 20:39 UTC, aestoltm commented on html/gui/js/PlotlyPanel.js
> +     * TODO:error display for plotly charts
I think that is an old TODO from the initial implementation. It can be removed.

2024-05-01 20:40 UTC, aestoltm commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +    // TODO: Two main implementations, need to choose which one would be better.
This can be removed. It is an old comment from Highcharts2.php

2024-05-01 20:40 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +    const findPoint = (evt, traces) => {
Is there a reason this function definition is nested in the definition for `function getClickedPoint`? I would recommend avoiding nesting the definition if possible.

2024-05-01 20:40 UTC, aestoltm commented on classes/DataWarehouse/Visualization/AggregateChart.php
> +                        //TODO: Ajust data labels
This is an old comment from the initial aggregate chart implementation. This can be removed.

2024-05-01 20:44 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +        }
```suggestion
        if ((layout.swapXY && layoutKeys[i].startsWith('xaxis'))
            || layoutKeys[i].startsWith('yaxis')
        ) {
            multiAxes.push(layoutKeys[i]);
        }
```

2024-05-01 20:50 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +    }
```suggestion
    const axisKeyStart = (layout.swapXY ? 'x' : 'y') + 'axis';
    for (let i = 0; i < layoutKeys.length; i++) {
        if (layoutKeys[i].startsWith(axisKeyStart)) {
            multiAxes.push(layoutKeys[i]);
        }
    }
```

2024-05-01 20:54 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +        }
```suggestion
        if (firstRender || prevLineCount === update.subtitleLineCount) {
            update.chartUpdates['margin.t'] = 45 + subtitle_lines.length * 15;
        }
```

2024-05-01 20:54 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +    if (len > 0) {
```suggestion
    const update = { chartUpdates: {}, subtitleLineCount: 0 };
    if (subtitle.length > 0) {
```

2024-05-01 20:59 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +function topLegend(layout) {
```suggestion
function isTopLegend(layout) {
```
Would also require another change in this file and in `html/.eslintrc.json`.

2024-05-01 21:02 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +                                    : Math.min(chartDiv._fullLayout.margin.t, chartDiv._fullLayout._size.t);
```suggestion
        const func = (legendHeight === 0) ? Math.max : Math.min;
        let marginTop = func(chartDiv._fullLayout.margin.t, chartDiv._fullLayout._size.t);
```

2024-05-01 21:05 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +        const exportShift = isExport ? 30 : 0;
```suggestion
        const exportShift = isExport ? 30 : 0;
```
I would move this to right after the declaration of `const shiftYDown` to put it closer to where it is used.

2024-05-01 21:09 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +        // We need set tickmode to auto if so.
```suggestion
        // We need set to tickmode to auto if so.
```

2024-05-01 21:36 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +        }
```suggestion
        const axis = (evt.layout.swapXY ? 'y' : 'x') + 'axis';
        if (evt.layout[axis].type === 'date') {
            if (
                (
                    evt.layout[axis].dtick === CCR.xdmod.ui.dtickDay
                    && evt.data[evt.curveNumber].x.length > 7
                ) || (
                    visibleData.length === 1
                    && visibleData[0].index === evt.curveNumber
                )
            ) {
                tickType = 'auto';
            } else {
                tickType = 'date';
            }
        } else {
            tickType = 'category';
        }
        Plotly.relayout(chartDiv, { `${axis}.tickmode`: tickType });
```

2024-05-01 21:38 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +                const errorBar = evt.layout.swapXY ? 'error_x.visible' : 'error_y.visible';
Can declare `errorBar` above the if/else to avoid having to declare it in both.

2024-05-01 21:49 UTC, aaronweeden commented on html/gui/js/modules/dashboard/ReportThumbnailsComponent.js
> +                        this.tmpHpc = new CCR.xdmod.ui.PlotlyPanel({
I think the `tmpHpc` variable was probably named as a misspelling of `tmpHcp` and could use a better name.

2024-05-06 16:52 UTC, aaronweeden commented on CHANGELOG.md
> +    - Open XDMoD is now no longer bundled with any non-commercial licenses. The charting library used in Open XDMoD has changed from [Highcharts](https://www.highcharts.com/) to [Plotly JS](https://p
```suggestion
    - Open XDMoD is now no longer bundled with any non-commercial licenses. The charting library used in Open XDMoD has changed from [Highcharts](https://www.highcharts.com/) to [Plotly JS](https://plotly.com/javascript/), an open source library. This transition removes the non-commercial license required from the Highcharts library. Please refer to the [license notices](https://open.xdmod.org/11.0/notices.html) for more information about the open source licenses bundled with Open XDMoD.
```

2024-05-06 16:59 UTC, aaronweeden commented on CHANGELOG.md
> +        - Rendering support for a subset of HTML tags in a chart's main title. Please refer to the [list](https://plotly.com/javascript/reference/layout/annotations/#layout-annotations-items-annotati
I would actually list the tags here since it is a small list and because the documentation at that URL can and will change without our 11.0 source code syncing to it.

2024-05-06 17:02 UTC, aaronweeden commented on CHANGELOG.md
> +        - Rendering support for a subset of HTML tags in a chart's main title. Please refer to the [list](https://plotly.com/javascript/reference/layout/annotations/#layout-annotations-items-annotati
```suggestion
        - Rendering support for a subset of HTML tags in a chart's main title. Please refer to the [list](https://plotly.com/javascript/reference/layout/annotations/#layout-annotations-items-annotation-text) of supported HTML tags. Unsupported tags will render as plain text instead of HTML.
```

2024-05-06 17:12 UTC, aaronweeden commented on CHANGELOG.md
> +    - Chart Features Temporarily Removed
```suggestion
    - Chart Features Removed
```
I'm going back on my previous suggestion since I think we shouldn't suggest these will be put back in unless we have a roadmap for doing so.

2024-05-06 17:39 UTC, aaronweeden commented on html/gui/js/libraries/PlotlyUtilities.js
> +        // We need set the tickmode to auto if so.
```suggestion
        // We need to set the tickmode to auto if so.
```
Sorry, I typoed my suggestion last time.

2024-05-06 17:44 UTC, aaronweeden commented on html/gui/js/modules/dashboard/ReportThumbnailsComponent.js
> +                        this.reportCharts = new CCR.xdmod.ui.PlotlyPanel({
I'd suggest renaming `reportCharts` to `reportChartsPanel`.

2024-05-06 18:32 UTC, aaronweeden commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> -            layerItems.push({
The `layerItems` variable is defined elsewhere and can be removed.

2024-05-06 18:43 UTC, aaronweeden commented on CHANGELOG.md
> +            - Degrees
```suggestion
        - Rendering support for a subset of HTML tags and entities in a chart's main title. Unsupported tags/entities will render as plain text instead of HTML. The following HTML tags are supported: <br>, <b>, <i>, <sup>, <sub>, and <a>. The following entities are supported: Greek letters (recommended Unicode format, e.g., &#x3BC; for lowercase mu), some mathematical symbols (e.g., &plusmn; for ±), and degrees (&deg;).
```

2024-05-06 19:51 UTC, ryanrath commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                    // We also want to strip out the anchor tag to avoid nefarious links.
So while I appreciate taking the time to think about security here, I would recommend backing this change out so that we can more holistically address the `encode/decode` issue in the future.

2024-05-06 20:56 UTC, aestoltm commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                    // We also want to strip out the anchor tag to avoid nefarious links.
Its a new feature that the charts render a subset of HTML tags. The charts supported HTML tags are listed [here](https://plotly.com/chart-studio-help/adding-HTML-and-links-to-charts/). Im not sure, but I believe the only tag we would be worried about is the anchor tag. Plotly won't render <img> tags or anything not on that list. Should we be okay to keep the current sanitization? Otherwise anchor tags in the chart title will render anything given.

2024-05-06 21:01 UTC, aaronweeden commented on CHANGELOG.md
> +        - Rendering support for a subset of HTML tags and entities in a chart's main title. Unsupported tags/entities will render as plain text instead of HTML. The following HTML tags are supported:
```suggestion
        - Rendering support for a subset of HTML tags and entities in a chart's main title. Unsupported tags/entities will render as plain text instead of HTML. The following HTML tags are supported: `<br>`, `<b>`, `<i>`, `<sup>`, and `<sub>`. The following entities are supported: Greek letters (recommended Unicode format, e.g., `&#x3BC;` for lowercase mu), some mathematical symbols (e.g., `&plusmn;` for ±), and degrees (`&deg;`).
```

2024-05-07 13:56 UTC, ryanrath commented on html/gui/js/modules/metric_explorer/MetricExplorer.js
> +                    // We also want to strip out the anchor tag to avoid nefarious links.
Coolio, all set then.

2024-05-07 15:05 UTC, aaronweeden approved these changes

2024-05-07 17:13 UTC, merged