Add properties for request method and path to parsed web server logs.
ubccr/xdmod pull request #1824
Opened 2024-02-21 23:08 UTC by aaronweeden

## Description

This PR updates the web server log parser to split the request line (e.g., `GET /index.html HTTP/1.1`) into two new properties for ease of access: 
* `request_method` (e.g., `GET`).
* `request_path` (e.g., `/index.html`).

## Motivation and Context

This enables https://github.com/ubccr/xdmod-ondemand/pull/46 and https://github.com/ubccr/xdmod-ondemand/pull/47.

## Tests performed

I tested ingesting logs on my port on `xdmod-dev` with the changes from this PR, https://github.com/ubccr/xdmod-ondemand/pull/46, and https://github.com/ubccr/xdmod-ondemand/pull/47.

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2024-05-16 17:47 UTC, jpwhite4 commented
The webserver log parser already supports requestMethod (%m) and url === requestPath (%U) format strings. 

Why don't we use these?

2024-05-16 17:49 UTC, jpwhite4 requested changes

2024-05-16 17:49 UTC, jpwhite4 commented on classes/ETL/DataEndpoint/WebServerLogFile.php
> +            $requestParts = explode(' ', $decoded->request);
In general can't guarantee that request is in the decoded output (e.g. could use "%m %U %H" instead of "%r") [in fact we probably want to do this in the ondemand module]

2024-05-16 17:49 UTC, jpwhite4 commented on classes/ETL/DataEndpoint/WebServerLogFile.php
> +            $requestParts = explode(' ', $decoded->request);
If you really do want to do this I recommend a `property_exists` guard around it.

2024-05-20 17:32 UTC, aaronweeden commented
> The webserver log parser already supports requestMethod (%m) and url === requestPath (%U) format strings.
> 
> Why don't we use these?

@jpwhite4 Thanks, I have refactored it to use `%m`, `%U`, and `%H`; added unit tests; and updated https://github.com/ubccr/xdmod-ondemand/pull/50.

2024-05-22 17:37 UTC, jpwhite4 approved these changes

2024-05-22 21:03 UTC, merged