Allow multiple columns and multiple files in `RegexTransformIngestor`.
ubccr/xdmod pull request #1838
Opened 2024-05-08 15:49 UTC by aaronweeden

## Description

This PR allows the `RegexTransformIngestor` to transform multiple columns and use multiple files to configure the transformation.

## Motivation and Context

This enables https://github.com/ubccr/xdmod-ondemand/pull/50, specifically the ability to have a separate `application-map.json` and `request-path-filter.json` for each resource being ingested.

## Tests performed

I tested ingesting logs on my port on xdmod-dev with the changes from https://github.com/ubccr/xdmod-ondemand/pull/50 and the PRs on which it depends.

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2024-05-13 19:25 UTC, jpwhite4 commented on classes/ETL/Ingestor/RegexTransformIngestor.php
> +        $outdata = $srcRecord;
I think that this function is called for each record in the data: You should avoid opening and parsing config files in this function instead do the configuration setup once in the constructor.

2024-05-14 13:11 UTC, aaronweeden commented on classes/ETL/Ingestor/RegexTransformIngestor.php
> +        $outdata = $srcRecord;
I have updated it to do the opening and parsing in the constructor.

2024-05-16 17:56 UTC, jpwhite4 requested changes

2024-05-16 17:56 UTC, jpwhite4 commented on classes/ETL/Ingestor/RegexTransformIngestor.php
> +                $this->logger->debug("$dest: Ignore $srcColumn");
Should this debug statement be in the `else` part of the if statement on line 81? If you have multiple regexes then one can match and another not match and the row will not be ignored. It will only be ignored if all of the regexes fail to match.

2024-05-17 16:48 UTC, aaronweeden commented on classes/ETL/Ingestor/RegexTransformIngestor.php
> +                $this->logger->debug("$dest: Ignore $srcColumn");
Thanks, I have updated it.

2024-05-29 19:58 UTC, jpwhite4 approved these changes

2024-06-11 17:46 UTC, merged