Add additional information for 11.0 upgrade
ubccr/xdmod pull request #1879
Opened 2024-06-27 15:54 UTC by ryanrath

## Description
Added additional documentation on how to update the xdmod DB user to work when the XDMoD webserver is migrated to a new host. 

## Motivation and Context
It's important for installations that host the XDMoD DB on a different server than the XDMoD Web Server to ensure that the database user XDMoD uses is updated to reflect a change in the XDMoD Web Server's hostname. Failure to do this will result in XDMoD not being able to funciton due to permission denied errors.

## Tests performed

## Checklist:

- [ ] The pull request description is suitable for a Changelog entry
- [ ] The milestone is set correctly on the pull request
- [ ] The appropriate labels have been added to the pull request

2024-06-27 16:06 UTC, aaronweeden commented on docs/upgrade.md
> +5. **NOTE:** MariaDB / MySQL users are defined as `'username'@'hostname'` so if the hostname of the server that the user is connecting from changes, you will need to make sure that this change is ref
```suggestion
5. **NOTE:** MariaDB / MySQL users are defined as `'username'@'hostname'` so if the hostname of the Rocky 8 web server is different than the hostname of the CentOS 7 web server, you will need to make sure that this change is reflected in the database.
```

2024-08-23 18:49 UTC, aestoltm requested changes
From my notes during metrics-staging upgrade

> For the upgrade documentation, we may want to also include reminders for copying over more than just /etc/xdmod/, also copying over the Apache config, sendmail config, etc

2024-08-23 18:49 UTC, aestoltm commented on docs/upgrade.md
I believe we want to specify the mongo version here. From the notes when you were helping with staging it looks like specifically `$ yes '' | pecl install mongodb-1.18.1`

2024-09-04 18:17 UTC, ryanrath commented
@aestoltm do you happen to have a list of the configs that should be transferred?

2024-09-04 19:10 UTC, aestoltm approved these changes

2024-09-04 19:53 UTC, merged