Add resource specifications documentation
ubccr/xdmod pull request #1892
Opened 2024-08-02 14:47 UTC by eiffel777

This adds documentation for the Resource Specifications realm.

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2024-08-02 17:59 UTC, aaronweeden requested changes

2024-08-02 17:59 UTC, aaronweeden commented on docs/configuration.md
> +The `resource_allocation_type` option indicated how this resource is allocated
```suggestion
The `resource_allocation_type` option indicates how this resource is allocated
```

2024-08-02 17:59 UTC, aaronweeden commented on docs/configuration.md
> +still active. The `end_date` should not be include for the last entry for a
```suggestion
still active. The `end_date` should not be included for the last entry for a
```

2024-08-02 17:59 UTC, aaronweeden commented on docs/configuration.md
> +Defines how a resource is allocated to user.  Each resource in `resources.json`
```suggestion
Defines how a resource is allocated to users.  Each resource in `resources.json`
```

2024-08-02 17:59 UTC, aaronweeden commented on docs/resource_specifications.md
> +The Resource Specifications realm in Open XDMoD provides a way to track the changes in computing capacity over time, such as the number of CPUs and GPUs as well as CPU Hours, GPU Hours and other metr
```suggestion
The Resource Specifications realm in Open XDMoD provides a way to track the changes in computing capacity over time, such as the number of CPUs and GPUs as well as CPU Hours, GPU Hours and other metrics. The source for these data is the `resource_specs.json` configuration file (see the [Configuration Guide](configuration.md)). The data
```

2024-08-02 17:59 UTC, aaronweeden commented on docs/resource_specifications.md
> +for this file is ingested into the XDMoD database when `xdmod-ingestor` is run. The only extra command needed is to aggregate the data using the [`xdmod-ingestor`](ingestor.md) command. Please see th
```suggestion
from this file are ingested into the XDMoD database when `xdmod-ingestor` is run. The only extra command needed is to aggregate the data using the `xdmod-ingestor` command. Please see the [`xdmod-ingestor` guide](ingestor.md) guide for further information.
```

2024-08-02 17:59 UTC, aaronweeden commented on docs/resource_specifications.md
Where is this file to be linked from?

I'm not sure listing out the metrics and dimensions is going to be much more helpful that having them available in the Metric Explorer. We also might forget to keep this list in sync if we make changes to the data warehouse configuration.

2024-08-05 14:30 UTC, eiffel777 commented on docs/resource_specifications.md
My thinking was that this is more for people who haven't install XDMoD yet and want to know what is available if they install XDMoD.

2024-08-06 17:00 UTC, jpwhite4 commented on docs/configuration.md
> +`CPU`, `CPUNode`, `GPU`, `GPUNode`.
Can you add a sentence to explain what the options mean. e.g. CPUNode allocation seems a bit oxymoronic.

2024-08-29 15:36 UTC, aaronweeden requested changes

2024-08-29 15:36 UTC, aaronweeden commented on docs/resource-specifications.md
> +The Resource Specifications realm in Open XDMoD provides a way to track the changes in computing capacity over time, such as the number of CPUs and GPUs as well as CPU Hours, GPU Hours and other metr
```suggestion
The Resource Specifications realm in Open XDMoD provides a way to track the changes in computing capacity over time, such as the number of CPUs and GPUs as well as CPU Hours, GPU Hours and other metrics. The source for this data is the `resource_specs.json` configuration file (see the [Configuration Guide](configuration.md)). The data
```

2024-08-29 15:36 UTC, aaronweeden commented on docs/resource-specifications.md
> +for this file is ingested into the XDMoD database when `xdmod-ingestor` is run. The only extra command needed is to aggregate the data using the [`xdmod-ingestor`](ingestor.md) command. Please see th
```suggestion
for this file are ingested into the XDMoD database when `xdmod-ingestor` is run. The only extra command needed is to aggregate the data using the `xdmod-ingestor` command. Please see the [`xdmod-ingestor` guide](ingestor.md) for further information.
```

2024-08-29 15:36 UTC, aaronweeden commented on docs/resource-specifications.md
> +  - The average number of CPU nodes per day during the days in which the resource(s) were operational during selected time period. This does not take into account downtimes, outages of resources, or
```suggestion
  - The average number of CPU nodes per day during the days in which the resource(s) were operational during the selected time period. This does not take into account downtimes, outages of resources, or the percent of a resource allocated.
```

2024-08-29 15:36 UTC, aaronweeden commented on docs/resource-specifications.md
> +  - A resource is defined as any compute infrastructure.
In `configuration/datawarehouse.d/ref/group-by-common.json`, it says `A resource is a remote computer that can run jobs.`

2024-08-29 15:36 UTC, aaronweeden commented on docs/ingestor.md
> +        $ xdmod-ingestor --aggregate=resourcespecs --last-modified-start-date "$last_modified_start_date"
```suggestion
Set timestamp:

    $ last_modified_start_date=$(date +'%F %T')

Aggregate:

    $ xdmod-ingestor --aggregate=resourcespecs --last-modified-start-date "$last_modified_start_date"
```
To keep formatting consistent with other sections above.

2024-08-29 15:36 UTC, aaronweeden commented on docs/ingestor.md
> +
This appears to be missing the ingestion step.

2024-08-29 15:36 UTC, aaronweeden commented on docs/configuration.md
> +node of CPU's to users.
```suggestion
`CPU`, `CPUNode`, `GPU`, and `GPUNode`. `CPUNode` denotes a resource that allocates
nodes of CPUs to users, whereas `CPU` denotes a resource that allocates individual CPUs
to users.
```

2024-08-29 15:36 UTC, aaronweeden commented on docs/resource_specifications.md
I see. I hadn't realized we have similar pages for Cloud, Storage, and GPU metrics.

2024-09-04 16:12 UTC, eiffel777 commented on docs/ingestor.md
> +
The ingestion step for the resource specs is run when you `xdmod-ingestor` for any of the other realms. Actually, anytime `xdmod-ingestor` is run the resources.json and resource_specs.json is ingested. There isn't a command to just ingest the resource and resource specs data. Only an extra command to aggregate the data.

2024-09-04 17:31 UTC, aaronweeden commented on docs/ingestor.md
> +
OK, as written the instructions look like you set a timestamp and then aggregate, which would not aggregate anything since nothing has been ingested after the timestamp is set. I'd suggest removing the set timestamp step from this section and mention in the paragraph above it that `last_modified_start_date` should have been set previously and what to do if it wasn't.

2024-09-04 18:05 UTC, eiffel777 commented on docs/ingestor.md
> +
I updated the text but it still might need some help with clarity.

2024-09-06 18:14 UTC, aaronweeden commented on docs/ingestor.md
> +or Cloud data, you may have already set the `last-modified-start-date` shell variable. Otherwise,
```suggestion
or Cloud data, you may have already set the `$last_modified_start_date` shell variable. Otherwise,
```

2024-09-06 18:14 UTC, aaronweeden commented on docs/ingestor.md
> +run after you edited the `resource_specs.json` file.
```suggestion
run and after you edited the `resource_specs.json` file.
```

2024-09-10 14:14 UTC, merged