Adding logic to catch invalid datetime values
ubccr/xdmod pull request #1896
Opened 2024-08-09 20:11 UTC by ryanrath

## Description
Additional Validation of both ISO8601 Date & Unix Timestamp parameters REST parameters have been added. 

## Motivation and Context
Aaron noted in https://app.asana.com/0/159049597309611/1208001546005418/f that it seemed like invalid values ( ex. `2024-01-99`) were being accepted for date parameters provided to rest endpoints.

These changes add additional validation to both ISO8601 Date & Unix Timestamp parameters where `DateTime::getLastErrors()` is checked to see if there are any warnings or errors before possibly returning a value.

New tests were added per conversation with Aaron.

## Tests performed
All automated tests were run / passed. 

## Checklist:

- [X] The pull request description is suitable for a Changelog entry
- [X] The milestone is set correctly on the pull request
- [X] The appropriate labels have been added to the pull request

2024-08-12 13:36 UTC, aaronweeden requested changes

2024-08-12 13:36 UTC, aaronweeden commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    if ($lastErrors['warning_count'] > 0 || $lastErrors['error_count'] > 0) {
If there were no errors, will this statement cause `Warning: Trying to access array offset on value of type bool`?

2024-08-12 13:36 UTC, aaronweeden commented on tests/integration/lib/BaseTest.php
> +                            ('string' === $id && 'string_params' === $key)) {
For readability, I would swap the two conditions to match the order of the comments above.

2024-08-12 13:36 UTC, aaronweeden commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    if ($lastErrors['warning_count'] > 0 || $lastErrors['error_count'] > 0) {
Is `$lastErrors['error_count'] > 0` necessary; i.e., is there a way for it to be true and for `$value_dt` not to be false?

2024-08-13 15:07 UTC, ryanrath commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    if ($lastErrors['warning_count'] > 0 || $lastErrors['error_count'] > 0) {
Doesn't seem to, here's an example w/ no errors showing that the property `error_count` is still present. 
```php
$value = '2024-09-99';
$datetime = \DateTime::createFromFormat('Y-m-d', $value);
print_r(DateTime::getLastErrors());

Output:
Array
(
    [warning_count] => 1
    [warnings] => Array
        (
            [10] => The parsed date was invalid
        )

    [error_count] => 0
    [errors] => Array
        (
        )

)
```

2024-08-13 15:28 UTC, ryanrath commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    if ($lastErrors['warning_count'] > 0 || $lastErrors['error_count'] > 0) {
No idea, but since it was always present I added it to the `if`, I can remove it. I did find an interesting update to this, apparently the return value changes depending on what version of PHP is used. I've made the necessary updates to future proof the code in an upcoming commit.

2024-08-13 15:28 UTC, ryanrath commented on tests/integration/lib/BaseTest.php
> +                            ('string' === $id && 'string_params' === $key)) {
sure

2024-08-13 15:28 UTC, ryanrath commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                        throw new BadRequestHttpException("Invalid value for $name. Must be a(n) Unix timestamp.");
sure

2024-08-15 23:43 UTC, aaronweeden commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    if ($lastErrors['warning_count'] > 0 || $lastErrors['error_count'] > 0) {
I was referring to the case where the value is a valid date; as you note below, this will be `false` in PHP ≥8.2.0.

2024-08-15 23:44 UTC, aaronweeden commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    if ($lastErrors['warning_count'] > 0 || $lastErrors['error_count'] > 0) {
Looks like this code needs to be updated to match the code below.

2024-08-15 23:54 UTC, aaronweeden commented on classes/Rest/Controllers/BaseControllerProvider.php
> +                    if ($lastErrors['warning_count'] > 0 || $lastErrors['error_count'] > 0) {
Maybe best to define a function since it will be duplicated code. Something like:
```php
"options" => function ($value) {
    return self::filterDate('U', $value);
}
// ...
"options" => function ($value) {
    return self::filterDate('Y-m-d', $value);
}
```
```php
private static function filterDate(string $format, string $value)
    $value_dt = DateTime::createFromFormat($format, $value);
    $lastErrors = DateTime::getLastErrors();
    if ($value_dt === false || (is_array($lastErrors) && $lastErrors['warning_count'] > 0)) {
        return null;
    }
    return $value_dt;
}
```

2024-08-16 19:44 UTC, aaronweeden submitted a review, later dismissed
Since there is a `use DateTime`, the backslashes in front of `\DateTime` aren't necessary, but it's up to you if you want to change those or merge as is.

2024-08-19 17:17 UTC, aaronweeden approved these changes

2024-08-19 17:18 UTC, merged