Adding columns for resource, PI, and person organization ID for cloud realm
ubccr/xdmod pull request #1936
Opened 2024-10-28 15:47 UTC by eiffel777

This adds the Resource, PI, and Person organization ID columns for the cloud realm. The `cloud-state-pipeline` etl pipeline has been added to the migration to re-aggregate the cloud realm so these columns are added and the columns are populated. These columns are used in the xsede module at this point in time.

## Tests performed
Tested in docker.

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2024-11-22 20:23 UTC, jpwhite4 requested changes

2024-11-22 20:23 UTC, jpwhite4 commented on classes/OpenXdmod/Migration/Version1050To1100/DatabasesMigration.php
> +                ['cloud-migration-10-5-0_11-0-0','cloud-state-pipeline'],
Should this be changed to an 11.0.0 -> 11.0.1 migration? We can't be modifying the 10.5 to 11.0 migration anymore since the 11.0.0 is released

2025-01-29 16:39 UTC, aaronweeden commented
It looks like this should be based on `xdmod11.0` branch instead of `main`.

2025-01-30 13:07 UTC, eiffel777 commented
This is replaced by #1966

2025-01-30 13:07 UTC, closed without merging