Adding resource_organization_id, person_organization_id, piperson_organization_id to cloudfact tables
ubccr/xdmod pull request #1956
Opened 2024-12-04 15:11 UTC by eiffel777

## Description
This adds the Resource, PI, and Person organization ID columns for the cloud realm. These columns are used in the xsede module at this point in time.

## Motivation and Context
We want to track the organizations that a person, resource and PI belong to.

## Tests performed
Tested in docker

## Checklist:

- [x] The pull request description is suitable for a Changelog entry
- [x] The milestone is set correctly on the pull request
- [x] The appropriate labels have been added to the pull request

2024-12-04 21:22 UTC, jpwhite4 submitted a review, later dismissed

2024-12-04 21:29 UTC, aaronweeden requested changes
Does there need to be a PR into `xdmod-xsede` that updates these files to add the `piperson_organization_id` column?
```
configuration/etl/etl_action_defs.d/cloud_access/access_cloud_metrics_aggregation.json
configuration/etl/etl_action_defs.d/cloud_access/access_cloud_metrics_aggregation_by_day.json
configuration/etl/etl_tables.d/cloud_jetstream/jetstream_cloudfact_by_.json
configuration/etl/etl_tables.d/cloud_jetstream/jetstream_cloudfact_by_day.json
```

2024-12-04 21:45 UTC, aaronweeden requested changes

2024-12-04 21:45 UTC, aaronweeden commented on configuration/etl/etl_action_defs.d/cloud_common/session_records.json
> +          ],
```suggestion
        ],
```

2024-12-04 21:45 UTC, aaronweeden commented on configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
The `comment` on line 6 says `Euca` — should that be `Cloud`?

2024-12-04 21:45 UTC, aaronweeden commented on configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
> +                "person_organization_id": "sr.person_organization_id",
It looks like in `xdmod-xsede` in `configuration/etl/etl_action_defs.d/cloud_access/access_cloud_metrics_aggregation.json` it gets a value for `person_organization_id` by joining the `person` table instead of adding a column to the `session_records` table. Is there a preference for which way to do it?

2024-12-04 21:52 UTC, aaronweeden requested changes

2024-12-04 21:52 UTC, aaronweeden commented on configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
> +                "comment": "DIMENSION: The organization of the person that ran the jobs."
```suggestion
                "comment": "DIMENSION: The organization of the person to whom the VM is assigned."
```

2024-12-04 21:52 UTC, aaronweeden commented on configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
> +                "default": -1,
This is `1` in `xdmod-xsede` in `configuration/etl/etl_tables.d/cloud_jetstream/jetstream_cloudfact_by_.json`.

2024-12-04 21:54 UTC, aaronweeden commented on configuration/etl/etl_tables.d/cloud_common/cloudfact_by_day.json
> +                "comment": "DIMENSION: The organization of the PI that owns the project that funds these jobs. References piperson.organization_id"
```suggestion
                "comment": "DIMENSION: The organization of the PI that owns the project that funds these VMs. References piperson.organization_id"
```

2024-12-04 23:22 UTC, eiffel777 commented on configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
> +                "person_organization_id": "sr.person_organization_id",
I like getting it from `modw_cloud.session_records` better. I'll put in PR to `xdmod-xsede` to have them use the same column.

2024-12-06 18:39 UTC, eiffel777 commented on configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
> +                "person_organization_id": "sr.person_organization_id",
@aaronweeden PR to change this is https://github.com/ubccr/xdmod-xsede/pull/530

2024-12-06 18:39 UTC, eiffel777 commented
> Does there need to be a PR into `xdmod-xsede` that updates these files to add the `piperson_organization_id` column?
> 
> ```
> configuration/etl/etl_action_defs.d/cloud_access/access_cloud_metrics_aggregation.json
> configuration/etl/etl_action_defs.d/cloud_access/access_cloud_metrics_aggregation_by_day.json
> configuration/etl/etl_tables.d/cloud_jetstream/jetstream_cloudfact_by_.json
> configuration/etl/etl_tables.d/cloud_jetstream/jetstream_cloudfact_by_day.json
> ```

@aaronweeden This was added in https://github.com/ubccr/xdmod-xsede/pull/530

2024-12-06 18:39 UTC, eiffel777 commented on configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
> +                "default": -1,
This was changed in https://github.com/ubccr/xdmod-xsede/pull/530

2024-12-06 18:40 UTC, eiffel777 commented on configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
> +                "resource_organization_id": "sr.resource_organization_id",
I removed this. It should probably change to using resource_organization_id in the future since there is a common group by for service provider that uses that column

2024-12-06 18:41 UTC, eiffel777 commented on configuration/etl/etl_tables.d/cloud_common/cloudfact_by_.json
It probably should but I will change that some other time in a different PR. I want to keep this PR focused on just the organization ids.

2024-12-06 19:46 UTC, aaronweeden requested changes

2024-12-06 19:46 UTC, aaronweeden commented on configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
>                  "account_id": "sr.account_id",
Does this need to be `COALESCE(sr.account_id, -1)`? That's how it is in `xdmod-xsede`: `configuration/etl/etl_action_defs.d/cloud_access/access_cloud_metrics_aggregation.json`. It looks like there are some other fields like `person_id` that are going from a nullable column to a non-nullable column so there might need to be some more `COALESCE`s.

2024-12-06 19:46 UTC, aaronweeden commented on configuration/etl/etl_action_defs.d/cloud_common/session_records.json
> +            "person_organization_id": "p.organization_id",
```suggestion
            "person_organization_id": "COALESCE(p.organization_id, -1)",
```

2024-12-06 19:46 UTC, aaronweeden commented on configuration/etl/etl_action_defs.d/cloud_common/session_records.json
> +            "piperson_organization_id": "pi.organization_id",
```suggestion
            "piperson_organization_id": "COALESCE(pi.organization_id, -1)",
```

2024-12-06 19:46 UTC, aaronweeden commented on configuration/etl/etl_action_defs.d/cloud_common/session_records.json
> +            },
```suggestion
```
It looks like this isn't needed anymore.

2024-12-06 21:01 UTC, eiffel777 commented on configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
>                  "account_id": "sr.account_id",
There probably are other fields `COALESCE`s should be put on, but I think is better put in a new PR since that affects fields not related to this PR.

2024-12-06 21:01 UTC, eiffel777 commented on configuration/etl/etl_action_defs.d/cloud_common/cloud_metrics_aggregation.json
I think this is best addressed in a separate PR.

2024-12-10 19:39 UTC, aaronweeden approved these changes

2024-12-10 19:45 UTC, merged